### ISSUE TITLE
CDN script doesn't work for IE (indentify method is broken)

### ISSUE THREAD

**Issue by nhim175** [DavidWells/analytics#10]
I found that by calling `.identify(userId)` on IE 11 will cause this issue 
```
Object.keys: argument is not an Object
```

## Steps to reproduce
- Open IE 11 on BrowserStack or a Windows machine
- Call `.identify` and provide a string as argument

**Comment by DavidWells** [comment]
Thanks for report. I will have a look.

Couple of questions to help debug:

- What version are you running?
- Are you using any provider plugins? 
- Can you share how you are calling this in your code
- Is it possible to send more of the stack track (or even better a live link to the site)

Seems like one of the `Object.keys` calls is getting malformed data https://github.com/DavidWells/analytics/search?q=Object.keys&unscoped_q=Object.keys

Likely inside plugin engine https://github.com/DavidWells/analytics/blob/a9f3244605b1a891fff6aff1c29604f86469a460/packages/analytics-core/src/middleware/plugins/engine.js

**Comment by DavidWells** [comment]
Also are you using the unpkg version of the script?

```
<script src="https://unpkg.com/analytics/dist/analytics.min.js"></script>
```

Or is this installed as a dependency on your project

**Comment by DavidWells** [comment]
Any updates here @nhim175 ?

Can you share the code you are using?

**Comment by DavidWells** [comment]
Closing this for now. 

Please re-open if you can provide more information on how to reproduce
