### ISSUE TITLE
Support for Client / Session / Visit ID etc.

### ISSUE THREAD

**Issue by totalhack** [DavidWells/analytics#100]
Hi there,

First off thanks for putting this library together. Before I go down the road of trying to develop something myself, I was wondering if you know of any plugins or related projects that can help in the generation *and* management of IDs. I know your utils library has a `uuid` function, but I'm looking for something a bit more similar to what GA does (without necessarily depending on GA) with perhaps a few extras, such as:

- Generate a long-lived Client ID with parameterized expiration (GA leaves it for 2 years since last visit by default). Renew each time the user visits before expiration.
- Generate a Session ID with parameterized expiration (default 24 hours in GA I believe). Renew each time the user visits before expiration.
- Generate a Visit ID on each entrance (not a concept in GA but something I'd use for additional granularity). Reset when referrer is not same domain, or when the session has expired.

I would then aim to be able to tie any events back to any of these IDs, but mainly the Visit ID since others could be tied to that. Generation of the IDs is easy, it's mainly the other stuff or some combination of it all where I'm wondering if a solution/plugin exists.

It looks like your storage utils have an automatic fallback mechanism in terms of where these things could get stored (cookie vs localStorage) which is nice, but I didn't see a `ttl` param there like you have on the cookie util functions.

In my particular situation, I'd be storing events and tying things together in a custom backend but also feeding GA. 

Thanks for taking a look.

**Comment by DavidWells** [comment]
Hello @totalhack 

Cool use case ideas 😃

The lifecycle of all values set to localstorage/cookies/memory is pluggable. This means you can set any value you want and overide the default `uuid` for the visitor.

It sounds like you might need the `setItemStart` and `bootstrap` [event hooks](https://getanalytics.io/lifecycle/). 

Here is an example plugin for this:

```js
import analyticsLib from 'analytics'

const customAnonIdPlugin = {
  name: 'set-anon-id',
  // On storage event, intercept and value custom value
  setItemStart: ({ payload, instance }) => {
    if (payload.key === '__anon_id') {
      return {
        ...payload,
        ...{ value: 'new-value-xyz' }
      }
    }
  }
}

const customBootstrap = {
  name: 'custom-bootstrap-logic-plugin',
  // Run when analytics starts up
  bootstrap: ({ payload, instance }) => {
    // Do custom cookie stuff or whatever else when analytics starts
    // check cookies/reset/set them etc
  }
}

// Initialize analytics
const Analytics = analyticsLib({
  app: 'site',
  version: '1.0.0',
  debug: true,
  plugins: [
    // Custom stuff on analytics startup
    customBootstrap,
    // Set custom values
    customAnonIdPlugin,
    // Load analytics providers...
    googleTagManagerPlugin({
      containerId: 'GTM-XYZ'
    }),
    ...
  ]
})
```

Under the hood analytics uses https://getanalytics.io/utils/cookies/#setcookie for cookies but yeah it looks like ttl is not passed in right now to https://github.com/DavidWells/analytics/blob/4f2b7fdc12d4acfd06a23b3099dcd39e5ea5cd3e/packages/analytics-util-storage/src/index.js#L77 . 

I'd recommend using `@analytics/cookie-utils` pkg in bootstrap event

**Comment by totalhack** [comment]
Thanks for your feedback. I had actually already started a similar approach leveraging the bootstrap hook to initialize IDs and override the anonymous ID, though I did that via `instance.setAnonymousId`.

I plan to open source what I'm working on, so I'll share more details once it gets to that point, hopefully in the coming weeks. I'd be interested to get your feedback on the approach at that point.

**Comment by totalhack** [comment]
I have a very early version of this available. It ended up being a slightly opinionated plugin basically that implements the features i'm looking for.  Here is the meat:

https://github.com/totalhack/zar/blob/main/frontend/src/zar.js

Disclaimer: javascript is not my expertise. I'll close this out, thanks.
