### ISSUE TITLE
Plugin Request: indicative

### ISSUE THREAD

**Issue by antoniopaolillo** [DavidWells/analytics#101]
Having this lib plugin would be great! 
link: https://app.indicative.com/

**Comment by DavidWells** [comment]
Hey there @antoniopaolillo  

Thanks for the plugin request.

I won't have the bandwidth to write/maintain a plugin for indicative.

That said, it's pretty easy to create a plugin for any provider. Here are the docs https://getanalytics.io/plugins/writing-plugins/#1-provider-plugins

It's really a matter of mapping their calls, to the analytics primitives `page`, `track`, `identity` etc

```js
export default function providerPluginExample(userConfig) {
  // return object for analytics to use
  return {
    /* All plugins require a name */
    name: 'my-example-plugin',
    /* Everything else below this is optional depending on your plugin requirements */
    config: {
      whatEver: userConfig.whatEver,
      elseYouNeed: userConfig.elseYouNeed
    },
    initialize: ({ config }) => {
      // load provider script to page
    },
    page: ({ payload }) => {
      // call provider specific page tracking
    },
    track: ({ payload }) => {
      // call provider specific event tracking
    },
    identify: ({ payload }) => {
      // call provider specific user identify method
    },
    loaded: () => {
      // return boolean so analytics knows when it can send data to third party
      return !!window.myPluginLoaded
    }
  }
}
```

Let me know if you have any questions on this

**Comment by DavidWells** [comment]
A consolidated issue has been created at https://github.com/DavidWells/analytics/issues/153 for plugin requests.

Feel free to comment/reopen this thread if you have begun active development on this plugin.
