### ISSUE TITLE
plugin custom events dependent on ready() completing?

### ISSUE THREAD

**Issue by fraser-m-hurley-LTK** [DavidWells/analytics#105]
Hi, I'm building out a custom plugin which exposes some methods for page speed events to be captured and sent to an in house analytics BE. One of the things we are keen to do is perform correction on client side timestamps (by comparing the client side timestamp to a server timestamp). The intention is for the comparison to be done during bootstrap() or ready() and then apply that correction to subsequent events.

I read through #9 which I think hints the core analytics lib performs as I would like (for this case) but wanted to check. Am I correct in saying that method calls like page, track or a custom plugin event will not fire until bootstrap() and/or ready() have completed?

Thanks Fraser

**Comment by DavidWells** [comment]
You might want to checkout / use the https://github.com/DavidWells/analytics/tree/master/packages/analytics-plugin-perfumejs plugin and send the data this way. Here is a video explaining the plugin https://www.youtube.com/watch?v=9DZAVpAubtQ&t=21s

> Am I correct in saying that method calls like page, track or a custom plugin event will not fire until bootstrap() and/or ready() have completed?

`analytics.page` etc queue events to be fired by any plugins that have a matching `.page` method. If their loading state is `true` there is no waiting to execute them.

Plugins fire when their individual state is set to `loaded` when the `loaded` function evaluates to true https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-google-analytics/src/browser.js#L227

If you exclude the `loaded` method, it will default to true. 

Another option is using custom methods ([example](https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-segment/src/browser.js#L35)). https://getanalytics.io/plugins/writing-plugins/#adding-custom-methods

Custom methods run whenever you fire them with no queuing mechanism.

---

Here is an example if you want to debug when things fire. Add redux dev tools to your browser and you will see all events flowing through the system

```js
const analyticsLib = require('analytics')
const googleAnalytics = require('@analytics/google-analytics')

const originalGA = googleAnalytics({
  trackingId: '1234'
})

const myPluginOverrides = {
  page: ({ payload }) => {
    const { properties } = payload
    console.log('See all props properties', properties)
    // Note this will disable data from sending to GA.
    // use for for debugging or sending data elsewhere
  },
  methods: {
    doThing: () => {
      console.log('My thing!')
    }
  }
}

const customPageGoogleAnalytics = Object.assign({}, originalGA, myPluginOverrides)

const analytics = analyticsLib({
  app: 'my-app-name',
  debug: true,
  plugins: [
    customPageGoogleAnalytics
  ]
})

// Using custom methods in your code
analytics.plugins['google-analytics'].myCustomThing()

// Page call made
analytics.page()

// The google analytics plugin will call it's .page method when loaded evaluates to true
// https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-google-analytics/src/browser.js#L227
```

**Comment by fraser-m-hurley-LTK** [comment]
Thanks for the reply David. As custom methods are treated slightly differently its expected I wouldn't see them fire when using redux dev tools right? I was also curious as to what the difference between `EVENTS` https://getanalytics.io/plugins/writing-plugins/#adding-custom-methods and `methods` keys are? It sounds like they perform a similar function?

**Comment by DavidWells** [comment]
Yeah, custom methods don't show up in redux dev tools. They are for provider-specific functionality.

```js
import Analytics from 'analytics'

const customPlugin = {
  name: 'xyzPlugin',
  methods: {
    // Firable via analytics.plugins.xyzPlugin.myCustomThing()
    myCustomThing(one, two, three) {
      const analyticsInstance = this.instance
      console.log('Use full analytics instance', analyticsInstance)
    }
  },
  // Firable via undocumented analytics.dispatch('customActionTriggeredByDispatch')
  customActionTriggeredByDispatch: () => {
    console.log('all plugins with customActionTriggeredByDispatch will fire')
  }
}

// Initialize analytics instance with plugins
const analytics = Analytics({
  app: 'your-app-name',
  plugins: [
    customPlugin,
  ]
})
```
