### ISSUE TITLE
Segment plugin: "options" parameter is discarded on "track()" invocations

### ISSUE THREAD

**Issue by FranFu-OC** [DavidWells/analytics#108]
When calling the .track() method to record a Segment "track" event, it is not possible to override the object fields due to the missing handling of the "option" parameter used by the native segment library.

File reference: node_modules/@analytics/segment/dist/@analytics/segment.js:194

https://github.com/DavidWells/analytics/blob/222a99d2d6372057f4fdb109463891ec90c4e301/packages/analytics-plugin-segment/src/browser.js#L127

```
    /* Track Segment event http://bit.ly/2WLnYkK */
    track: ({ payload }) => {
      if (typeof analytics === 'undefined') return

      analytics.track(payload.event, payload.properties)
    },
```

Tested fix:

```
    /* Track Segment event http://bit.ly/2WLnYkK */
    track: ({ payload }) => {
      if (typeof analytics === 'undefined') return

      analytics.track(payload.event, payload.properties, payload.options)
    },
```

**Comment by DavidWells** [comment]
Thanks for report!

Released update in `@analytics/segment@0.5.1`
