### ISSUE TITLE
TypeError in core: undefined is not a function

### ISSUE THREAD

**Issue by pechischev** [DavidWells/analytics#117]
I finded that problem in my Sentry. But i can't reproduced the error.

Example here: 

![image](https://user-images.githubusercontent.com/14825339/99249941-f4218e80-281b-11eb-9e02-7645eceaf83a.png)

Reproduced only on the desktop browsers - using Chrome (version: 85.0.4183) Windows 10

Current version of plugins:

```
"analytics": "0.5.5",
"@analytics/google-analytics": "0.5.2",
"@analytics/google-tag-manager": "0.3.0",
```

**Comment by DavidWells** [comment]
Sounds like the plugins value is undefined https://github.com/DavidWells/analytics/blob/master/packages/analytics-core/src/index.js#L130

What does the configuration of your analytics look like in your code?

**Comment by pechischev** [comment]
Looks like that

```
const analytics = Analytics({
  plugins: [
    googleTagManager({
      containerId: isProduction ? GTM_PRODUCTION_ID : isStaging ? GTM_STAGING_ID : null,
    }),
    googleAnalytics({
      trackingId: isProduction ? GTAG_PRODUCTION_ID : isStaging ? GTAG_STAGING_ID : null,
      customDimensions: {
        id: 'dimension1',
        type: 'dimension2',
        balance: 'dimension3',
      },
    }),
    yandexMetric({
      ymId: isProduction ? YM_PRODUCTION_ID : isStaging ? YM_STAGING_ID : null,
    }),
  ],
})
```

yandex-metric is a custom plugin built according to your README. Example here: https://github.com/pechischev/analytics-yandex-metric-plugin

**Comment by DavidWells** [comment]
Interesting... 

Does the sentry error say the type of browser / version the error came from?

It's possible that `new Set` or `Array.from` are throwing in old versions of a particular browser.

**Comment by pechischev** [comment]
Yes, senty said the type. This is the latest version of chrome, described above. I will repeat here again - **Chrome (version: 85.0.4183) Windows 10.**

And the strangest thing is that I tested on the same version and didn't see any errors
