### ISSUE TITLE
Amplitude plugin support

### ISSUE THREAD

**Issue by wyattEpp** [DavidWells/analytics#120]
Is an Amplitude plugin planned for the future? Documentation graphic seems to indicate Amplitude is a supported analytics service, but it does not appear in source.

![Screen Shot 2020-11-23 at 2 53 24 PM](https://user-images.githubusercontent.com/8572924/100014183-a8329480-2d9b-11eb-9fc2-1528d1d1c53e.png)

**Comment by DavidWells** [comment]
There is an open PR to add amplitude https://github.com/DavidWells/analytics/pull/19

We need to change it slightly to load the amplitude library like other integrations work like [this](https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-google-analytics/src/browser.js#L66-L71) where the library uses the embed code provided by amplitude

**Comment by DavidWells** [comment]
A consolidated issue has been created at https://github.com/DavidWells/analytics/issues/153 for plugin requests.

Feel free to comment/reopen this thread if you have begun active development on this plugin.
