### ISSUE TITLE
Add changelog or releases with notes

### ISSUE THREAD

**Issue by lukasoppermann** [DavidWells/analytics#121]
Hey @DavidWells,

I know this adds more work on your side, but it would be great if you could add some release notes so that one can find out what the difference between e.g. version 0.5.5 and 0.6.0 is. 

Thanks.

**Comment by DavidWells** [comment]
Hey @lukasoppermann 

All the packages should have a `CHANGELOG.md` file like https://github.com/DavidWells/analytics/blob/master/packages/analytics-core/CHANGELOG.md

**Comment by lukasoppermann** [comment]
Ahh, I only looked at the top level. I may not that used to packages within packages that are not npm imports. Thanks
