### ISSUE TITLE
multiple instances of Segment

### ISSUE THREAD

**Issue by jhonsfran** [DavidWells/analytics#126]
I wonder if I can use multiple instances of segment in the same project.

I have a Software as a Service and I want to track all the data in each tenant but I want to give the possibility to the owner of each tenant configure their segment instance as well.

Is this possible?

**Comment by DavidWells** [comment]
I'm not sure. I believe this would require multiple versions of segment loaded on the page.

Do they support this?

**Comment by jhonsfran** [comment]
I don't think so. Just curious if I can do something like this https://getanalytics.io/plugins/google-tag-manager/#using-multiple-instances-of-gtm but with Segment.

**Comment by DavidWells** [comment]
I think you would need to setup a custom proxy https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/custom-proxy/ 

Let me know if you setup a proxy endpoint and what to test this out. We could add a [`customScriptSrc`](https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-google-analytics/src/browser.js#L37) option to segment plugin like other providers

**Comment by DavidWells** [comment]
Closing out for now. 

Open to PRs on adding this as option.

**Comment by dwjohnston** [comment]
Just putting it out there that this is something we're looking for too.

**Comment by dwjohnston** [comment]
If you're interested, here's my attempt to get this to work here: https://github.com/whispir/typewriter-example/blob/multiple-sources/README.md

(It didn't work, it appears that the first write key takes precedence)
