### ISSUE TITLE
If 'Google Analytics' and 'Google Tag Manager' both used, GTM breaks event category for GA

### ISSUE THREAD

**Issue by s3rious** [DavidWells/analytics#127]
Hi there!

I've got both 'Google Tag Manager' and 'Google Analytics' used on our code, here is an example of plugins:

```
Analytics({
  plugins: [
    googleTagManager({
      containerId: isProduction ? GTM_PRODUCTION_ID : isStaging ? GTM_STAGING_ID : null,
    }),
    googleAnalytics({
      trackingId: isProduction ? GTAG_PRODUCTION_ID : isStaging ? GTAG_STAGING_ID : null,
      customDimensions: {
        <...>
      },
    }),
  ],
})
```

And them both of them are used, `googleTagManager` plugin rewrites passed category to 'All'.

Here is an example of how I trigger an event:
```
analytics.track('Click ‘Get stated’', {
  category: 'Get started',
})
```

And that's what's triggered on `track`:
```
{
  action: "Click ‘Get stated’"
  properties: {
    category: "All",
    anonymousId: "<...>"
}
```

I've dug deeper to, and that's what I've found. Inside `track` function of GTM plugin category used as `payload.category` but in reality it's passed as `payload.properties.category` → https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-google-tag-manager/src/browser.js#L60

Here is a runtime screenshot.
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/1730834/101774958-d932f900-3aff-11eb-9039-d31735156b3c.png">

I'm not sure why it was written this way, maybe in some cases passed as a `payload.category`, and in other as `payload.properties.category`. 

If that's not the case, I can fork, fix and create a pull request myself.

**Comment by DavidWells** [comment]
You are right. It should be `properties.category`

This is fixed and shipped (just now) with `@analytics/google-tag-manager@0.3.1`

**Comment by DavidWells** [comment]
Let me know if it doesn't work for you 😃

Thanks for the detailed report!
