### ISSUE TITLE
Track callback not waiting for requests to complete - expected?

### ISSUE THREAD

**Issue by totalhack** [DavidWells/analytics#132]
I'm implementing a custom plugin and running into a scenario where I'd like to wait until all plugin track requests have finished before allowing an event to propagate (a click redirect, so it will abort the requests if I don't wait or set a delay).

I came across the callback param in `track` and was hoping that would solve my problem, but it does not appear to be waiting for all requests to finish. I believe at a minimum part of the problem is that my custom plugin [makes a post request](https://github.com/totalhack/zar/blob/main/frontend/src/zar.js#L227) that it doesn't wait for. I'm also not returning any value and it got me questioning a few things:

1. Does analytics *intend* to wait for all requests to finish before calling the callback, or just for the plugin `track` calls to return async? 
2. What should a custom plugin return in `track`, if anything? Just wondering if returning the Promise from axios would lead to it getting used somewhere in `analytics` (not that I saw from a quick look at the code). 

I understand this is not a bug or issue in `analytics`, but just trying to confirm what the intended behavior is and whether the way I'm implementing my plugin is breaking anything.

Notably GA has a special way of handling this type of outbound click tracking as described [here](https://support.google.com/analytics/answer/1136920?hl=en). I was hoping the `analytics` callback would work in a similar way. If not I'll probably just fall back to using setTimeout before finishing the redirect.

**Comment by DavidWells** [comment]
Hello there! 

> 1. Does analytics intend to wait for all requests to finish before calling the callback, or just for the plugin track calls to return async?

Analytics calls happen as fast as they can, but do happen in order. You can make method calls async and make other wait

> 2. What should a custom plugin return in track, if anything? Just wondering if returning the Promise from axios would lead to it getting used somewhere in analytics (not that I saw from a quick look at the code).

Returning data from `track` is a way to enrich payloads for other plugins. You need to do this in `trackStart` or in `track:namespace` methods. Any example of this is here https://github.com/DavidWells/analytics/blob/master/examples/demo/src/utils/analytics/example-5.js 

Looks like you are [using this](https://github.com/totalhack/zar/blob/main/frontend/src/zar.js#L213-L216) already 🎉

Returning data from `track` will merge into the payload and pass into the `trackEnd` action

---

There are a couple of ways to do this. Heres what I'd recommend

You can make any methods (except `loaded`) async.

Adding an `async` / `await` to `axios.post(`${config.apiUrl}/track`, payload)` will wait for your remote call to finish before 

```js
export default function providerPluginExample(userConfig) {
  return {
    name: 'my-example-plugin',
    track: async ({ payload }) => {
      await axios.post(`${config.apiUrl}/track`, payload)
    },
    loaded: () => {
      return !!window.myPluginLoaded
    }
  }
}
```

Combine this with an `on` listener. https://getanalytics.io/api/#analyticson

```js
analytics.on('trackEnd', ({ payload }) => {
  console.log('called after all track methods called')
  // redirect or do other stuff
})
```

Or via a plugin `trackEnd` function in the original plugin or in another

```js
export default function otherPlugin(userConfig) {
  return {
    name: 'other-example-plugin',
    trackEnd: ({ payload }) => {
        console.log('called after all track methods called')
        // redirect or do other stuff
    },
  }
}
```

**Comment by totalhack** [comment]
Thanks, that is very helpful. 

I had thought about using `async` / `await` but am trying to maintain support for IE until it is more dead. If I did that in my custom plugin that also wouldn't guarantee other plugins` requests have finished before the redirect, although it would be more likely assuming they made their calls before mine. But I believe the way I have it ordered now my plugin [gets called first](https://github.com/totalhack/zar/blob/main/frontend/src/zar.js#L275). Perhaps I'd need to change that if I go down this path.

For now I'm going to live with the setTimeout approach outside of the plugin, but will revisit this down the road. 

Thanks again for the detailed examples.
