### ISSUE TITLE
有中国人吗，analytics的作用到底是什么

### ISSUE THREAD

**Issue by SoftwareEngineerPalace** [DavidWells/analytics#140]

**Comment by DavidWells** [comment]
Looks like this translates to:

> Are there any Chinese? What is the role of analytics?

I'd recommend checking out the docs at https://getanalytics.io/ and using google translate on them.

> Analytics is a lightweight abstraction library for tracking page views, custom events, & identify visitors. It is pluggable & designed to work with any third-party analytics tool or your own backend.

Analytics是一个轻量级的抽象库，用于跟踪页面视图，自定义事件和识别访问者。它是可插拔的，旨在与任何第三方分析工具或您自己的后端一起使用。

**Comment by SoftwareEngineerPalace** [comment]
> Looks like this translates to:
> 
> > Are there any Chinese? What is the role of analytics?
> 
> I'd recommend checking out the docs at https://getanalytics.io/ and using google translate on them.
> 
> > Analytics is a lightweight abstraction library for tracking page views, custom events, & identify visitors. It is pluggable & designed to work with any third-party analytics tool or your own backend.
> 
> Analytics是一个轻量级的抽象库，用于跟踪页面视图，自定义事件和识别访问者。它是可插拔的，旨在与任何第三方分析工具或您自己的后端一起使用。

i must choose the place to write log code.... so why do i use analytics... it is useless....
