### ISSUE TITLE
Upgrade analytics-node to resolve security issue in Axios

### ISSUE THREAD

**Issue by peterwj** [DavidWells/analytics#141]
Hello,

I run `yarn audit` on our app at work, and I notice the version of `axios` pulled in by `@analytics/segment`, 0.19.2, contains an [outstanding security issue](https://www.npmjs.com/advisories/1594).  

It looks like fixing it requires bumping the version of `analytics-node` (the Segment-provided npm package) [to 3.5](https://github.com/segmentio/analytics-node/releases/tag/v3.5.0).  Changing the version of `axios` is the only change mentioned in this release compared to the one currently used by the `@analytics/segment` package, so hopefully this is a simple operation.

Let me know if I can help!

**Comment by DavidWells** [comment]
Bumped the dep and released with `@analytics/segment@0.6.1`

**Comment by peterwj** [comment]
Thank you for the prompt response and the release!
