### ISSUE TITLE
Amplitude support?

### ISSUE THREAD

**Issue by pranasziaukas** [DavidWells/analytics#142]
First of all, this seems like a very neat project, I'm sure everyone appreciates quality analytics, so thanks for that! :)

Looking at the README, I got a strong impression that the library comes with batteries-included support for Amplitude analytics, mostly because its logo is featured in the intro animation:
<img width="833" alt="Screenshot 2021-02-04 at 17 09 17" src="https://user-images.githubusercontent.com/26874494/106913978-3e285b00-670d-11eb-8c35-2aae97026b18.png">

However, upon further inspection, it looks like that might not be the case as Amplitude is not listed in https://github.com/DavidWells/analytics#analytic-plugins
So a working plugin needs to be created first to get the ball rolling to Amplitude, is that correct?

Cheers.

**Comment by DavidWells** [comment]
Hey @pranasziaukas 

Apologies for that 😃

We have this long-standing PR out for amplitude https://github.com/DavidWells/analytics/pull/19

The implementation looks good to me in https://github.com/DavidWells/analytics/blob/262ed4d778554fa443f3cbfa00c51647aa787e80/packages/analytics-plugin-amplitude-browser/src/index.js#L19 but I haven't had the time to test this out.

Would you folks be interested in testing it & helping get it across finish line?

You can see the [mapped calls here](https://github.com/DavidWells/analytics/blob/262ed4d778554fa443f3cbfa00c51647aa787e80/packages/analytics-plugin-amplitude-browser/src/index.js#L45-L61)

I think the main blocker was the amplitude SDK is included in the package https://github.com/DavidWells/analytics/blob/262ed4d778554fa443f3cbfa00c51647aa787e80/packages/analytics-plugin-amplitude-browser/src/index.js#L1 versus being loaded into the page via the `initialize` call like [this example](https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-gosquared/src/browser.js#L50-L79)

**Comment by pranasziaukas** [comment]
Thanks for the useful pointer @DavidWells, we'll look into it!

**Comment by johnparn** [comment]
Hi!

@DavidWells The current solution in PR #19 seems to work just fine, at least the browser-version. Why is it preferred to load the SDK through `initialize` instead of having a dependency to `amplitude-js`? 

I took a quick look at loading the amplitude SDK through `initialize`, but I didn't come up with an immediate solution and will have to revisit the code.
