### ISSUE TITLE
New Plugin!

### ISSUE THREAD

**Issue by elvisace** [DavidWells/analytics#143]
Hi @DavidWells !

I wrote this (very simple!) plugin that essentially sends the payload genrated by `analytics` to a custom url. Take a look at it and let me know if you're interested in making it part of the `analytics` packages.

https://www.npmjs.com/package/@standardorg/analytics-fetch

**Comment by DavidWells** [comment]
Hey, nice plugin!

I've added to the docs https://github.com/DavidWells/analytics/blob/master/external-plugins.json 😃

**Comment by elvisace** [comment]
Thanks @DavidWells!
