### ISSUE TITLE
analytics.track payload for GA

### ISSUE THREAD

**Issue by gragland** [DavidWells/analytics#15]
I'm currently tracking events and have the GA plugin added, but I'm having trouble finding the payload values when browsing events within my GA dashboard. Looking at the GA plugin I'm seeing that it expects `label`, `value`, `category` in the payload (not any key:values we want). Is that correct? I'm somewhat new to the GA interface so I apologize in advance if the data is there and I'm just not finding it. My code looks like this:

```js
analytics.track('chooseStackOption', {
  type: 'framework',
  option: 'next.js'
});
```

**Comment by DavidWells** [comment]
Hey @gragland

What are you looking to track inside of GA? 

For `ga` events you would want to fire events like:

```js
analytics.track('eventName', {
  category: 'yourEventCategory' // defaults to 'All' if empty
   // what form is this? If this is part of an A/B test, what variation?
  label: 'xyz',
  // how much is this action worth?
  value: 0
})
```

The category is mapped here: https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-ga/src/browser.js#L78

And the label/value are mapped here: https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-ga/src/browser.js#L96-L100

---

On a side note, the benefit of `analytics` plugins being POJOs (plain ol' javascript objects) is they are easy to customize if the default behavior doesn't fit your use case.

Example:

```js
import Analytics from 'analytics'
import googleAnalytics from 'analytics-plugin-ga'

const gaPlugin = googleAnalytics({
  trackingId: 'UA-121491291',
})

const myCustomOverride = Object.assign({}, gaPlugin, {
  track: ({ payload, config }) => {
    console.log('do my custom thing')
    console.log('Instead of base tracking call from google plugin')
  }
})

/* Initialize analytics with modified plugin */
const analytics = Analytics({
  app: 'my-app',
  version: '1.0.2',
  plugins: [
    myCustomOverride
  ]
})
```

You can use ^ this method to experience with updates to the core plugin and then I'm happy to look at anything we need to add into the project.

**Comment by gragland** [comment]
Okay, thanks for clarifying! I saw the [usage example](https://github.com/DavidWells/analytics#usage) in the readme and incorrectly assumed GA allowed any key/value pair. Might avoid confusion by using `label` and `value` there or making a note of it somewhere in the docs.

And thanks for the customization example! That's super useful.

**Comment by DavidWells** [comment]
Good point. I will update the docs.

There is some additional work to be done with the GA plugin to support custom dimensions and stuff as well.

Right now those can all be handled with raw ‘ga’ calls in the code

**Comment by slidenerd** [comment]
Curious but related question, which analytics are you using? The older GA or the new GA GTM combo. The script of the newer one goes like this
```

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-145190952-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-111111111-1');
</script>

```

**Comment by DavidWells** [comment]
Hey @slidenerd

The google analytics plugin uses the regular google analytic script

https://github.com/DavidWells/analytics/tree/master/packages/analytics-plugin-ga

If you want to use google tag manager script instead you can use that plugin https://github.com/DavidWells/analytics/tree/master/packages/analytics-plugin-google-tag-manager

Just depends on your setup. 

I prefer the simpler “just google analytics” setup myself because I like keeping my js in my app instead of hidden in gtag manager tags
