### ISSUE TITLE
How to track events from a service worker

### ISSUE THREAD

**Issue by matthias-pichler** [DavidWells/analytics#157]
Is it somehow possible to track events inside the service worker using the same context as the main thread? Meaning without having to create a whole new `Analytics` instance.

Could this be achieved with `postMessage` somehow? What about "offline" events such as `onBackgroundMessage`?

**Comment by DavidWells** [comment]
Hey, @matthias-pichler-warrify not sure.

It should* work with via postMessage.

The analytics plugins themselves often load up a third-party analytics script into the DOM, this would need to happen in the main thread.

Whats the use case you have for running this in a service worker?

**Comment by matthias-pichler** [comment]
Yeah I also came across the requirement of some plugins that the DOM must be available which it isn't in service workers.

We have a service worker that handles push notifications. When a push notification is received or clicked one can attach an event listener to those. If the site is loaded this can be done in the in the main thread. However when a background notification is received there is no main thread. 

So what I would like to achieve is to track the fact that a push notification was received or clicked while in the background. This doesn't have to be instantaneous. So what I thought about would be storing the fact (e.g. in IndexedDB) and when the page is opened again flushing the queue.

I don't think [MessageChannels](https://developer.mozilla.org/en-US/docs/Web/API/MessageChannel) or [Broadcast Channels](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API) persist messages.

But I take that this is not something you have seen done before so I will probably have to explore myself.

**Comment by DavidWells** [comment]
Oh man, this is a cool use case!

Please share the result of how you do this if you can 😃

Analytics can run in memory in the service worker (this is how analytics runs in the server). This comes with some caveats where userId/anonId aren't persisted unless you supply your own storage mechanisms. You can supply your own (sync) storage mechanisms [like so](https://github.com/DavidWells/analytics/blob/master/packages/analytics/src/index.js#L5)

**Comment by DavidWells** [comment]
Closing this out for now. If you figured out how to do this it would be cool to see 😃

There is an `isBrowser` type checker in `@analytics/type-utils` package that could be added in plugins before any DOM calls are made
