### ISSUE TITLE
analytics-plugin-snowplow: JavaScript errors encountered when trying to use this package

### ISSUE THREAD

**Issue by bb-avinash** [DavidWells/analytics#158]
Encountering some JS errors when trying to use this analytics-plugin-snowplow.
Investigated them and found below issues. Are these to be fixed in the code or am I missing something else.

**Error 1:** 
TypeError: Cannot read property 'toLowerCase' of undefined
    at snowplowPlugin (/node_modules/@analytics/snowplow/lib/analytics-plugin-snowplow.cjs.js:57:71)

Investigation:
null-check and type-checks aren't being performed on optional properties in config in below line of code:
https://github.com/DavidWells/analytics/blob/911c2bea233ea3f9c3e6912e9ed716b0b3f6e208/packages/analytics-plugin-snowplow/src/node.js#L50

**Error 2:** 
ReferenceError: http is not defined
    at snowplowPlugin (/node_modules/@analytics/snowplow/lib/analytics-plugin-snowplow.cjs.js:58:15)

Investigation:
http and https node modules are used without being imported in below code:
https://github.com/DavidWells/analytics/blob/911c2bea233ea3f9c3e6912e9ed716b0b3f6e208/packages/analytics-plugin-snowplow/src/node.js#L57

**Comment by DavidWells** [comment]
Thanks for the report. This should be fixed and released with `@analytics/snowplow@0.2.5`

Can you give that a try and report back if this fixes the issue?
