### ISSUE TITLE
GA label always undefined

### ISSUE THREAD

**Issue by gragland** [DavidWells/analytics#16]
It looks like the value of `label` is stored in `payload.properties.label`, but the ga plugin tries to get it from `payload.label`.

https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-ga/src/browser.js#L71

Payload object:
![Screen Shot 2019-08-05 at 10 00 46 AM](https://user-images.githubusercontent.com/1481077/62481684-f0bddd00-b767-11e9-9e9c-572b433a4aa5.png)

**Comment by DavidWells** [comment]
Fixed with `analytics-plugin-ga@0.1.5`

Thanks for the report!
