### ISSUE TITLE
how to analyze outgoing link clicks?

### ISSUE THREAD

**Issue by CarltonHenderson** [DavidWells/analytics#160]
Is there a best practice for tracking links to external websites? e.g: running analytics on http://mysite.example to track the click on a link to http://external.example

Although I was expecting to, I couldn't find a recommendation in the readme or api docs. It wouldn't be possible with `onRouteChange from '@analytics/router-utils'` would it?

Thank you!

**Comment by DavidWells** [comment]
Hey good question.

This might make for a good util 😃

First check the domain against the current one to see if its external and then run `analytics.track` 

You can do this with an event listener or in a component like so:

```js
function getDomain(url) {
  return url.replace(/https?:\/\//, '').split('/')[0]
}

function isExternalLink(url) {
  if (typeof window === 'undefined') return true
  const currentDomain = location.href
  return getDomain(currentDomain) !== getDomain(url)
}

// React component example
export default function Link({ href, text }) {
  const trackExternalLink = async (e) => {
    e.preventDefault()
    // run track
    await analytics.track('externalLink', { href })
    // Load external page
  }

  const noOp = (e) => {}

  const tracker = isExternalLink(href) ? trackExternalLink : noOp

  return (
    <a href={href} onClick={handleClick}>
      {text}
    </a>
  )
}
```
