### ISSUE TITLE
@analytics/google-analytics: does not track page search (query parameters) 

### ISSUE THREAD

**Issue by denis-sokolov** [DavidWells/analytics#162]
analytics.page() call gathers the current page path with search (`?x=1`), but google-analytics ignores it and submits paths without it, preventing from analysing them in Google Analytics.

https://github.com/DavidWells/analytics/blob/0be72166f5ea1d7d4f09575927622db18d671d1f/packages/analytics-plugin-google-analytics/src/browser.js#L157-L168

**Comment by DavidWells** [comment]
Hey @denis-sokolov this is by design

Otherwise, page views would be split into several different "pages" in the GA dashboard.

If you'd like to customize this functionality you can override the default method like so:

```js
import Analytics from 'analytics'
import googleAnalytics from '@analytics/google-analytics'

const baseGAPlugin = googleAnalytics({
  trackingId: 'UA-1234567'
})

const customGAPlugin = {
  ...baseGAPlugin,
  ...{
    // Your custom page overide function
    page: ({ payload, config, instance }) => {
      const { properties } = payload
      const path = document.location.href

      ga(`set`, {
        page: path,
        title: properties.title
      })
      ga(`send`, 'pageview', {
        page: path,
        title: properties.title,
        location: properties.url
      })
    }
  }
}

const analytics = Analytics({
  app: 'awesome-app',
  plugins: [
    customGAPlugin
  ]
})


/* Track a page view */
analytics.page()

/* Track a custom event */
analytics.track('playedVideo', {
  category: 'Videos',
  label: 'Fall Campaign',
  value: 42
})

/* Identify a visitor */
analytics.identify('user-id-xyz', {
  firstName: 'bill',
  lastName: 'murray'
})
```

^ something like this should work for your use case.

I'm not sure you'd want the query params on the path tho because it will make the pageview data harder to deal with in GA UI

Instead, I'd use `analytics.track` to track query params as an event if you need to see those in GA v3

```js
if (queryParamsExist) {
analytics.track('queryParam', {
  category: 'params',
  label: queryParamValue,
})
}
```

**Comment by denis-sokolov** [comment]
I see your point of view. It makes a lot of sense, and it comes from a place of trying to set meaningful defaults, which is very valuable. In our project we have since resolved this, so consider the rest of the comment user feedback: take it for what it’s worth.

Smart defaults are great when they work exactly right. In this particular instance there are cases where this decision is not right. The behavior is different from the default `ga("send", "pageview")` behavior, so switching from native GA v3 to this package brings an unexpected surprise. One way or another the users who used GA v3 have handled the query parameters in the admin panel and my understanding is they would expect the analytics package to behave the same way without additional configuration. Worse, if one does not notice this immediately, this results in losing valuable tracking data for the entire period of using the unconfigured analytics package. I.e. the query parameters are never sent to the admin so the data is gone.

Putting the defaults aside, as much as pretty URLs are pretty, some websites do have less pretty URLs like “/product?id=123”. There seem to be tools in Google Analytics to distinguish meaningful query parameters from meaningless ([sample blog post](https://edit.co.uk/blog/how-to-handle-url-query-parameters-google-analytics/)), and those website owners need query parameters unconditionally.

Anyway, I appreciate the package and I appreciate the response. Seeing how GA v3 is being phased out, this issue is probably not something that matters much, so I’ll close it for clarity.
