### ISSUE TITLE
[Doc improvements] Payload "meta" data breaking change

### ISSUE THREAD

**Issue by pnarielwala-tc** [DavidWells/analytics#163]
Hello!

After updating `analytics`, I noticed that the meta object changed causing breaking changes in our codebase as we were using `meta.timestamp`:

Before:
https://github.com/DavidWells/analytics/blob/c7b75d6f778c76bf4f0b9502115a1092274b1d90/packages/analytics-core/src/index.js#L433-L435

After:
https://github.com/DavidWells/analytics/blob/master/packages/analytics-core/src/index.js#L825-L830

Although we can totally update to simply just call `new Date().getTime()` directly, it would be nice to understand the payload a bit better in the documentation. Thoughts?

Thanks!

**Comment by pnarielwala-tc** [comment]
This doc also utilizes `meta.timestamp` so this could cause some confusion

https://github.com/DavidWells/analytics/blob/master/site/main/source/resources/faq.md

**Comment by DavidWells** [comment]
Hey @pnarielwala 

Apologies for that change 😅

Was assuming this was internal only but you make a good point. Will be more cognisant of this in the future.

I've updated the reference in the docs.
