### ISSUE TITLE
Correct way of using Google Analytics plugin with HTML. Demo and example code don't work.

### ISSUE THREAD

**Issue by simon-bigsofa** [DavidWells/analytics#166]
Love the library but struggling to get the Google Analytics plugin working with HTML.

The demo and example here don't work: https://github.com/DavidWells/analytics/tree/master/examples/vanilla-html

The "Using in HTML" section of the docs here https://getanalytics.io/plugins/google-analytics/ don't seem to work either - `analyticsGA is not defined`

The script tag seems to return `analyticsGa` but when I change the code to use this then even though`analytics.page()` will fire a callback if provided, it does not send any data to GA. 

What is the correct way of setting up and using the Google Analytics plugin with HTML?

**Comment by DavidWells** [comment]
It should work with something like:

https://unpkg.com/@analytics/google-analytics@0.5.2/dist/@analytics/google-analytics.min.js is exposing analyticsGa to the window.

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Using @analytics/google-analytics in HTML</title>
    <script src="https://unpkg.com/analytics/dist/analytics.min.js"></script>
    <script src="https://unpkg.com/@analytics/google-analytics/dist/@analytics/google-analytics.min.js"></script>
    <script type="text/javascript">
      /* Initialize analytics */
      var Analytics = _analytics.init({
        app: 'my-app-name',
        plugins: [
          analyticsGa.init({
            trackingId: 'UA-1234567'
          })
        ]
      })

      /* Track a page view */
      analytics.page()

      /* Track a custom event */
      analytics.track('playedVideo', {
        category: 'Videos',
        label: 'Fall Campaign',
        value: 42
      })

      /* Identify a visitor */
      analytics.identify('user-id-xyz', {
        firstName: 'bill',
        lastName: 'murray'
      })
    </script>
  </head>
  <body>
    ....
  </body>
</html>
```

What does your HTML look like?

**Comment by DavidWells** [comment]
Aha I see the issue. The pkg name changed and the global is `analyticsGa` not `analyticsGA`

Checkout https://analytics-html-example.netlify.app/ for the fixed demo.

I've updated the docs as well.

**Comment by simon-bigsofa** [comment]
Thanks @DavidWells - got it working after making those changes.
