### ISSUE TITLE
Ternary operator throws error in runtime

### ISSUE THREAD

**Issue by johnparn** [DavidWells/analytics#169]
The following ternary operator throws an error when the amplitude plugin is loaded. Easily fixed by adding a semicolon at the end of:

https://github.com/DavidWells/analytics/blob/efe0751c16730a058baf0d3dbc56a303381e9037/packages/analytics-plugin-amplitude/src/browser.js#L51

The error message is:

`analytics-plugin-amplitude.browser.es.js:53 Uncaught (in promise) TypeError: "https://cdn.amplitude.com/libs/amplitude-8.1.0-min.gz.js" is not a function`

**Comment by DavidWells** [comment]
Aha! Thanks for quick fix

**Comment by DavidWells** [comment]
Released with `@analytics/amplitude@0.0.3`
