### ISSUE TITLE
Types of identify mismatch the implementation

### ISSUE THREAD

**Issue by Fnxxxxo** [DavidWells/analytics#172]
I found the type of `identify` requires userId. But the implementaion accepts params without userId which merges params with the local one. Any way to fix it? Typescript complains when compiling ` analytics.identify({})`

**Comment by DavidWells** [comment]
Identity takes optional id as first argument

```
analytics.identify('user-xyz', {})
```

Or just user attributes

```
analytics.identify({})
```

Will need to revisit how the types work here. For now, I'd recommend `ts-ignore`

---

Note to self: revisit when new typescript setup in place
