### ISSUE TITLE
Recipe for SPAs using hashes when page() only sends path

### ISSUE THREAD

**Issue by binarykitchen** [DavidWells/analytics#177]
Most Single Page Apps always have the same path in location, but their hashes change when user navigates.

Unfortunately the page() event for Google Analytics only sends path but not hashes.

```
ga("send", "pageview", {page: "/", title: "Home", location: "https://localhost:3000/"})
```

Should I hack and amend hashes like for example `#contact` to the path?

Like

```js
      analytics.page({
        title: 'Contact',
        path: '#contact'
      })
```

But then isn't that wrong? Hashed aren't part of a path. Hence asking for a recipe how to use your plugin properly for Single Page Apps, thanks!

**Comment by DavidWells** [comment]
Yeah you can override any value

```
onHashChange((hash) => {
  analytics.page({
     title: 'Contact',
     path: hash
  })
})
```

Values are mapped here https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-google-analytics/src/browser.js#L160
