### ISSUE TITLE
Doubleclick.net?  

### ISSUE THREAD

**Issue by dstroot** [DavidWells/analytics#18]
Why is this calling doubleclick.net?  I am only using the `googleAnalyticsPlugin` and the example plugin but I get pings to https://stats.g.doubleclick.net and they seem to be coming from the library.  

<img width="740" alt="Screen Shot 2019-08-24 at 7 15 09 PM" src="https://user-images.githubusercontent.com/1438457/63644687-9697a400-c6a3-11e9-9f88-7eebbe82e033.png">

**Comment by DavidWells** [comment]
Hey @dstroot good question

This appears to be the default behavior of `https://www.google-analytics.com/analytics.js`

It's loaded here: https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-ga/src/browser.js#L39

Then page view is called under the hood with normal GA calls here: https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-ga/src/browser.js#L63-L64
