### ISSUE TITLE
Logs incorrect url when canonical tag on page

### ISSUE THREAD

**Issue by ochrzan** [DavidWells/analytics#180]
The tracker will log the wrong url if there is a canonical tag in the header of the page. The tracker should not be changing the logged url because there is a canonical tag. This make it so that it is impossible to tell if non-canonical links are indexed by search engines or being used on the site.

**Comment by DavidWells** [comment]
Hello there!

can you share a live page or the html of what the pages with canonical tags looks like?

I need to test with something to debug any issues

**Comment by ochrzan** [comment]
Just make any html page with a link rel=“canonical” tag on it and have the url of the page different than the tag. The analytics.js will log the href of the canonical tag instead of the actual url.

**Comment by DavidWells** [comment]
The core module is grabbing the canonical URL here https://github.com/DavidWells/analytics/blob/master/packages/analytics-core/src/modules/page.js#L9-L17 and uses that in the page view call https://github.com/DavidWells/analytics/blob/master/packages/analytics-core/src/modules/page.js#L59

Can you run the following code on your site to see if it returns the canonical tag

```js
function canonicalUrl() {
  const tags = document.getElementsByTagName('link')
  for (var i = 0, tag; tag = tags[i]; i++) {
    if (tag.getAttribute('rel') === 'canonical') {
      return tag.getAttribute('href')
    }
  }
}
```

**Comment by ochrzan** [comment]
We stopped using the analytics package at this point and just wrote our own layer. Sorry I can’t help more, but thought I would put in a bug report for something I thought was incorrect behavior.

**Comment by DavidWells** [comment]
Okay sounds good.

P.s. You can override any of the default page values in the `.page()` call

```js
analytic.page({
  url: 'whatever-you-want-instead-of-canonical-link-found'
})
```
