### ISSUE TITLE
Integrating @analytics/google-analytics with Angular 

### ISSUE THREAD

**Issue by ANVESH96** [DavidWells/analytics#184]
I am integrating analytics with the angular project and unable to import the `@analytics/google-analytics` package. 

Code sample looks like this 

import { Injectable } from '@angular/core';
import Analytics from 'analytics';
import googleAnalytics from '@analytics/google-analytics'

```
@Injectable({
  providedIn: 'root',
})
export class AnalyticsService {
  private analytics: any;
  constructor() {
    this.analytics = Analytics({
      app: 'test-app',
      debug: true,
      plugins: [
        googleAnalytics({
          trackingId: 'G-********',
        }),
      ],
    });
  }
  trackPage() {
    this.analytics.page( );
    console.log('track');
  }
```
  
  The AnalyticsService is invoked in login page as soon as the user is loggedin. I am able to see the console.log printing 'track'
 without any errors but the data is not being transferred to google analytics at all (both real-time and normal looks empty).  
 
 `import googleAnalytics from @analytics/google-analytics` is throwing an warning looking for module with file extension `.d.ts` which is not available in package. Did any encounter the same issue ?

**Comment by DavidWells** [comment]
Hello there!

1. Verify that GA is loaded into the DOM

```
@Injectable({
  providedIn: 'root',
})
export class AnalyticsService {
  private analytics: any;
  constructor() {
    this.analytics = Analytics({
      app: 'test-app',
      debug: true,
      plugins: [
        googleAnalytics({
          trackingId: 'G-********',
        }),
      ],
    });
  }
  trackPage() {
    console.log('Does GA exist?', window.ga)
    this.analytics.page( );
    console.log('track');
  }
```

2. Open up the network tab and look for calls to collect

It should look something like:

```
https://www.google-analytics.com/j/collect?v=1&_v=j91&a=12322131&t=pageview&_s=1&dl=https%3A%2F%2Fwww.vendia.net%2F&dp=%2F&ul=en-us&de=UTF-8&dt=xyze&sd=24-bit&sr=1680x1050&vp=1665x484&je=0&_u=SACAAEABAAAAAC~&jid=1231&gjid=1841061430&cid=29266571.1598320881&tid=UA-122131312-1&_gid=12312312321&_r=1&_slc=1&z=1882056589
```

3. Install redux dev tools https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd/related?hl=en and verify the call was made

![image](https://user-images.githubusercontent.com/532272/125142223-15492f00-e0cc-11eb-9b90-35972df5c833.png)


Try these things to make sure GA is loaded into your app.

PS. GA is known to work differently if this is a desktop app that doesn't use the HTTP protocol

**Comment by ANVESH96** [comment]
@DavidWells  I am able to verify the network request through the chrome network tab and redux dev tools. Still couldn't see the data in the analytics.  


I am able to see the data if I enabled the analytics in index.html (gtag.js way.) 

This is how the redux action looks like. Is there is something I am missing? 
![C4EB4CB9-7A8B-480B-86E6-493DFF562652_1_201_a](https://user-images.githubusercontent.com/36524965/125321729-9d187e80-e302-11eb-8790-3df25e7fd646.jpeg)

**Comment by DavidWells** [comment]
Sounds like your GA account is possibly filtering out any data from localhost OR you might be using the wrong GA ID.

Note this plugin is for google analytics v3. So if you are using GA4 this also might be why data is not showing.

Double-check your GA tracking ID and try to Deploy to a live URL and test it from there

**Comment by ANVESH96** [comment]
I am using GA4 which is why the plugin is not working. Thanks for the help.  Is there a way to update the plugin to work with GA4 ?

**Comment by DavidWells** [comment]
There is an open PR for new version here https://github.com/DavidWells/analytics/pull/125

I haven't had the bandwidth to adopt ga4 yet
