### ISSUE TITLE
Support for segment cross domain tracking using setAnonymousId

### ISSUE THREAD

**Issue by Wazbat** [DavidWells/analytics#185]
Is there any way to override the segment anonymous ID when using @analytics/segment? If not, this would be a useful and appreciated feature

https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/identity/#override-the-anonymous-id-from-the-segment-snippet

**Comment by DavidWells** [comment]
Yeah you can listen to the `setItemEnd` event and make a call to segments `analytics.setAnonymousId('ABC-123-XYZ')` function.

Here is an example:

```js
import AnalyticsLib from 'analytics'
import segmentPlugin from '@analytics/segment'

const extendedSegment = {
  ...segmentPlugin({
    writeKey: '123-xyz'
  }),
  // Custom method to fire after analytics.setAnonymousId('new-id-xyz') is called
  setItemEnd: ({ payload }) => {
    if (payload.key === '__anon_id') {
      console.log('Set anon id to', payload.value)
      analytics.setAnonymousId(payload.value)
    }
  }
}

const Analytics = AnalyticsLib({
  app: 'awesome-app',
  plugins: [
    extendedSegment
  ]
})

Analytics.setAnonymousId('new-id-xyz')
```

The `setItemEnd` probably needs to get added into the plugin here https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-segment/src/browser.js#L162 . PRs welcome

**Comment by DavidWells** [comment]
Closing this out. Let me know if you have any other questions

**Comment by Wazbat** [comment]
Sorry for the delay. I'm a little confused as to what that analytics variable there is referring to. Did you mean window.analytics? I was looking through the segment plugin code and it appears that segment is still loaded onto the global window, correct?

And if so, wouldn't it be possible to set the ID manually by referencing that?
```
const analytics= AnalyticsLib({
  app: 'awesome-app',
  plugins: [
    segmentPlugin(config)
  ]
})
analytics.on('ready', () => {
   window.analytics.anonymousId('new-id-xyz')
})
```

Something like this?

**Comment by DavidWells** [comment]
@Wazbat yep

You can reference the segment global and use that
