### ISSUE TITLE
Persisting events between sessions while offline

### ISSUE THREAD

**Issue by Azim-Palmer** [DavidWells/analytics#186]
I'm building a html based app that's being used in Hospitals, which have terrible reception so it's likely they'll often be offline.

What happens often is the user will open the app in offline mode, interact with it and potentially close it before it has a chance to ever see the network, then later at home when they reopen the app ideally I'd like the analytics data captured during previous sessions but never uploaded to be loaded from storage and sent.

How/can I achieve this with this package? I can see there's Network events and if during the same session the user regains an internet connection it will push the events, but I can't see a way of asking it to persist between sessions etc

**Comment by DavidWells** [comment]
All events are automatically buffered in memory if connections drop out and will send data when the browser reconnnects (as long as the window hasn't been closed)

In the case where you want to persist events/payloads between sessions, there are a couple different ways to save events flowing through the system

For example, you can listen to all events via the `.on` listener and [navigator.onLine](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine)

```js
// https://getanalytics.io/api/#analyticson
analytics.on('track', ({ payload }) => {
  if (!navigator.onLine) {
     console.log('offline');
     console.log('save events for replay later')
  }
})

analytics.on('page', ({ payload }) => {
  if (!navigator.onLine) {
     console.log('offline');
     console.log('save events for replay later')
  }
})
```

Or you can do something similar in a provider plugin https://getanalytics.io/plugins/writing-plugins/#1-provider-plugins
