### ISSUE TITLE
Matomo plugin?

### ISSUE THREAD

**Issue by mhf-ir** [DavidWells/analytics#187]
Any plan to support Matomo? https://matomo.org/

**Comment by DavidWells** [comment]
Hello there!

I won't have time to build this integration myself but you are more than welcome to 😃

See https://getanalytics.io/plugins/writing-plugins/#1-provider-plugins for writing a plugin.

Essentially, you will want to map the `page`, `track` methods to the Matomo JS calls

```js
export default function pluginExample(userConfig) {
  return {
    /* All plugins require a name */
    name: 'matomo-plugin',
    /* Everything else below this is optional depending on your plugin requirements */
    config: {
      whatEver: userConfig.whatEver,
      elseYouNeed: userConfig.elseYouNeed
    },
    initialize: ({ config }) => {
      // load matomo script to page
    },
    page: ({ payload }) => {
      // call matomo specific page tracking
    },
    track: ({ payload }) => {
      // call matomo event tracking
    },
    loaded: () => {
      // return boolean so analytics knows when it can send data to third party
      return !!window.myPluginLoaded
    }
  }
}
```

**Comment by DavidWells** [comment]
Moving over to this thread https://github.com/DavidWells/analytics/issues/153

Let me know if you have any questions on creating plugins

**Comment by daun** [comment]
A third-party Matomo plugin is available at [analytics-plugin-matomo](https://github.com/daun/analytics-plugin-matomo).
