### ISSUE TITLE
AWS Pinpoint Plugin for Analytics not working

### ISSUE THREAD

**Issue by krish07-github** [DavidWells/analytics#189]
Hi,
We are trying to follow the directives as part of the below link in order to use AWS Pinpoint Analytics for one of our engagement.

https://www.npmjs.com/package/@analytics/aws-pinpoint

But once we copy the HTML source from the link but was getting an error once we load the page. Attached is the screenshot. We are facing some issues with a component called **smartQueue** and was not able to resolve the same. We did try a lot of things, but nothing worked and somehow, it's not able to identify the smartQueue function altogether.

![smartQueueError](https://user-images.githubusercontent.com/76196364/126128707-cee04ab3-08ec-4416-97d3-a144e0c4177d.PNG)

Below is the HTML that we used for reference. It would be really helpful if we get a resolution for the same.

'''<!DOCTYPE html>
<html>
  <head>
    <title>Using @analytics/aws-pinpoint in HTML</title>
    <script src="https://unpkg.com/analytics/dist/analytics.min.js"></script>
    <script src="https://unpkg.com/@analytics/aws-pinpoint/dist/@analytics/aws-pinpoint.min.js"></script>
    <script type="text/javascript">
      /* Initialize analytics */
      var Analytics = _analytics.init({
        app: 'my-app-name',
        plugins: [
          analyticsAWSPinpoint.default({
            pinpointAppId: '<changed to our project id>',
            getCredentials: () => Auth.currentCredentials()
          })
        ]
      })

      /* Track a page view */
      analytics.page()

      /* Track a custom event */
      analytics.track('cartCheckout', {
        item: 'pink socks',
        price: 20
      })

      /* Identify a visitor */
      analytics.identify('user-id-xyz', {
        firstName: 'bill',
        lastName: 'murray'
      })
    </script>
  </head>
  <body>
    ....
  </body>
</html>'''

**Comment by DavidWells** [comment]
The queuing util is included in the package https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-aws-pinpoint/package.json#L51

But I see what you are saying. Looks like the standalone build is externalizing the dep in unpkg build

![image](https://user-images.githubusercontent.com/532272/126199863-3613dd01-ff84-48cb-80d7-326ba083317c.png)

I will need to take a look at why this is being excluded. In the meantime you can you use the `import` syntax and it should work 

```
import Analytics from 'analytics'
import awsPinpointPlugin from '@analytics/aws-pinpoint'
``` 

Thanks for reporting this

**Comment by DavidWells** [comment]
Updated the unpkg build with `@analytics/aws-pinpoint@0.6.9` 

The latest is inlining those missing deps https://unpkg.com/@analytics/aws-pinpoint@0.6.9/dist/@analytics/aws-pinpoint.js
