### ISSUE TITLE
customDomain in Simple Analytics script should be string, not boolean

### ISSUE THREAD

**Issue by adriaandotcom** [DavidWells/analytics#190]
In this commit an error is added: https://github.com/DavidWells/analytics/commit/4572cf38c32eacd0bacd50d0d0119216f42100b6

The custom domain in Simple Analytics should be a string, not a boolean.

In the `browser.js` file you can see it's used as a string:

https://github.com/DavidWells/analytics/blob/73afae2f710821b7cec2c41d949aad4633f38afa/packages/analytics-plugin-simple-analytics/src/browser.js#L22-L23

Same goes for the comment above the code:

https://github.com/DavidWells/analytics/blob/73afae2f710821b7cec2c41d949aad4633f38afa/packages/analytics-plugin-simple-analytics/src/browser.js#L8

I'm not sure where or how to update the docs. Because in these files I see a lot of auto generated stuff. Therefor I'm not sure what source files to change for this documentation and code error.

**Comment by DavidWells** [comment]
Good catch! 

I've updated the docs and the package `@analytics/simple-analytics@0.3.1`

**Comment by adriaandotcom** [comment]
Thank you for handling it this quickly!
