### ISSUE TITLE
Auth.currentCredentials() error on using unpkg cdn with HTML + accessKeyId and secretAccessKey mandatory for instantiating class AWSClient within aws-pinpoint.js

### ISSUE THREAD

**Issue by sayantan1997** [DavidWells/analytics#191]
When using the cdn along side HTML , we get the error "Auth" not defined for getCredentials() method while executing init method. If we change it to a cognito login enabled page and pass the credentials to getCredentials() , it doesn't work either-reason being it tries to instantiate class AwsClient within aws-pinpoint.js which needs the access key id and secret access key to be present. 

Question : Is it assumed that who ever visits my page has a profile created in AWS , if not then for any individual who is redirected to my page via a URL in some email or SMS communication using SES or SNS , how are we supposed to have their access key id or secret key available for tracking their behavior .

**Comment by DavidWells** [comment]
Pinpoint requires a valid identity to make calls to the service.

To do this you will need to use the AWS SDK, AWS Amplify, [tiny-cognito](https://www.npmjs.com/package/tiny-cognito) etc to vend AWS creds for that visitors to be allowed to call pinpoint

`getCredentials` must return an object that looks like:

```js
{
    accessKeyId: 'xyz',
    secretAccessKey: 'xyz',
    sessionToken: 'xyz'
}
```

Here is an example using `tiny-cognito`

```js
import Analytics from 'analytics'
import cognitoAuth from 'tiny-cognito'
import awsPinpointPlugin from '@analytics/aws-pinpoint'

// Identity pool ID that allows for unauthenticated access. 
const poolId = 'us-east-1:11111111-22222-222222-44444'
const region = 'us-east-1'

function getCredentials() {
  return cognitoAuth({
    COGNITO_REGION: region,
    IDENTITY_POOL_ID: poolId
  })
}

const analytics = Analytics({
  app: 'awesome-app',
  plugins: [
    awsPinpointPlugin({
      pinpointAppId: '123456789',
      getCredentials: getCredentials
    })
  ]
})
```

This is above example is attached to an identity pool that allows for unauthenticated access. 

Using Amplify it looks like:

```js
import Analytics from 'analytics'
import AmplifyAuth from '@aws-amplify/auth'
import awsPinpointPlugin from '@analytics/aws-pinpoint'

const analytics = Analytics({
  app: 'awesome-app',
  plugins: [
    awsPinpointPlugin({
      pinpointAppId: '123456789',
      // Get credentials from amplify
      getCredentials: async () => {
        const creds = await AmplifyAuth.currentCredentials()
        return creds
      },
    })
  ]
})
```

**Comment by DavidWells** [comment]
I've added this to the docs here https://getanalytics.io/plugins/aws-pinpoint/#authenticating

Let me know if you have any other questions
