### ISSUE TITLE
analytics.identify fn does nothing

### ISSUE THREAD

**Issue by binarykitchen** [DavidWells/analytics#193]
For example I have this

```js
      analytics.identify(this.profile.user.userLogin.userName, {
        firstName: this.profile.user.firstName,
        lastName: this.profile.user.lastName,
        displayName: this.profile.user.displayName
      })
```

after initialising and authentication. But on Google Analytics side under User Explorer, I do not see them anywere at all. Only seeing random Client IDs not associated with anything from the above, e.g. username or firstname or so.

Possibly a bug?

**Comment by DavidWells** [comment]
Identity calls this function https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-google-analytics/src/browser.js#L376-L384 that sets the userID to the ga context.

On the next page/tracking call it should include this information. Inside GA3 you must have userID enabled https://support.google.com/analytics/answer/3123666?hl=en&ref_topic=3123660#zippy=%2Cin-this-article

try this:

```js
analytics.identify(this.profile.user.userLogin.userName, {
  firstName: this.profile.user.firstName,
   lastName: this.profile.user.lastName,
   displayName: this.profile.user.displayName
}, () => {
  // trigger dummy event to immediatly send user id
  analytics.track('userIdentified')
})
```

**Comment by binarykitchen** [comment]
Awesome, this helps. Thanks man!
