### ISSUE TITLE
Plugin Request: Data Dog

### ISSUE THREAD

**Issue by vusimngomezulu** [DavidWells/analytics#20]
Hello, 

Will it possible to have a Datadog(https://www.datadoghq.com/) integration?

Regards

**Comment by DavidWells** [comment]
Hey @vusimngomezulu yeah for sure.

Analytics can send data anywhere 😃

Does datadog have an existing browser or node.js client to checkout?

**Comment by DavidWells** [comment]
Hello there.

Is this the javascript client you would like to see support for https://docs.datadoghq.com/logs/log_collection/javascript/?tab=us?

**Comment by DavidWells** [comment]
A consolidated issue has been created at https://github.com/DavidWells/analytics/issues/153 for plugin requests.

Feel free to comment/reopen this thread if you have begun active development on this plugin.
