### ISSUE TITLE
Plugin Request: Sentry

### ISSUE THREAD

**Issue by hazem-osama** [DavidWells/analytics#200]
Would be great to add a plugin for [sentry.io](https://sentry.io/)

Would be happy to create a pull request with the plugin XD

**Comment by DavidWells** [comment]
Hey, @hazem-osama sounds good to me!

Here are the docs for creating plugins https://getanalytics.io/plugins/writing-plugins/#1-provider-plugins

Let me know if you have any questions

**Comment by DavidWells** [comment]
Closing this thread. It's tracked in here https://github.com/DavidWells/analytics/issues/153
