### ISSUE TITLE
Node.js example not working

### ISSUE THREAD

**Issue by hodlerhacks** [DavidWells/analytics#201]
Hi, this seems like a great library and it is exactly what I need for my project. However, I can't get it to work in my node.js application. Even the basic example from the documentation is not working for me:

```
const analyticsLib = require('analytics').default
const googleAnalytics = require('@analytics/google-analytics').default

const analytics = analyticsLib({
  app: 'my-app-name',
  plugins: [
    googleAnalytics({
      trackingId: '123-xyz'
    })
  ]
})

/* Track a page view */
analytics.page()
```

Using analytics.page() throws an error (Error: Missing path, href or title in page call for GA). If I do the following:

```
analytics.page({
    title: 'test',
    href: 'http://localhost:3000',
    path: '/'
})
```
the code runs, but I don't see any page event in Google Analytics. And of course, I replaced the trackingId from the sample code with my own.

Any hints that can help me to get page views tracked?

Thanks!

**Comment by markojak** [comment]
A few tings:

1. Enable debug: true just under "app" - If you are seeing that https://getanalytics.io/debugging/ is giving you the page() hit then the analytics module is working and you're trying to do something non-standard

2. Have you installed the relevant packages? 
You'll need
```
import Analytics from 'analytics'
import googleAnalytics from '@analytics/google-analytics'
```

3. You don't need to specify any custom attributes for the page() call. What it seems like you're doing is attempting to define custom dimensions without first defining them in GA?
Read this:
https://developers.google.com/analytics/devguides/collection/analyticsjs/custom-dims-mets

**Comment by DavidWells** [comment]
There could be a couple of different problems. 

1. 'universal-analytics' lib batches calls in node.js https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-google-analytics/src/node.js#L35 and your request doesn't finish
2. This is for google analytics v3 not v4.
3. Double check the GA ID to make sure the data sends through.

To debug the deeper network call alter the underlying `node_modules/universal-analytics` and log out to make sure the calls resolve before your code exits.

I've observed this when using this package in AWS lambda and needed a setTimeout to wait for next event loop to return

**Comment by hodlerhacks** [comment]
Thanks both for your help! I'm using GA4, so that's causing the issue. Are you planning to support GA4 in the (near) future?

**Comment by DavidWells** [comment]
> Are you planning to support GA4 in the (near) future?

We aren't using GA4 yet and I won't have time to implement the plugin for this. That said, there is an open PR https://github.com/DavidWells/analytics/pull/125 and thread on the issue https://github.com/DavidWells/analytics/issues/107

Additionality how to building a plugin is documented here: https://getanalytics.io/plugins/writing-plugins/#1-provider-plugins.

Let me know if you have any questions

**Comment by hodlerhacks** [comment]
Thanks for the additional information. I'll keep an eye on those threads to see how things are evolving.

Back to my original comment, I created a GA3 property and tested with the node.js sample code, and it's working, but only when adding the additional attributes to the page() call, i.e.:

```
analytics.page({
    title: 'test',
    href: 'http://localhost:3000',
    path: '/'
})

```
When using just page() I keep getting 'Error: Missing path, href or title in page call for GA'. Just FYI.

**Comment by DavidWells** [comment]
> When using just page() I keep getting 'Error: Missing path, href or title in page call for GA'. Just FYI.

Yep those are required from the underlying lib https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-google-analytics/src/node.js#L59
