### ISSUE TITLE
Amplitude Plugin: Allow  session_id to be set

### ISSUE THREAD

**Issue by freitaga** [DavidWells/analytics#203]
I'm attempting to attach a session_id for the plugin to passively send with each track event. In the amplitude plugin, there's a prototype method for `setSessionId` that looks useful for this situation.

This is the only reference I can find about session_id with segment/amplitude:

https://segment.com/docs/connections/destinations/catalog/amplitude/

The `sessionId` section looks to be outdated as the link is to the depracted API. There is also no integration specific option to set this session_id manually.

**Comment by DavidWells** [comment]
How is `session_id` set by the amplitude SDK?

We would need to add to probably somewhere in the initialize call https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-amplitude/src/browser.js#L37-L119 via a plugin option.

**Comment by freitaga** [comment]
https://developers.amplitude.com/docs/javascript

The documentation doesn't have an exact example on how to set it. Looks like it's initialized automatically as it only provides the method on how to retrieve it.

`var sessionId = amplitude.getInstance()._sessionId;`

The documentation does reference a `setSessionId` here as well. Assuming it works in the same way as the setUserId function:

`amplitude.getInstance().setUserId('USER_ID');`

Only session id would be a  timestamp.

One possible solution would be to set the sessionId on an identify such as:

`client.setSessionId(Date.now())`

As the session id is the timestamp of when the user is identified.

**Comment by myleslinder** [comment]
You can call `amplitude.getInstance().setSessionId(someNumber)` [after the script has loaded, but before calling `init`](https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-amplitude/src/browser.js#L117) but there isn't a way to do that right now. The amplitude SDK doesn't offer any specific options for initializing with a particular session_id, it's either what's in the cookie, or the current timestamp. 

However, if you provide `true` for the `deferInitialization` option any users without a cookie wont have a session_id set until you call `amplitude.getInstance().enableTracking()`. Which means once you have your session_id call `amplitude.getInstance().setSessionId(someNumber)` and then `amplitude.getInstance().enableTracking()` afterward. This ensures that if you're capturing any referrer values that they get attached to the proper session_id. 

If you'll have the session_id available right away on page load you could do this by hooking into the `ready:amplitude` event to set your session_id.  

```js
const amplitudeSessionIdPlugin = {
  name: 'custom-amplitude-session-id',
  'ready:amplitude': ({ payload }) => {
	const amplitudeInstance = window.amplitude.getInstance();
	amplitudeInstance.setSessionId(yourSessionId)
	amplitudeInstance.enableTracking() 
        return payload;
  },
 // or the 'identify' or 'identify:amplitude' events
'identify:amplitude': // same as above
}

```
When `amplitude.getInstance().setSessionId(someNumber)` is called it overwrites the current in-memory session_id and updates the cookie, meaning that session_id will be used for events tracked until the next session timeout. 

However, even if a cookie is present to get the session_id from, the amplitude SDK still compares it to the previous event time to determine if it should set a new session_id based on the sessionTimeout (defaults to 30 mins or can be overwritten in initial options).

**Comment by DavidWells** [comment]
You can now set session ids via `@analytics/amplitude@0.1.0`. Thanks @myleslinder for pointing out how this works

## Setting Custom Session Ids

You can set a session id like so

```js
import Analytics from 'analytics'
import amplitudePlugin from '@analytics/amplitude'

const analytics = Analytics({
  app: 'awesome-app',
  plugins: [
    amplitudePlugin({
      apiKey: 'token',
    })
  ]
})

// Run custom method https://getanalytics.io/plugins/writing-plugins/#adding-custom-methods
analytics.plugins['amplitude'].setSessionId('your-id')
```

Or via the `initialSessionId` config value

```js
import Analytics from 'analytics'
import amplitudePlugin from '@analytics/amplitude'

const analytics = Analytics({
  app: 'awesome-app',
  plugins: [
    amplitudePlugin({
      apiKey: 'token',
      initialSessionId: 'xyz-123'
    })
  ]
})
```
