### ISSUE TITLE
Issues with Google Analytics v4

### ISSUE THREAD

**Issue by thom801** [DavidWells/analytics#206]
The new version of Google Analytics (v4) seems to not be compatible with the `@analytics/google-analytics` plugin. Is that something that y'all are aware of or am I just doing something wrong. I noticed that all the docs refer to Universal Analytics (the older version of GA) and seem to use `GA-123456` format tracking Ids, where the newer versions are `G-123456` format.

The odd thing is that I see the events firing and it pulling down the single pixel gif with a 200 response, however none of the events seem to be registering in my analytics account. No page views or events are working at all with this lib for me. However if I slap in the script in my HTML with the same tracking Id, it starts working at least for page views.

I have tried messing around with the cookie domain etc since I am testing on localhost. But again, the domain doesn't seem to be an issue when I use the default GA script so I am not sure what the issue is. Would love some feedback or ideas if y'all have any.

**Comment by DavidWells** [comment]
The `google-analytics` plugin is for v3 as v4 is still in beta last I checked.

That said, there is an open PR on how a GA4 plugin would look https://github.com/DavidWells/analytics/pull/125 I'd recommend checking that out and using a custom plugin.

Thread here https://github.com/DavidWells/analytics/issues/107

**Comment by thom801** [comment]
@DavidWells Thank you sir, I will take a look. Hopefully the v4 keywords in this issue will help point others in the right direction as well.

**Comment by thom801** [comment]
@DavidWells how do you recommend I go about using the PR #125 version as a plugin?

**Comment by kpapadatos** [comment]
@DavidWells All new GA accounts are GA4 now and the addon is basically useless as it fails to track pages/events/users with "G-" tracking ids.

**Comment by tom-wagner** [comment]
+1 on everything said above, very frustrating

**Comment by LarsBuur** [comment]
I like everything about this package and I am missing the GA4 plugin as many others.
Can we chip in collectively to have someone build this properly?

**Comment by totalhack** [comment]
Just wanted to note that universal analytics is now [scheduled for sunset](https://searchengineland.com/google-deprecate-universal-analytics-on-july-1-2023-382648) on July 1 2023. I believe GA4 properties are completely separate from universal analytics properties and don't share data/history, so folks likely won't want to wait until the last minute to transition.

**Comment by winston0410** [comment]
Joining this discussion lately. @totalhack If I am trying to set up GA now, which add on should I use? Should I use the gtag plugin?

**Comment by DavidWells** [comment]
At long last, GA4 is released via version 1+ of the https://www.npmjs.com/package/@analytics/google-analytics package.

You can install and use via this command

```
npm install @analytics/google-analytics@latest
```

**Note this is a breaking change** and you will need to setup a google analytics 4 property & stream and use its measurement ID.

If you want to continue using older google analytics 3, which is honestly a completely different product, you will want to switch to the https://www.npmjs.com/package/@analytics/google-analytics-v3 package.

**Using both GA3 and GA4*

It is possible to use both GA3 and GA4 together like so:

```js
import Analytics from 'analytics'
import googleAnalyticsPlugin from '@analytics/google-analytics'
import googleAnalyticsV3Plugin from '@analytics/google-analytics-v3'

/* Initialize analytics instance */
const analytics = Analytics({
  app: 'my-app',
  plugins: [
    /* Load Google Analytics v4 */
    googleAnalyticsPlugin({
      measurementIds: ['G-abc123'],
    }),
    /* Load Google Analytics v3 */
    googleAnalyticsPlugin({
      trackingId: 'UA-11111111-2',
    }),
  ],
})

analytics.page()
```

Just remember GA3 will be deprecated starting in July of 2023
