### ISSUE TITLE
Identify Calls Not Funneling to MixPanel Via Segment

### ISSUE THREAD

**Issue by stevenolay** [DavidWells/analytics#209]
Currently my team uses segment as a CDP.

One of our destinations is MixPanel. 

I tried using the SegmentPlugin for the analytics package to do an Identify call. The call shows up in the Segment logs in this format: 

```
{
  "context": {
    "library": {
      "name": "analytics-node",
      "version": "3.5.0"
    }
  },
  "integrations": {},
  "messageId": "REDACTED",
  "originalTimestamp": "2021-09-09T20:49:20.373Z",
  "receivedAt": "2021-09-09T20:49:20.876Z",
  "sentAt": "2021-09-09T20:49:20.374Z",
  "timestamp": "2021-09-09T20:49:20.875Z",
  "traits": {},
  "type": "identify",
  "userId": "user-id-xyz",
  "writeKey": "REDACTED"
}
```

When using the Segment Analytics.js package. Identify calls show up in the segment logs in the following format:

```
{
  "anonymousId": "99703ab7-b1e6-4a9a-98b4-e9c3b4cb19c6",
  "context": {
    "ip": "REDACTED",
    "library": {
      "name": "analytics.js",
      "version": "next-1.30.0"
    },
    "locale": "REDACTED",
    "page": {
      "path": "REDACTED",
      "referrer": "REDACTED",
      "search": "REDACTED",
      "title": "REDACTED",
      "url": "REDACTED"
    },
    "userAgent": "REDACTED"
  },
  "integrations": {},
  "messageId": "REDACTED",
  "originalTimestamp": "2021-09-09T21:13:59.511Z",
  "receivedAt": "2021-09-09T21:14:00.775Z",
  "sentAt": "2021-09-09T21:13:59.511Z",
  "timestamp": "2021-09-09T21:14:00.775Z",
  "traits": {
  },
  "type": "identify",
  "userId": "REDACTED"
}
```

The only difference in top level keys in the Object, is that the analytics package leaves out the anonymousId in the call. MixPanel appears to require the anonymous id to be defined in the identify call or else it rejects it. I was able to test this by altering the payload in the segment log and adding in an anonymousId field. And the event was successfully received. Any time I removed the anonymousId field, the event was dropped/ignored by MixPanel. 

I tried using the event listeners to intercept the track calls using the `identifyStart` event, and much to my surprise the anonymousId was there in the payload. But somewhere between that `identifyStart` event and the payload being pushed to segment the anonymousId is removed. Causing MixPanel to ignore the identify call when it's received on its end. 

Payload from `identifyStart` event:

```
 {
 type: 'identifyStart',
 userId: 'user-id-xyz',
 traits: {},
 options: {},
 anonymousId: 'e7e1cefc-f661-4d09-8c2c-bad53625abd3',
 meta: {
  rid: 'REDACTED',
  ts: REDACTED,
  hasCallback: true
 }
}
```

Does anyone know why the anonymousId is being left out of the calls to segment, causing MixPanel to ignore the events?

**Comment by DavidWells** [comment]
Hmmm good question.

The identify call with segment plugin is made here https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-segment/src/browser.js#L147 the anonymous ID from segment's analytics.js should already be set from the `init` https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-segment/src/browser.js#L114 

 `anonymousId` from `identifyStart` is not passed to the segment analytics.js `analytics.identify` call https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-segment/src/browser.js#L147 I don't think it needs to be as long as it's set as localstorage/cookie value that segment uses

**Comment by stevenolay** [comment]
I was calling the library from NodeJs. And in that context there isn't a cookie/localstorage available.

I'll try calling it from the client and see if that works, but I thought this package should work the same on the backend and the front end?

**Comment by stevenolay** [comment]
Okay. So your response was a big help. 

Turns out that the Segment Analytics.js Node package also does not include the anonymousId and MixPanel also ignores those identify calls unless they are also tied to a track call. This must be intentional behavior. 

Everything worked as it should from the client side. The anonymousId is being included. And the identify calls are showing up in MixPanel.
