### ISSUE TITLE
NextJS, @analytics/mixpanel "mixpanel not available in node.js yet"

### ISSUE THREAD

**Issue by amie-wilt** [DavidWells/analytics#220]
Hello,

`"@analytics/mixpanel": "^0.4.0"`
`"analytics": "^0.7.15"`

I'm using these packages with NextJS and am getting the following in ` next dev` and `next build`:
<img width="759" alt="Screen Shot 2021-10-02 at 11 03 26 AM" src="https://user-images.githubusercontent.com/8226176/135722267-bc0514d1-82d8-43e5-9052-e97bc91e2084.png">

Any idea on why I'm getting this or how to resolve it?

Thank you

**Comment by DavidWells** [comment]
Hello there!

The log here won't hurt anything but if you'd like to disable it use conditional loading for client-side only.

```js
import Analytics from 'analytics'
import googleAnalyticsPlugin from '@analytics/google-analytics'

const IS_BROWSER = typeof window !== 'undefined'

const plugins = [
  googleAnalyticsPlugin({
    trackingId: 'xyz'
  }),
  //... plugins
]

// Initialize analytics
const analytics = Analytics({
  debug: true,
  app: 'vendia-site',
  plugins: [
    ...(IS_BROWSER) ? plugins : [],
  ]
})
```

**Comment by amie-wilt** [comment]
Ah okay, thank you!

**Comment by gabimoncha** [comment]
@DavidWells won't this disable the mixpanel tracking?

**Comment by unnimona** [comment]
same issue 
any fix?
