### ISSUE TITLE
TypeError: googleAnalytics is not a function

### ISSUE THREAD

**Issue by omkar-tenkale** [DavidWells/analytics#221]
i'm using it in node like this:

```
const Analytics = require("analytics");
const googleAnalytics = require("@analytics/google-analytics");
const instance = Analytics({
	app: 'my-app-name',
	version: 100,
	plugins: [
		googleAnalytics({
			trackingId: process.env.GA4_MEASUREMENT_ID,
		})
	]
})
module.exports = {
	analytics: instance
};
```

but trying to run the express server throws error

> TypeError: googleAnalytics is not a function

am I not importing properly?

**Comment by omkar-tenkale** [comment]
"@analytics/google-analytics": "^0.5.3",
    "analytics": "^0.7.15",

**Comment by DavidWells** [comment]
You need to use the `.default` key in es5. See https://getanalytics.io/plugins/google-analytics/#server-side-usage

```js
const analyticsLib = require('analytics').default
const googleAnalytics = require('@analytics/google-analytics').default

const analytics = analyticsLib({
  app: 'my-app-name',
  plugins: [
    googleAnalytics({
      trackingId: '123-xyz'
    })
  ]
})

/* Track a page view */
analytics.page()

/* Track a custom event */
analytics.track('cartCheckout', {
  item: 'pink socks',
  price: 20
})

/* Identify a visitor */
analytics.identify('user-id-xyz', {
  firstName: 'bill',
  lastName: 'murray'
})
```

**Comment by Micode360** [comment]
They need to state that clearly in their documentation. It should be among the required things to add. I saw this ``const googleAnalytics = require('@analytics/google-analytics') ;``` first at the npm documentation and used it even at the git hub documentation.
