### ISSUE TITLE
storage.getItem() to fetch cookie value does not work

### ISSUE THREAD

**Issue by fraser-m-hurley-LTK** [DavidWells/analytics#223]
Hi, I noticed recently that the storage support methods for cookies don't appear to work. 

I've tested with both `setItem()` and `getItem()` with 'cookie' provided as the storage location to search/set and neither work (tested in chrome and firefox). I was looking to use these whilst accessing the analytics instance in my plugin. e.g `instance.storage.getItem('cookieName','cookie')`

**Comment by DavidWells** [comment]
Thanks for the report!

Fix released in `analytics@0.7.16`
