### ISSUE TITLE
userId is set to key email in Intercom plugin for node

### ISSUE THREAD

**Issue by emilkaiser** [DavidWells/analytics#224]
https://github.com/DavidWells/analytics/blob/3f0e5884ba0e491e999bc00bf0ebc9f94e6a94a9/packages/analytics-plugin-intercom/src/node.js#L65

Either key should be changed to id (i think) and/or support create with email.

**Comment by DavidWells** [comment]
Fixed via `@analytics/intercom@1.0.2`

It will try the `userId` if its an email, else it will look for `{ email: 'xyz@xyz.com'}` on traits

```js
analytics.identify('userid-123', {
  email: 'bob@bob.com',
})
```
