### ISSUE TITLE
Extensions like uBlock are preventing the script from loading

### ISSUE THREAD

**Issue by stanyq4** [DavidWells/analytics#226]
Good day, 

We noticed that content-filtering extensions like uBlock are preventing the downloading of the analytics library. 

<img width="1674" alt="Screen Shot 2021-10-22 at 8 26 33 AM" src="https://user-images.githubusercontent.com/23194864/138461554-db5f49c4-ec3f-4359-97b2-66c6a717fa96.png">

We are using @analytics/amplitude and I was hoping to utilize `customScriptSrc` to proxy the library through our domain, but in your code, it is doing a checksum verification, so I might need to fork it to remove that check, but before I do that...

Have anyone found a workaround to this?

**Comment by DavidWells** [comment]
Good find.

The check will be skipped if no `customScriptSrc` or `integritySha` provided

This has been fixed and released via `@analytics/amplitude@0.0.4`

**Comment by stanyq4** [comment]
@DavidWells Have you had a chance to test your fix? 

I just tried passing a public S3 URL and integritySha, but getting: 

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'init')`. 

Was quickly debugging locally, but the execution doesn't even go into: 

```
      // Initialize amplitude js
      (function(e, t) {
```

Based on this line: 

`const integrity = integritySha || 'sha384-u0hlTAJ1tNefeBKwiBNwB4CkHZ1ck4ajx/pKmwWtc+IufKJiCQZ+WjJIi+7C6Ntm'`

integritySha always has to be provided, can we disable it? so if it's not provided - we just don't perform the integrity check.

**Comment by DavidWells** [comment]
Looks like it might be `iife` semicolon issue.

I just released `@analytics/amplitude@0.1.1`, give that a try. It should fix that issue

**Comment by DavidWells** [comment]
Updated the integrity check via `@analytics/amplitude@0.1.2`

```js
let integrity
if (integritySha) {
   integrity = integritySha
} else if (!customScriptSrc) {
   // use default
   integrity = 'sha384-u0hlTAJ1tNefeBKwiBNwB4CkHZ1ck4ajx/pKmwWtc+IufKJiCQZ+WjJIi+7C6Ntm'
}
```

**Comment by stanyq4** [comment]
Thank you @DavidWells, this fix worked.
