### ISSUE TITLE
How to contribute third-party plugins

### ISSUE THREAD

**Issue by deevus** [DavidWells/analytics#234]
I have developed and have been using the following plugins for a few months now:

1. https://github.com/deevus/analytics-plugin-activecampaign
2. https://github.com/deevus/analytics-plugin-profitwell
3. https://github.com/deevus/analytics-plugin-tapfiliate

What is the process for getting them added to the README, since it looks like it is automatically generated?

**Comment by OllyHodgson** [comment]
According to the [README](https://github.com/DavidWells/analytics#community-plugins), you'd open a PR with your changes in https://github.com/DavidWells/analytics/blob/master/external-plugins.json 🙂

**Comment by DavidWells** [comment]
Hey @deevus 

Thanks so much for these plugin contributions! You rock ❤️

I've added them to the external plugins file and they are now included in the docs https://github.com/DavidWells/analytics/commit/97f95d91b73ef2a1722a3cdb6765b5fa9357feae

**Comment by deevus** [comment]
Thanks @DavidWells 

I meant to come back to this and make the PR myself but got busy.
