### ISSUE TITLE
Plugin for self hosted data

### ISSUE THREAD

**Issue by micahwalter** [DavidWells/analytics#237]
I was wondering if it is possible to use this library to ship analytics data to a self-hosted solution. For example if I wanted to store all my tracking data on S3 or in a DynamoDB table .. any thoughts on how to do this?

cheers,
Micah

**Comment by DavidWells** [comment]
Hey @micahwalter 

Yeah, you can send the data wherever you wish. Check out https://blog.mikecoughlin.com/own-your-event-tracking/ and the creating your own plugin docs https://getanalytics.io/plugins/writing-plugins/#1-provider-plugins

**Comment by micahwalter** [comment]
Ugh - that blog URL is no longer working. It was there a few days ago!
