### ISSUE TITLE
Tracking Mixpanel "Super Properties"

### ISSUE THREAD

**Issue by TmanTman** [DavidWells/analytics#238]
Mixpanel supports "[Super Properties](https://help.mixpanel.com/hc/en-us/articles/360001355266-Event-Properties)", very similar to how Google Analytics tracks "Custom dimensions".

What would be the easiest way to track super properties through this library? I think either this library, or the Mixpanel plugin, needs to be extended? Either: 
1. To work in the same same as Google Analytics custom dimensions currently works with this library, or 
2. Perhaps the analytics library can expose a ".trackProperties" function? I'm not sure how common these custom dimensions/super properties are to other plugins.

Otherwise, if this is too "custom" to Mixpanel - do we have access to the underlying Mixpanel library to set this?

**Comment by DavidWells** [comment]
I'm not familiar with this in mixpanel, but if its like GA custom props you might want to map them in the `initalize` setup here https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-mixpanel/src/browser.js#L122 like how the GA plugin does it here https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-google-analytics/src/browser.js#L130-L133
