### ISSUE TITLE
Simple analytics documentation oversight

### ISSUE THREAD

**Issue by Jojoker33** [DavidWells/analytics#240]
Hi, 

In your https://github.com/DavidWells/analytics/blob/master/site/main/source/plugins/simple-analytics.md, there is a minor oversight : 
**_import exports from '@analytics/simple-analytics'_** should probably be replaced by **_import simpleAnalyticsPlugin from '@analytics/simple-analytics'_**

**Comment by DavidWells** [comment]
Thanks for report!

Updated
