### ISSUE TITLE
Custom Event Tracking

### ISSUE THREAD

**Issue by prashant-sirohi** [DavidWells/analytics#241]
Hi @DavidWells!
First of all thanks a lot for helping out the community with a great plugin!

#### Versions:
@analytics/google-analytics: 0.5.2
analytics: 0.7.18

#### Issue Description
I am using this to track custom events on my web app, i have added a piece of code to track a custom event as per the documentation. I can see in my console as well as in my network that it does send the data to GA and it gets registered as well. But i noticed something weird when i was trying to find a way to see all the payload data that i send with that event.

![image](https://user-images.githubusercontent.com/13165251/144854477-f4d69008-9034-47d9-a067-5025c1b3a898.png)
As you can see in the above image, it does send the event but it does not send the payload that i sent along with the event type. It does show me the payload value in redux dev-tools but when it actually makes a call to GA apis it does not send that payload

Now i am not sure if this even sends my payload at all. Please let me know if i am missing something or testing it wrong, in that case could you suggest how can i make sure that all the data that i am sending in event payload is there with each track event call. In my GA dashboard as well, i only see event type and no data that was the part of payload

**Comment by DavidWells** [comment]
Are you using GA3 or GA4 (latest google analytics)

The plugin is for version 3 right now.

**Comment by prashant-sirohi** [comment]
> Are you using GA3 or GA4 (latest google analytics)
> 
> The plugin is for version 3 right now.

I am using for GA3, not using GA4 since the plugin doesn't support that yet

**Comment by DavidWells** [comment]
Google analytics v3 only sends along these fields https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-google-analytics/src/browser.js#L263-L274

Everything else has to be mapped to a custom dimension https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-google-analytics/src/browser.js#L11

One day google analytics v4 plugin will be ready to address these limitations 😅

**Comment by prashant-sirohi** [comment]
Is that v4 plugin in progress? Anywhere i can tack that progress maybe?
