### ISSUE TITLE
Question: Plans to make storage APIs more consistent?

### ISSUE THREAD

**Issue by totalhack** [DavidWells/analytics#242]
The get/set/remove behavior from [storage utils](https://github.com/DavidWells/analytics/blob/master/packages/analytics-util-storage/src/index.js) is a bit different from that of [session storage utils](https://github.com/DavidWells/analytics/blob/23a39489d2d73ad8a6fe36e22596b8ea0067e45e/packages/analytics-util-storage-session/src/index.js). 

Namely, the former has support for an options argument which can force storage in all storage buckets (localStorage, cookie, and global) and it also forces JSON conversion on its input, as well as using a custom JSON `parse` function that can handle parsing JSON or just returning objects directly if that parsing fails. 

Are there any plans to bring the session storage utils inline with that behavior? I can work around this with some custom logic but it would be nice if the session storage utils behaved the same in terms of input handling and allowing "all" storage (sessionStorage and global in that case).

**Comment by DavidWells** [comment]
These packages are meant to be lightweight primitives where they all fall back to window storage.

- https://github.com/DavidWells/analytics/tree/master/packages/analytics-util-storage-session
- https://github.com/DavidWells/analytics/tree/master/packages/analytics-util-storage-local
- https://github.com/DavidWells/analytics/tree/master/packages/analytics-util-storage-cookie

The main https://github.com/DavidWells/analytics/tree/master/packages/analytics-util-storage uses (cookie + localstorage) with some additional logic to "be smart" about storing values.

I've thought about adding `analytics-util-storage-session` to `analytics-util-storage` but haven't really seen a need for it. 

Trying to keep storage utils as tiny as possible. There is probably some code golfing to do to shrink it even further.

**Comment by DavidWells** [comment]
What are you using session storage for?

**Comment by totalhack** [comment]
I'm storing one of my IDs in session storage because local storage is not appropriate for this use case. But I also want it to always store on the window as well in case storage gets wiped after some time, which I believe can happen on iOS now with the last rounds of ITP updates. 

So I had hoped the session storage util package had the same option as the storage util package where I could force it to save in all places. I worked around the issue by just creating the same logic locally.

**Comment by DavidWells** [comment]
I've gone ahead and added `sessionStorage` support to the `storage-utils` package.

Details in https://getanalytics.io/utils/storage/

It's available now in 

 - @analytics/storage-utils@0.3.0
 - analytics@0.7.22
