### ISSUE TITLE
How to integrate analytics.js in a WordPress site along with custom plugin?

### ISSUE THREAD

**Issue by aakash2610** [DavidWells/analytics#245]
Hi,

I want to track the custom events that are occurring on a WordPress site. Is there any way to do that using analytics.js? I have created a custom plugin which works very well in simple HTML, CSS and JavaScript website. I am not able to figure out how to use that plugin in a WordPress site. Please let me know if that is possible? If yes, then how?

Thanks!

**Comment by DavidWells** [comment]
Yeah, you can use `analytics` with any kind of site. 

You will probably want to load your analytics script with https://developer.wordpress.org/reference/functions/wp_enqueue_script or inline in your themes code.

See https://getanalytics.io/plugins/google-analytics/#additional-examples for how to integrate the library

Example using just HTML

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Using @analytics/google-analytics in HTML</title>
    <script src="https://unpkg.com/analytics/dist/analytics.min.js"></script>
    <script src="https://unpkg.com/@analytics/google-analytics/dist/@analytics/google-analytics.min.js"></script>
    <script type="text/javascript">
      /* Initialize analytics */
      var Analytics = _analytics.init({
        app: 'my-app-name',
        plugins: [
          analyticsGa.init({
            trackingId: 'UA-1234567'
          })
        ]
      })

      /* Track a page view */
      analytics.page()

      /* Track a custom event */
      analytics.track('playedVideo', {
        category: 'Videos',
        label: 'Fall Campaign',
        value: 42
      })

      /* Identify a visitor */
      analytics.identify('user-id-xyz', {
        firstName: 'bill',
        lastName: 'murray'
      })
    </script>
  </head>
  <body>
    ....
  </body>
</html>
```
