### ISSUE TITLE
Question: is the Segment plugin using the latest analytics-next package from Segment?

### ISSUE THREAD

**Issue by timonbimon** [DavidWells/analytics#248]
Hi there,

we've been having some problems with user sessions not showing up on Amplitude. We have Amplitude integrated via Segment's new "Amplitude (Actions)"-destination and Segment integrated via getanalytics.io :) 

While googling around I found that session tracking on Amplitude via Segment only works automatically if one is using Segment's new analytics library (https://github.com/segmentio/analytics-next/) => thus my question if this is being used here already?

**Comment by jegtugado** [comment]
If you look at [https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-segment/src/browser.js](https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-segment/src/browser.js) you can see that currently it uses `https://cdn.segment.com/analytics.js/v1/" + t + "/analytics.min.js` and the analytics-next is stated to be the v2.0

EDIT: Looking at this further, `"https://cdn.segment.com/analytics.js/v1/" + key + "/analytics.min.js"` is part of the default script when adding a new source in Segment. And as per https://github.com/segmentio/analytics-next/#-using-with-segment, the default script is already using Analytics 2.0

**Comment by Penners** [comment]
Looks like Segment's plan of action is to automatically migrate the accounts on these dates. Assuming the cdn urls remain the same looks like nothing needs to be done. 

https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/upgrade-to-ajs2/#automatic-migration
