### ISSUE TITLE
Namespaced hooks in plugins use the target plugin's config instead of own config

### ISSUE THREAD

**Issue by JuroOravec** [DavidWells/analytics#25]
**Current behavior:**
If I have 2 plugins, and one plugin defines a namespaced hook to run before the other plugin (`track:pluginB` in the example below), the config in the namespaced hook refers to the target plugin's config, instead of the config where the function was defined (see example below).

This is unexpected behavior, as one would expect that all hooks defined in single plugin would have access to their plugin's config object.

**Desired behavior:**
All hooks defined within one plugin should have access to their plugin's config object, regardless of whether they are namespaced or not.

```js
// plugin A
{
    name: "pluginA",
    config: {test: "A"},
    "track:pluginB": ({ config }) {
        // config refers to pluginB's config!
        console.log(config.test) // prints B
    }
    ...
  };

// plugin B
{
    name: "pluginB",
    config: {test: "B"},
    track:
        // config refers to pluginB's config!
        console.log(config.test) // prints B
    ...,
  };
```

**Comment by DavidWells** [comment]
Good catch! 

I've fixed this https://github.com/DavidWells/analytics/commit/a3cc443870c7cc697358d8a027384a5c1db96213 and added a test for coverage https://github.com/DavidWells/analytics/commit/f5282c9ef99326e5de8b849500beb3d694414fb9

Will release the fix to npm shortly

**Comment by DavidWells** [comment]
0.3.1 released with this fix. https://www.npmjs.com/package/analytics

Thanks again for the report!

**Comment by JuroOravec** [comment]
Thanks for the fix!
