### ISSUE TITLE
Conditional loading not working

### ISSUE THREAD

**Issue by renesijnke** [DavidWells/analytics#253]
Disabling a plugin with setting `enabled` to `false` in the plugin config is not working for me. It still sends out a pageview for example when using the Snowplow plugin. I followed the instructions [in the docs](https://getanalytics.io/conditional-loading/).

The weird thing is that using `analytics.plugins.disable(['snowplow'])` does work to prevent sending pageviews to Snowplow.

Let me know if I need to provide any other information

```
import Analytics from 'analytics'
import snowplowPlugin from '@analytics/snowplow'

const analytics = Analytics({
  app: 'app',
  plugins: [
    snowplowPlugin({
      name: 'snowplow',
      scriptSrc: '/sp.js',
      collectorUrl: 'url',
      trackerSettings: {
        appId: 'test'
      },
      enabled: false
    })
  ]
})

/* export the instance for usage in your app */
export default analytics
```

"@analytics/snowplow": "0.3.0"
"analytics": "0.8.0"

**Comment by DavidWells** [comment]
Interesting. Ah yes looks like it was missing the `config` value from plugin

https://github.com/DavidWells/analytics/commit/aecc60d1f7536c8945e0f9c3b8677a4eac19e2a8

Thanks for reporting

Fixed in `@analytics/snowplow@0.3.1`
