### ISSUE TITLE
DOC for inline plugin: page, track, identify quick question

### ISSUE THREAD

**Issue by j2l** [DavidWells/analytics#256]
Hello,
Thank you for this very open plugin!

I want to keep my data for me so I built an API server to populate a database locally and will build my queries :smile_cat:
Thanks for implementing the [custom-plugin](https://github.com/DavidWells/analytics/blob/297f9845543d5b058a8874dbb18922e1be70f750/site/main/source/resources/faq.md)

To extend to all your Analytics offers, would all types of records (page, track, identify, ...) should go in the same table? Or should I build different tables and API routes?

Thank you very much @DavidWells !

**Comment by DavidWells** [comment]
Hello there!

The table & endpoint design is totally up to you 😃

They can go into 1 DB or separate ones.
