### ISSUE TITLE
Cannot overwrite auto-generated anonymousId (Segment Plugin)

### ISSUE THREAD

**Issue by goowaa** [DavidWells/analytics#258]
It looks like I cannot overwrite auto-generated anonymousId when using segmentPlugin.

Example of the event dispatch:

```
import Analytics from 'analytics'
import segmentPlugin from '@analytics/segment'

const analytics = Analytics({
    app: 'awesome-app',
    plugins: [
        segmentPlugin({
            writeKey: 'key',
            disableAnonymousTraffic: false,
        }),
    ],
})

analytics.track('Test Event', { anonymousId: 'anonymous-dummy-id' })
```

Example of the same event when received in Segment

![image](https://user-images.githubusercontent.com/25343411/156765000-142dc179-02ed-469c-890b-1f96953ab363.png)

**Comment by DavidWells** [comment]
You can set the anonymous ID in the initialization of the lib like this https://github.com/DavidWells/analytics/issues/171#issuecomment-822774119 

Or via https://github.com/DavidWells/analytics/blob/master/packages/analytics-core/src/index.js#L797-L812

```js
analytics.setAnonymousId('1234567')
```

Or you can intercept the storage via the `setItemStart` event https://getanalytics.io/lifecycle/#storage-events like this:

```js
import Analytics from 'analytics'

const customAnonIdPlugin = {
  name: 'set-anon-id',
  // On storage event, intercept and value custom value
  setItemStart: ({ payload, instance }) => {
    if (payload.key === '__anon_id') {
      return {
        ...payload,
        // Change anon id value to be saved
        ...{ value: 'my-custom-anon-id' }
      }
    }
  }
}

// Initialize analytics
const analytics = Analytics({
  app: 'site',
  version: '1.0.0',
  plugins: [
    // Set custom values
    customAnonIdPlugin,
    // Load analytics provider pluginss...
    googleTagManagerPlugin({
      containerId: 'GTM-XYZ'
    }),
    ...
  ]
})
```

**Comment by jedashford** [comment]
A year old here, but we use nextjs middleware to set the segment anon id in cookies. Then when the web app loads, the segment ID is not synced to this analytics library even with syncAnonymousId set. When the user navigates to a a new route, then all works, but we had all of the first events fired out with the wrong anonymous ids for a long time. The custom plugin fixed it, but others may be aware, if they share the same architecture, that the anonymous id doesn't sync on first application load.
