### ISSUE TITLE
Documentation Update - Snowplow from 0.2.5 to 0.3.x

### ISSUE THREAD

**Issue by markojak** [DavidWells/analytics#260]
I noticed that `@analytics/snowplow` was upgraded to 0.3.x with the biggest change being migrating Snowplow Tracker from v2 to v3. The documentation has not been updated to reflect this and I am not sure what needs to be changed in order for it to work.
https://github.com/DavidWells/analytics/blob/master/site/main/source/plugins/snowplow.md

When we update the package to 0.3.2 we get the following error when Analytics loads the Snowplow Plugin:

```
analytics-plugin-snowplow.browser.es.js:142 Uncaught (in promise) ReferenceError: plugins is not defined
    at Object.initialize (analytics-plugin-snowplow.browser.es.js:142:9)
    at eval (analytics-core.module.js:14:9319)
```

We are loading the Snowplow plugin as per the documentation

@paulboocock Is this something you can please help with? You've been so great at this.

**Comment by DavidWells** [comment]
Hey @markojak 

I released `@analytics/snowplow@0.3.3` with a fix for missing plugins array.

**Comment by markojak** [comment]
Hi @DavidWells - thanks I have tested this out and can confirm that 0.3.3 is working the plugins array.
I am still loading Snowplow as per the Documentation (pseudo code below)
This means that I am loading it using the 2.18.2 tracker.

From what I recall the last bump @paulboocock made was to enable v3 Browser-tracker with getanalytics.io

My understanding is that it would then mean I wouldn't need to load via `scriptSrc` and use something like 

`import { newTracker, trackPageView } from "@snowplow/browser-tracker";`

The thing is that I don't know how this interfaces with the analytics() wrapper. I'd be happy to PR an update to the Documentation but I'm struggling to figure it out. 

Would you be able to share a few pointers on how we could load the v3 tracker via the browser-tracker package?

```
            const analytics = Analytics({
                app: 'secta',
                plugins: [
                    snowplowPlugin({
                        name: 'snowplow',
                        scriptSrc: 'https://cdn.secta.ai/2.18.2/ufmgttg7.js',
                        collectorUrl: 'sp.secta.ai',
                        trackerSettings: {
                            appId: spAppId,
                            discoverRootDomain: true,
                            cookieName: '_secta_',
                            cookieSameSite: 'Lax',
                            contexts: {
                                webPage: true,
                                gaCookies: true,
                            },
                        },
                    }),
                ],
            })
```

And the plugins section

```
                analytics.on('initialize:snowplow', ({ instance }) => {
                    instance.plugins.snowplow.enableActivityTracking(10, 10)
                    instance.plugins.snowplow.enableLinkClickTracking()
                    instance.plugins.snowplow.enableFormTracking()
}
```

**Comment by markojak** [comment]
Hey all -

Discovered this here with the latest v3 bump.
https://github.com/DavidWells/analytics/blob/master/examples/demo/src/utils/analytics/example-6.js

It seems that to migrate the Snowplow Plugin from v2 to v3 all is needed is to remove the `scriptSrc:`

This was done rather elegantly. The peer dependences are now bundled within `analytics@snowplow@0.3.3` (this explains the 20kB size bump in the package) and to implement this you just need to remove the `collectorUrl`

I'm going to do a PR on the documentation now to reflect this.
