### ISSUE TITLE
Is it possible to track modal views as in ReactGA.modalview(modalName) in react-ga?

### ISSUE THREAD

**Issue by konstantinkrumin** [DavidWells/analytics#261]
Hello,

I recently set up Analytics library for my app and I was wondering whether it is possible to set up a modal view like the one that is specified in the [react-ga documentation](https://github.com/react-ga/react-ga#reactgamodalviewmodalname). I assume it could be done via setting up a trigger event on a button that opens up the modal, however I was wondering whether there's a standalone method for it in Analytics library?

**Comment by DavidWells** [comment]
Yeah, you can set category with `analytics.track`

See the docs at https://getanalytics.io/plugins/google-analytics/#how-to-use

**Comment by konstantinkrumin** [comment]
> Yeah, you can set category with `analytics.track`
> 
> See the docs at https://getanalytics.io/plugins/google-analytics/#how-to-use

thank you!
