### ISSUE TITLE
Passing value to the Google Analytics track() function is not working 

### ISSUE THREAD

**Issue by konstantinkrumin** [DavidWells/analytics#262]
Hello,

I set up Google Analytics plugin according to this [tutorial](https://www.youtube.com/watch?v=C_1ced3l9cU) on Youtube. Basically almost everything is working, like passing category and label and action name in the title, however when I try to dynamically set up a value for value field the request seems to not go through to Google Analytics. I tried converting it to string, but got no luck

```
const dataViewChangeHandler = (value: string | number) => {
		onValueChange(value as DataViewType);
		if (value) {
			console.log('VALUE');
			console.log(value);
			const values = value.toString();
			if (values) {
				track('appliedDateFilter', {
					category: 'filtering',
					label: 'appliedDateFilterOnDiagnosticsPage',
					value: values
				});
			}
		}
};
```

Everything seems to be fine with this value that is being passed to the function, it prints out in console value.
I also tried to hardcode the value with a string or number and in that case it all worked.

Could you please help me?

Ideally I would need to pass the following object there in this case:

```
value: {
	pathname: pathname,
	selectedDateType: value
 }
```

**Comment by DavidWells** [comment]
Hello there.

The mapping happens here: https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-google-analytics/src/browser.js#L203-L223

It looks like the code should work. Verify the network request in dev tools to see if your values are in the requests to google analytics

```
				analytics.track('appliedDateFilter', {
					category: 'filtering',
					label: 'appliedDateFilterOnDiagnosticsPage',
					value: values
				});
```

**Comment by konstantinkrumin** [comment]
Hello,

I noticed that it is not working for me whenever I'm trying to set up the value of the string dynamically dynamically.

Now, I tried to do the following:

```
const onDiagnosticsSectionChangeHandler = (selectedValue: string) => {
		const selectedOption = diagnosticsOptions.find(({ value }) => value === selectedValue);
		if (selectedOption) {
			setCurrentDiagnostics(selectedOption);
			console.log(selectedOption.value);
			console.log(typeof selectedOption.value);
			if (selectedOption.value) {
				track('changed-diagnostics-type', {
					category: 'select',
					label: `changed-diagnostics-type-to-${selectedOption.value}-on-diagnostics-page`
				});
			}
		}
	};
```

All values are there and printing just right, POST request also goes through with 200 Status Code and it contains the following string: `&ea=changed-diagnostics-type&el=changed-diagnostics-type-to-emails-on-diagnostics-page` in the Request URL. But the request is not displaying in Google Analytics dashboard.

As soon as I change it to a string with predefined value it works just fine.

UPDATE: Just noticed that for some reason it for some reason returns it as a 'image/gif' in the response header, in such case.

<img width="695" alt="image" src="https://user-images.githubusercontent.com/12476225/159074286-d589cca7-442d-404e-a4c7-f76a0a670092.png">

And soon as I remove a dynamic value it becomes a xhr:

<img width="541" alt="image" src="https://user-images.githubusercontent.com/12476225/159074404-517b325a-2c96-4a7f-962b-1b203f0b5df6.png">

**Comment by DavidWells** [comment]
Mmmmm interesting. It's possible that `changed-diagnostics-type-to-emails-on-diagnostics-page` is too long. 

Not sure why the value isn't in GA for you. Try shortening the label

The `gif` is correct. Thats how GA sends data.

As long as the call to `/collect` is happening with your values the plugin is operating as it should be. It sounds like this may be a problem with length of label, the value used (special chars maybe?) or something else in GA

Some limits are listed here https://stackoverflow.com/questions/12280993/google-analytics-event-tracking-max-string-length#:~:text=Max%20Length%20for%20Event%20Label%20%3D%20500%20Bytes

**Comment by konstantinkrumin** [comment]
Yeah was pretty interesting case, I changed the library to react-ga and it seemed to work with the same parameters. Not sure what was this case since the requests to GA seemed to go through
