### ISSUE TITLE
Create Google Analytics 4 Plugin

### ISSUE THREAD

**Issue by claudfuen** [DavidWells/analytics#270]
Google is officially deprecating Universal Analytics in June 2023 and asking all users to transition to GA4.

Having a native plugin for implementing GA4 would be a huge help in transitioning our projects without doing a manual implementation.

**Comment by andyjagoe** [comment]
Does anyone know someone working on this? Analytics is a great project but I think support for Google Analytics is critical.

**Comment by claudfuen** [comment]
@andyjagoe I ended up creating my own "extension" file for /analytics.

// in utils/analytics.js
``` 
import Analytics from 'analytics'
import ga4Plugin from './analyticsCustomExtensions/ga4Plugin.ts'


let analytics = Analytics({})

analytics = Analytics({
  app: 'my-app',
  plugins: [
    ga4Plugin({
      trackingId: 'G-0000000000', // Insert your Google Analytics Tracking Id
    }),
  ],
})

export default analytics

```

// in ga4Plugin.ts
```
import { AnalyticsInstance } from "analytics";
import ReactGA from "react-ga4";

type IPluginProps = {
  instance: AnalyticsInstance;
  config: IPluginConfig;
};

type IPluginConfig = {
  trackingId: string;
};

const defaultConfig = {
  enabled: true,
};

export default function ga4(pluginConfig: IPluginConfig) {
  return {
    name: "ga4-analytics",
    config: {
      ...defaultConfig,
      ...pluginConfig,
    },

    initialize: (plugin: IPluginProps) => {
      const { config } = plugin;
      const { trackingId } = config;

      ReactGA.initialize(trackingId);
    },

    loaded: () => {
      return true;
    },

    identify: () => {
    },

    track: ({ payload }) => {
      ReactGA.event({
        category: "event",
        action: payload.event,
      });
    },
  };
}

```

Hope this helps!

**Comment by andyjagoe** [comment]
Thanks @claudfuen! I'll try it out.

**Comment by pe1uca** [comment]
@claudfuen great solution.  

ReactGA still is only meant for client side tracking (requires `window`).  
For server side just replace `ReactGA.event` with [the direct call](https://developers.google.com/analytics/devguides/collection/protocol/ga4/reference?client_type=gtag).  
```js
axios.post(`https://www.google-analytics.com/mp/collect?measurement_id=${measurementId}&api_secret=${secret}`, {
	client_id: client_id,
	events: [
		{
			name: payload.event,
			params: payload.properties
		}
	]
});
```

**Comment by dobesv** [comment]
The `google-analytics` plugin is using GA4 in this project now.  The `google-analytics-v3` plugin is for universal analytics.  So I think this can be closed.

**Comment by afgallo** [comment]
I am super confused with GA4 vs GA3. There are so many issues that reference GA4:

- https://github.com/DavidWells/analytics/issues/284
- https://github.com/DavidWells/analytics/issues/206
- https://github.com/DavidWells/analytics/issues/173
- https://github.com/DavidWells/analytics/issues/107

I get the _impression_ that the analytics version I am running _should_ be able to work out of the box with GA4 and yet I don't see any events being tracked.

Here's what I have installed:
```
"@analytics/google-analytics": "0.5.3",
"analytics": "0.8.1",
"use-analytics": "0.0.5"
```

Here's my basic configuration:

```
import Analytics from 'analytics'
import googleAnalyticsPlugin from '@analytics/google-analytics'
import { GA_TRACKING_ID, ENV } from './constants'

// Initialize analytics and plugins
// Documentation: https://getanalytics.io
const analytics = Analytics({
  app: 'App',
  debug: !ENV.IS_PRODUCTION,
  plugins: [
    googleAnalyticsPlugin({
      trackingId: GA_TRACKING_ID,
      enabled: ENV.NAME !== 'test'
    })
  ]
})

export default analytics
```

I have then implemented tracking following this https://getanalytics.io/tutorials/using-with-react-router/

Can anyone shed some light please, thank you!

**Comment by jurajmatus** [comment]
From what I understand, the version 4 is still in beta and hasn't been released yet into npm. I'm also awaiting it, so I would be glad to hear what's the status and when can we expect the release?

**Comment by dobesv** [comment]
Ah, I hadn't realized the GA4 version wasn't released yet.

**Comment by DavidWells** [comment]
GA 4 is released via `npm i @analytics/google-analytics@latest`

Please note: GA3 has moved to https://www.npmjs.com/package/@analytics/google-analytics-v3

Should work as drop-in replacement but `label` and `category` aren't fields GA4 needs like GA3 and below do.

**Comment by DavidWells** [comment]
At long last, GA4 is released via version 1+ of the https://www.npmjs.com/package/@analytics/google-analytics package.

You can install and use via this command

```
npm install @analytics/google-analytics@latest
```

**Note this is a breaking change** and you will need to setup a google analytics 4 property & stream and use its measurement ID.

If you want to continue using older google analytics 3, which is honestly a completely different product, you will want to switch to the https://www.npmjs.com/package/@analytics/google-analytics-v3 package.

**Using both GA3 and GA4*

It is possible to use both GA3 and GA4 together like so:

```js
import Analytics from 'analytics'
import googleAnalyticsPlugin from '@analytics/google-analytics'
import googleAnalyticsV3Plugin from '@analytics/google-analytics-v3'

/* Initialize analytics instance */
const analytics = Analytics({
  app: 'my-app',
  plugins: [
    /* Load Google Analytics v4 */
    googleAnalyticsPlugin({
      measurementIds: ['G-abc123'],
    }),
    /* Load Google Analytics v3 */
    googleAnalyticsPlugin({
      trackingId: 'UA-11111111-2',
    }),
  ],
})

analytics.page()
```

Just remember GA3 will be deprecated starting in July of 2023

**Comment by zuccs** [comment]
Should it be: 

```
/* Load Google Analytics v3 */
    googleAnalyticsV3Plugin({
      trackingId: 'UA-11111111-2',
    }),
```
