### ISSUE TITLE
Batching events?

### ISSUE THREAD

**Issue by Drabuna** [DavidWells/analytics#272]
I'm considering using this library for analytics in my project.
One of the things that concern me is that every track event will result in a network call.
Is there a way to batch events, and only send the whole batch to the backend every 5-10 seconds or so, while using local storage to preserve the state?
I assume I can get this functionality rather easily by building my own plugin, but maybe there is something I missed in the docs?
Is there any good reason not to do this?
Based on what I've seen from different client-side analytics libraries (like for example Google), they don't fire a network call on every event.

**Comment by paul-vd** [comment]
@Drabuna did you ever find a solution for this? if you have implemented something do you mind sharing, as have the same requirement.

**Comment by DavidWells** [comment]
You can batch send requests. See the aws pinpoint plugin for an example https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-aws-pinpoint/src/pinpoint/index.js#L28-L41

**Comment by DavidWells** [comment]
Uses the `queue` util https://github.com/DavidWells/analytics/blob/master/packages/analytics-util-queue/example.js
