### ISSUE TITLE
Hotjar plugin

### ISSUE THREAD

**Issue by VizcomAI** [DavidWells/analytics#275]
Hey!

Is an integration with hotjar, software similar to fullstory, in the works?

Thanks!

**Comment by DavidWells** [comment]
Moved to https://github.com/DavidWells/analytics/issues/153

I'd be open to a PR for this 😃

Let me know if you have questions on creating plugins.

The docs are over here https://getanalytics.io/plugins/writing-plugins/

**Comment by OxMarco** [comment]
@DavidWells would it be possible to just use the Google Tag Manager plugin and add hotjar tracking code to it?
