### ISSUE TITLE
Simple Analytics - config is not defined

### ISSUE THREAD

**Issue by dylmye** [DavidWells/analytics#276]
I'm getting an error trying to track events using the SA plugin:

![image](https://user-images.githubusercontent.com/7024578/168347754-12132d53-cabf-492b-93f7-ea4438f0599f.png)

I think it's because we should have `config` as a parameter on L83, like other analytics plugins:

https://github.com/DavidWells/analytics/blob/87ff904ff1c17137823c7bdc3821ce95299f88e2/packages/analytics-plugin-simple-analytics/src/browser.js#L83-L87

Or it should be `pluginConfig`?

Please let me know if you want me to make a PR or if you think I'm wrong here

**Comment by DavidWells** [comment]
Fixed and released in `@analytics/simple-analytics@0.3.4`

Thanks for the report!
