### ISSUE TITLE
Bundle Size: Use Babel Transform Runtime

### ISSUE THREAD

**Issue by ScriptedAlchemy** [DavidWells/analytics#277]
It would be great to offer a non-inline babel implementation for npm consumption. 

This package is larger than it needs to be because babel is inlining all the polyfill/syntax sugar. So im not able to take re-use the babel helpers. 

I think everything is inlined in browser.es so that one could embed it directly off a CDN, this isnt so great for install-based consumers and causes analytics to be one of the largest single files we import

It would be great to support a more optimal build output when consumed by something like webpack. 

We are happy to send a PR if this would be accepted.

**Comment by DavidWells** [comment]
Hello there. I think this is already solved. Babel was removed for microbundle a lil bit ago.

Please let me know if that's not the case 😃
