### ISSUE TITLE
Multiple instances of analytics-plugin-google-tag-manager

### ISSUE THREAD

**Issue by zobzn** [DavidWells/analytics#28]
How to correctly add multiple instances of the same plugin?
I need two instances of the analytics-plugin-google-tag-manager on a page.
As far as I know GTM doesn't forbid it and even has an example https://developers.google.com/tag-manager/devguide#multiple-containers.

This code won't work (error related to namespaces).
```
  plugins: [
    googleTagManager({containerId: 'GTM-123xxx'}),
    googleTagManager({containerId: 'GTM-123yyy'}),
  ]
```

I guess I could overcome it with little overriding like this
```
  plugins: [
    {...googleTagManager({containerId: 'GTM-123xxx'}), NAMESPACE: 'google-tag-manager-1'},
    {...googleTagManager({containerId: 'GTM-123yyy'}), NAMESPACE: 'google-tag-manager-2'},
  ]
```

But it won't work either - in plugin's `initialize` method script is being injected only when there is no .../gtm.js script on a page (regardless of it's containerId param).

Maybe `scriptLoaded` function should be rewritten with containerId parameter?

David, what your suggestions could be on this matter?

**Comment by DavidWells** [comment]
Good question. 

I'm not too familiar with how GTM datalayer works with multiple instances loaded. 

Right now the google tag manager is checking if the GTM [script is loaded](https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-google-tag-manager/src/browser.js#L87-L93) and if the [data layer exists](https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-google-tag-manager/src/browser.js#L78-L80)

You can use the overrides method as you mentioned. You can do something like:

```js
{
  plugins: [
    googleTagManager({containerId: 'GTM-123xxx'}),
    {
      ...googleTagManager({containerId: 'GTM-123yyy'}), 
      name: 'google-tag-manager-2', // <-- name overide to prevent namespace collision
      initialize: () => { /* custom init if needed for second instance */},
      loaded: () => { /* custom logic to verify second instance loaded */},
    },
  ]
}
```

---

> Maybe scriptLoaded function should be rewritten with containerId parameter?

This could also work. Something like:

```js
function googleTagManager(pluginConfig = {}) {
  // Allow for userland overides of base methods
  return {
    NAMESPACE: 'google-tag-manager',
    config: {
      ...config,
      ...pluginConfig
    },
    initialize: ({ config }) => {
      const { containerId } = config
      if (!containerId) {
        throw new Error('No google tag manager containerId defined')
      }
      if (!scriptLoaded(pluginConfig.containerId)) {
        // load script again?
      }
    },
    page: () => {},
    track: () => {},
    loaded: () => {
      const hasDataLayer = !!(window.dataLayer && Array.prototype.push !== window.dataLayer.push)
      return scriptLoaded(pluginConfig.containerId) && hasDataLayer
    },
  }
}

function scriptLoaded(containerId) {
  const scripts = document.getElementsByTagName('script')
  return !!Object.keys(scripts).filter((key) => {
    const { src } = scripts[key]
    // update regex to use container id 
    return src.match(/googletagmanager\.com\/gtm\.js/)
  }).length
}
```

What do you think?

**Comment by zobzn** [comment]
Thank you. I guess this https://github.com/DavidWells/analytics/pull/30 should do the trick

**Comment by DavidWells** [comment]
Looks great! 

Verified it works 🎉and added an [example](https://github.com/DavidWells/analytics/blob/23ecaf9dc83bbd88e32f507238b372cebd19bd50/examples/demo/src/utils/analytics/example-multiple-gtm-instances.js)

![image](https://user-images.githubusercontent.com/532272/76135860-99654f80-605d-11ea-8777-3a13ed398dbb.png)

Successfully published to `@analytics/google-tag-manager@0.2.2`

**Comment by DavidWells** [comment]
https://twitter.com/DavidWells/status/1236139603574177792

**Comment by zobzn** [comment]
Thank you. Published in production )) 👍
