### ISSUE TITLE
How can I dynamically change enabled plugins?

### ISSUE THREAD

**Issue by bryandickson** [DavidWells/analytics#280]
It is looking like I'll have to write a decent amount of code to be able to dynamically change/switch enabled plugins after login (potentially more than one at a time).  Idea would be to have a default set of plugins/providers until a user logs in and/or changes their consent, then disable/enable the appropriate plugins that user is configured for (once they have logged in).  Thoughts?

**Comment by DavidWells** [comment]
https://getanalytics.io/conditional-loading/#enabling--disabling-plugins

You can initialize with nothing on then enable when user opts in

**Comment by bryandickson** [comment]
Perfect, thank you!
