### ISSUE TITLE
Nextjs; unable to enable/disable mixpanel plugin

### ISSUE THREAD

**Issue by amie-wilt** [DavidWells/analytics#281]
Hello,

I'm looking to enable/disable mixpanel based on users' opt-in/opt-out preference. If I instantiate with `enabled: false`, I can't enable. If I don't set that prop—defaulting to enabled—I can't disable.

I've tried 
```
analytics.plugins.enable('mixpanel')
analytics.plugins.disable('mixpanel')
```

and 

```
analytics.enablePlugin('mixpanel')
analytics.disablePlugin('mixpanel')
```
My setup:

```
const plugins = [
  mixpanelPlugin({
    token: process.env.NEXT_PUBLIC_MIXPANEL_KEY,
  }),
];

export const analytics = Analytics({
  app: '3fr-web',
  plugins: [...(IS_BROWSER && IS_APP_3FR_COM ? plugins : [])],
});

if (IS_APP_3FR_COM) {
  mixpanel.init(process.env.NEXT_PUBLIC_MIXPANEL_KEY);
}
```

Also, I tried without the `mixpanel.init()` and that didn't fix it. 

```
"@analytics/mixpanel": "^0.4.0",
"analytics": "^0.7.23",
"mixpanel-browser": "^2.45.0",
```

Thank you,

Amie

**Comment by DavidWells** [comment]
What is that `mixpanel.init(process.env.NEXT_PUBLIC_MIXPANEL_KEY);` you have there?

The plugin is "self contained" and will initialize mixpanel on the page for ya. 

Are you loading mixpanel elsewhere as well? Like in next.js `Script` component or something?

**Comment by amie-wilt** [comment]
I found that the email wasn't always being set so I added that snippet so I could do this:

```
export function setMixpanelEmail(email) {
  mixpanel.people.set({
    $email: email,
  });
}
```

EDIT: Only loading/init-ing mixpanel there.

**Comment by amie-wilt** [comment]
"Also, I tried without the mixpanel.init() and that didn't fix it."

I only commented `mixpanel.init()` when I tried this. I removed all code regarding the mixpanel instance and uninstalled mixpanel-browser and as you can probably surmise, it fixed the issue. Sorry for wasting your time with this, I should've done a better job debugging before opening an issue.
