### ISSUE TITLE
Is there any reference for @types/analytics for Typing issue while Image Build

### ISSUE THREAD

**Issue by Ankit834** [DavidWells/analytics#282]
In my case, I am loading the analytics module via script in `index.html` file as:-
<script src="https://unpkg.com/analytics/dist/analytics.min.js"></script>

And then I am running a custom script and adding `window.analytics` as a global object with analytics reference.
So on building the solution, on type check I am getting `cannot find name 'analytics'`.
Can I get a helping hand if there is any other script/package I can add to my solution for this? Here I am trying to avoid creating my custom types so to have less maintainability.

**Comment by dobesv** [comment]
I think maybe something in this article here might help:

https://bobbyhadz.com/blog/typescript-declare-global-variable#:~:text=To%20declare%20a%20global%20variable,the%20necessary%20properties%20or%20methods.

**Comment by Ankit834** [comment]
Thank you for your response @dobesv . I got it fixed a couple of weeks back by adding the typings under global for analytics. Since only few of the functions were in scope.
Also the link implements the same.
Closing the issue now. Thanks Again
