### ISSUE TITLE
GA4 trackingId -> measurementIds

### ISSUE THREAD

**Issue by dobesv** [DavidWells/analytics#284]
In Google Analytics 4, they have changed terminology from "tracking ID" to "measurement ID", and you can seemingly load multiple of them.  It would be nice if the configuration key for GA4 was called `measuremendIds` instead of `trackingId` for consistency.

See https://github.com/segmentio/analytics.js-integrations/blob/master/integrations/google-analytics-4/lib/index.js for inspiration.

**Comment by DavidWells** [comment]
Aha i see that. Thanks for the info, I've updated the code to allow for multiple "streams" or whatever they are called 😅

I'm curious, would different `measuremendIds` want different configurations or all the same config?

**Comment by dobesv** [comment]
TBH I'm not sure, we only use one measurement ID in our project.  But I do see GA4 supports it, so  ... might as well support it too?

Probably kind of a niche use case, honestly.

**Comment by dobesv** [comment]
My main interest here was changing the name of the config key to `measurementId` or `measurementIds` so that it's clear that it's GA4 and what to search for in the google analytics docs.

**Comment by DavidWells** [comment]
Set this up here https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-google-analytics/src/browser.js#L131

Still working on the final plugin config values, then this will get published to NPM for consumption

**Comment by dobesv** [comment]
Won't you have to replace calls to `window.gtag` to something that uses the specific dataLayer name?  Otherwise I think there could be conflicts as you could have two things over-writing `window.gtag` with a different binding to `window.dataLayer.push` or `window.ga4DataLayer.push`.

**Comment by DavidWells** [comment]
Good call. Updated to allow for custom dataLayerName and custom gtag name https://github.com/DavidWells/analytics/commit/6c41881b997b249f542d5ae2b928f8bd4fd0bd5c

**Comment by afgallo** [comment]
Hi @DavidWells,

I was just wondering if you could help with my comment on #270? I know I must be doing something wrong 🤦🏻‍♂️
