### ISSUE TITLE
GA4 data layer name

### ISSUE THREAD

**Issue by dobesv** [DavidWells/analytics#285]
It would be nice if the Google Analytics 4 plugin used a non-default data layer name, like `ga4DataLayer`.  That way if we use Google Tag Manager and Google Analytics 4 together we don't have a naming conflict.

See for example how segment's integration renamed the GA4 data layer to `ga4DataLayer`.

https://github.com/segmentio/analytics.js-integrations/blob/master/integrations/google-analytics-4/lib/index.js

**Comment by DavidWells** [comment]
Good call, I've updated this to allow for custom datalayer name!

**Comment by DavidWells** [comment]
Added this!
