### ISSUE TITLE
Google Analytics v3 plugin not found on registry

### ISSUE THREAD

**Issue by yeseniamolinab** [DavidWells/analytics#286]
I tried to install the Google Analytics V3 plugin since the migration to Google Analytics 4 is not done yet on my side.
But I am getting a not found error for the [plugin package](https://registry.yarnpkg.com/@analytics%2fgoogle-analytics-v3)

````
yarn add @analytics/google-analytics-v3
yarn add v1.22.17
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@analytics%2fgoogle-analytics-v3: Not found".
Info If you think this is a bug, please open a bug report with the information provided in "/Users/yesimolina/Documents/Code/pronto/yarn-error.log."
Info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
````
Let me know if you need more information.

**Comment by DavidWells** [comment]
Yep sorry about that not yet published. Will be soon in meantime u can use the same code via `npm i @analytics/google-analytics@0.5.3`

Heads up, the 1.0 will be GA version 4 (a breaking change) use the `@analytics/google-analytics-v3` after v1 lands if you are considering with GA3 and below

**Comment by yeseniamolinab** [comment]
Thank you!
