### ISSUE TITLE
Vue example: middlewares not a function error

### ISSUE THREAD

**Issue by fraser-m-hurley-LTK** [DavidWells/analytics#29]
Hi, I'm experimenting building out a basic custom plugin which I am looking to add to the vue example. When I add even the most basic custom plugin (like the one in the docs that does nothing) I am getting the following error:

`applyMiddleware.js?05f2:39 Uncaught TypeError: middleware is not a function
    at eval (applyMiddleware.js?05f2:39)
    at Array.map (<anonymous>)
    at eval (applyMiddleware.js?05f2:38)
    at <anonymous>:1:28399
    at createStore (createStore.js?61ed:51)
    at analytics (analytics.browser.es.js?4747:3847)
    at eval (analytics.js?da7c:4)
    at Module../src/analytics.js (app.js:2662)
    at __webpack_require__ (app.js:726)
    at fn (app.js:101)`

I'm guessing its some sort of dependency version problem(?) but would really appreciate any insight.

**Comment by DavidWells** [comment]
Hello there.

It sounds like a plugin is malformed & is not being loaded properly 

What does the code look like?

A link to the implementation & the plugins you are using would help diagnose the issue

**Comment by fraser-m-hurley-LTK** [comment]
Hi, thanks for the reply! I've literally copy and pasted the example plugin

Plugin code:
`  export default function demoPlugin(userConfig) {
    return {
      name: 'demo-plugin',
      bootstrap: ({ payload, config, instance }) => {
        // Do whatever on `bootstrap` event
      },
      pageStart: ({ payload, config, instance }) => {
        // Fire custom logic before analytics.page() calls
      },
      pageEnd: ({ payload, config, instance }) => {
        // Fire custom logic after analytics.page() calls
      },
      trackStart: ({ payload, config, instance }) => {
        // Fire custom logic before analytics.track() calls
      },
      trackEnd: ({ payload, config, instance }) => {
        // Fire custom logic after analytics.track() calls
      },
      // ... hook into other events
    }
  }`

Analytics config:
` 
import Analytics from 'analytics'
import demoPlugin from './demoPlugin'

const analytics = Analytics({
  app: 'my-vue-app',
  debug: true,
  plugins: [
    demoPlugin({
    }),
  ]
})

export default analytics`

**Comment by DavidWells** [comment]
Can you `console.log(demoPlugin)` and ensure it’s being imported correctly?

It should be a function 

If it is, `console.log(demoPlugin())` and ensure that it’s and object with name and the events you are hooking into.

**Comment by fraser-m-hurley-LTK** [comment]
I've done both and can see its being imported correctly and when calling the function, its an object with the name and events I'm hooking into
![Screenshot 2020-03-01 at 13 42 24](https://user-images.githubusercontent.com/50616834/75625885-93392400-5bc2-11ea-8e4f-04ca450c62f4.png)
![Screenshot 2020-03-01 at 13 42 38](https://user-images.githubusercontent.com/50616834/75625886-93d1ba80-5bc2-11ea-9614-dd9e08d1fc27.png)

**Comment by fraser-m-hurley-LTK** [comment]
I played around a little more and got it working when I provided a `NAMESPACE` attribute. Looking through the docs I'm not sure this is how it should be (or at least not how its documented). Is that something that should be modified in the docs?

**Comment by DavidWells** [comment]
NAMESPACE was changed to name. It sounds like that version of analytics needs to get updated to 0.3.0 in the demo

NAMESPACE and name both work (for backwards compatibility) but older analytics version won’t understand ‘name’

**Comment by DavidWells** [comment]
Oops yeah looks like demos need to be updated to latest https://github.com/DavidWells/analytics/blob/master/examples/vue/package.json#L14
