### ISSUE TITLE
Question: What are the responsibilities of the analytics lib as opposed to the plugin?

### ISSUE THREAD

**Issue by longility** [DavidWells/analytics#294]
Hey, I'm new here and trying to analyze and understand a bit as I plan on evaluating the effort on creating a custom plugin. 

What are the responsibilities of the analytics lib as opposed to the plugin? https://getanalytics.io/#features
This is what I think should is happening based on analysis but there are some things I see that questions it.

- Add functionality/modify tracking calls with baked in lifecycle hooks **PLUGIN**
- Isomorphic. Works in browser & on server **PLUGIN**
- Queues events to send when analytic libraries are loaded **ANALYTICS**
- Works offline **ANALYTICS**

The feature I'm questioning is "Queues events to send when analytic libraries are loaded" as I would expect that to be the responsibility of analytics lib. However, a quick gander at the aws pinpoint plugin, I see these:
- https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-aws-pinpoint/src/pinpoint/helpers/create-event-queue.js
- https://github.com/DavidWells/analytics/blob/5eba4d0fca9fd2c6cef3663d2b04b2f31856d16d/packages/analytics-plugin-aws-pinpoint/src/pinpoint/index.js#L1

Can you help me understand how come the pinpoint plugin has some queue logic on why that is there so I can understand what gap there is where I may need to fill when writing a custom plugin? Also, if you can help me understand what queue logic is handled by analytics. I am assuming that the analytics lib handles the queuing before the plugin is loaded or if the system is offline.

Is there documentation somewhere that I may have missed?

Thanks in advance.

**Comment by DavidWells** [comment]
If the analytics plugin isn't loaded yet or if the network is offline, the events sent to the plugin will be queued by the core library. Once the plugins `loaded` function evaluates to true or network connection enabled, the events will fire into the plugins `track`, `page`, and `identify` methods to send the data to the sinks.

The pinpoint plugin has an additional (optional) queuing mechanism to batch the requests going to the pinpoint service. You can do something similar if there are costs associated with "too many" calls to an analytics provider. If this isn't a concern, you can just send the data normally described in https://getanalytics.io/plugins/writing-plugins/#1-provider-plugins

I'd recommend just creating a simple plugin and not worrying about an additional batching queue in your plugin unless you really need it

**Comment by longility** [comment]
Thanks for clarity!
