### ISSUE TITLE
Google Tag Manager not working with custom domain

### ISSUE THREAD

**Issue by AdrienFery** [DavidWells/analytics#306]
https://github.com/DavidWells/analytics/blob/764fd74ddf130a213f9ba11d6a40e68bdfa44862/packages/analytics-plugin-google-tag-manager/src/browser.js#L119

The regex here do not take into consideration `customScriptSrc` parameter.

**Comment by AdrienFery** [comment]
I have created a pull request with a fix: #307

**Comment by nourdandan** [comment]
Hey all, can the custom domain be passed as a configuration when initializing the Analytics object e.g. 
const analytics = Analytics({
  app: 'awesome-app',
  plugins: [
    googleTagManager({
      containerId: 'GTM-123xyz',
      domain: 'mycustomdomain.com'
    })
  ]
})
