### ISSUE TITLE
Is it cookieless?

### ISSUE THREAD

**Issue by leonanluppi** [DavidWells/analytics#310]
Can i use it to tracking user behavior with cookieless?

**Comment by DavidWells** [comment]
You can disable all storage mechanisms with plugins and events https://getanalytics.io/lifecycle/#storage-events `setItemStart` or by using just `@analytics/core` https://github.com/DavidWells/analytics/tree/master/packages/analytics-core storage mechanisms from `analytics` are passed in here https://github.com/DavidWells/analytics/blob/master/packages/analytics/src/index.js#L2

I'd recommend using `@analytics/core` if you want to disable all storage mechanisms
