### ISSUE TITLE
Where is the Changelog?

### ISSUE THREAD

**Issue by dmoKruso** [DavidWells/analytics#314]
I am not able to find any changelog. Where can I find it?

I am using version 0.8.0, and my npm says there is a 0.8.1, but on the releases tags I can find some newer ones as 0.8.4.

**Comment by dmoKruso** [comment]
Ok already found it here... https://github.com/DavidWells/analytics/blob/master/packages/analytics/CHANGELOG.md

**Comment by Primajin** [comment]
I ran into the same thing - do you think it might make sense to make the individual changelogs more prominent and link them maybe somehow in the root readme or have a changelog.md that then points to the ones further down? 🤔 🤷🏻 
cc: @DavidWells 

Happy to open an MR if you agree
