### ISSUE TITLE
@analytics/google-analytics in node.js?

### ISSUE THREAD

**Issue by hodlerhacks** [DavidWells/analytics#316]
The @analytics/google-analytics documentation says the plugin works in the browser. I was wondering if I can use it in node.js (server-side) as well. That's how I've used the v3 plugin so far, and it's been working great. But I'm not getting it to work with v4.

The following code does trigger events in GA3, but not in GA4:

```
const { Analytics } = require('analytics');
const googleAnalyticsV3Plugin = require('@analytics/google-analytics-v3').default;
const googleAnalyticsPlugin = require('@analytics/google-analytics').default;

const analytics = Analytics({
    app: 'app-name',
    plugins: [
        googleAnalyticsV3Plugin({
            trackingId: 'UA-xxxxxxx-1',
        }),
        googleAnalyticsPlugin({
            measurementIds: ['G-xxxxxxx'],
        })
    ]
});

sendAnalytics();

function sendAnalytics() {
    analytics.page({
        title: 'App Server',
        href: 'https://app-domain.com',
        path: `/${some-variable}`,
    });
}
```

I've checked the network requests coming from node.js and I only see v3 requests. No v4 requests are being sent.

Am I doing something wrong, or is the v4 plugin indeed only supported in the browser?

**Comment by DavidWells** [comment]
GA4 doesn't work in the server.

The implementation is empty right now https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-google-analytics/src/node.js#L2

There is probably a way to do it with manual calls to ga4 but I havent see any serverside implementation of the "new" (completely different) version of google analytics v4

**Comment by hodlerhacks** [comment]
Thanks for your response. I tried to find an alternative way of implementing this, but failed so far. Hopefully, GA4 will work server-side eventually as well.

**Comment by hmiguim** [comment]
Will there be any plan to implement it?

**Comment by jmaferreira** [comment]
I have the same question.
