### ISSUE TITLE
Missing Project Licence?

### ISSUE THREAD

**Issue by nickcoury** [DavidWells/analytics#32]
The `CONTRIBUTING.md` file suggests this project is licensed under MIT, but references a `LICENSE` file that doesn't exist.  `package.json` also doesn't specify the license, nor could I find an explicit license anywhere in the docs.

Am I missing it somewhere, was it just missed, or is the lack of explicit license intentional? Project looks great!

**Comment by DavidWells** [comment]
Apologies for the radio silence. Its been a crazy couple of weeks 😅

The project is MIT licensed! Thanks for bringing this to my attention
