### ISSUE TITLE
Should we merge the plugins from https://github.com/ian/analytics into here?

### ISSUE THREAD

**Issue by ian** [DavidWells/analytics#326]
I have a separate plugin repo that adds the following services. Wondering if we should just merge them all into a single repo?

- [Plausible](packages/plausible)
- [Logrocket](packages/logrocket)
- [Indicative](packages/indicative)
- [Reddit](packages/reddit)
- [Splitbee](packages/splitbee)

**Comment by DavidWells** [comment]
Hey @ian 

Yeah we could do that if you wish!

Thanks again for making those plugins. Cool to see 😃
