### ISSUE TITLE
TypeError in gtm plugin: undefined is not an object

### ISSUE THREAD

**Issue by zobzn** [DavidWells/analytics#33]
I have no idea why do I continue to get errors 'TypeError: undefined is not an object (evaluating 'n[t].src.match')'.
Example of report in bugsnag:
https://i.imgur.com/cLfm60Y.png
https://i.imgur.com/H2pgIDn.png
It refers to this lines in source code:
```
  const scripts = document.querySelectorAll('script[src]')
  return !!Object.keys(scripts).filter(key => scripts[key].src.match(regex)).length
```
I can't even imagine when `scripts[key].src` in these lines could be undefined.
Anyway, we can replace `scripts[key].src.match` with `(scripts[key].src || '').match`.

**Comment by zobzn** [comment]
At least I got this error reported in:
- Mobile safari 8.0.0
- Mobile safari 9.0.0
- Mobile safari 9.3.5
- Chrome 49.0.2623
- Chrome 78.0.3904
- Chrome 79.0.3945
- Opera 66.0.3515

I personally can't reproduce the error.

**Comment by DavidWells** [comment]
Sounds like mobile browsers don't like/understand `document.querySelectorAll('script[src]')`

I'm adding the conditional here https://github.com/DavidWells/analytics/commit/8ce2852968cad831a74827e5aeca2de7c3f2361e

**Comment by DavidWells** [comment]
Published to `@analytics/google-tag-manager@0.2.3`

https://github.com/DavidWells/analytics/releases/tag/%40analytics%2Fgoogle-tag-manager%400.2.3

Let me know if that doesn't fix it 😃

**Comment by zobzn** [comment]
Apparently not only mobile browsers (detected also in different versions of chrome and opera on windows xp/7/10).

One more idea. Is it possible that `scripts[key].getAttribute('src')` can produce different result compared to `scripts[key].src` ?

**Comment by zobzn** [comment]
Thanks. I’ll write later whether this change will solve the issue.

**Comment by zobzn** [comment]
So far so good.
