### ISSUE TITLE
Collect Referrer

### ISSUE THREAD

**Issue by doublejosh** [DavidWells/analytics#330]
The `analytics-plugin-original-source` plugin should stash the `document.referrer` ...an important piece of a user's origin source.

**Comment by DavidWells** [comment]
Oh yeah for sure. I made a bunch of updates to this in a utility library https://github.com/DavidWells/analytics/tree/master/packages/analytics-util-visitor-source. Demo here https://utils-visitor-source.netlify.app/

You can use that.

Need to update `analytics-plugin-original-source` to use this newer package.
