### ISSUE TITLE
I can't run script google analytics only in brave browser

### ISSUE THREAD

**Issue by domlimited** [DavidWells/analytics#333]
https://user-images.githubusercontent.com/49817540/199138086-4eea0f7d-ce21-4edf-9c1c-8e69382a9d5e.png

**Comment by danestves** [comment]
Brave block analytics scripts from any source, so, this is a normal behavior 👀

**Comment by DavidWells** [comment]
Yeah brave is very over zealous at blocking analytics. You will probably need to use the `customScriptSrc` fields and self host files.

Also use https://getanalytics.io/plugins/do-not-track/ etc to track folks who opt in
