### ISSUE TITLE
Nuxt 3 Event with redirection not fired

### ISSUE THREAD

**Issue by agracia-foticos** [DavidWells/analytics#339]
If I launch a track event and then redirect to another page, the event does not fire

- Operating System: `Linux`
- Node Version:     `v18.11.0`
- Nuxt Version:     `3.0.0-rc.13`
- Nitro Version:    `0.6.1`
- Package Manager:  `npm@8.19.2`
- Builder:          `vite`
- User Config:      `srcDir`, `modules`, `compilerOptions`, `vue`, `vite`, `telemetry`, `algolia`, `head`, `auth`, `css`, `build`, `runtimeConfig`
- Runtime Modules:  `genesis-design-system/nuxt`, `@nuxtjs/tailwindcss@6.1.3`, `@nuxtjs/algolia@1.1.4`, `@nuxtjs-alt/auth@2.0.30`, `@nuxtjs-alt/http@1.4.2`, `@nuxtjs/device@3.0.0`, `@nuxtjs/partytown@1.2.2`, `unplugin-icons/nuxt`, `@pinia/nuxt@0.4.3`, `@nuxtjs/i18n@8.0.0-beta.3`
- Build Modules:    `-`

I am checking the debugger, and if I comment the navigateTo line the event is fired correctly, however if it is redirected it is not fired correctly

`await useNuxtApp().$analytics_track('Product Added', {
			cart_id: cart.cart_id,
		})

		await navigateTo('/cart')`

**Comment by DavidWells** [comment]
You probably need to redirect in the track callback

```js
analytics.track('Product Added', {
  cart_id: cart.cart_id,
}, () => {
  // callback 
  navigateTo('/cart')
})
```

IDK how your redirects work and if they are in SPA or not.
