### ISSUE TITLE
Make redux integration optional

### ISSUE THREAD

**Issue by eugene-manuilov** [DavidWells/analytics#34]
Hello,

Are there any plans to remove redux from the core package? It increases the final bundle size, but it is needed only for development mode. Pehaps you can extract it into a separate package?

**Comment by DavidWells** [comment]
Interesting idea, I thought about this as well.

It would be possible to shrink the package a little bit if redux was stripped down & inlined. Mainly removing larger redux error messages & playing a little "code golf"

When this was originally designed redux was much more "hot" as a state management library & the idea was redux would act like a peer dependency & its size wouldn't matter. (2.4kb gzipped) 

Redux drives the plugin architecture right now & everything is event driven inside analytics.

The other reason for redux was the out of the box debugging dev tooling support for time travel debugging etc. 

Will need to sit & think about this one 😃

**Comment by DavidWells** [comment]
This is fixed as of https://github.com/DavidWells/analytics/pull/39 

We will see how it goes. So far so good. Trimmed down from kbs 😃

Thanks for opening the issue!
