### ISSUE TITLE
Internal state isn't update after pageStart dispatch

### ISSUE THREAD

**Issue by Julienng** [DavidWells/analytics#35]
Hi 👋,

First, I hope everything is ok for you by the current times.

I would love to use your library but, I do have a problem when invoking `page()` with `react-router-dom`.

I made a [codesandbox](https://codesandbox.io/s/react-router-with-analytics-gmte8?file=/src/App.js) to illustrate my problem.

When I navigate between page `A`, `B`, `C`. React-router change the page URI correctly but internal state of analytics seems to be unchanged.

---

I tried first with `history` with the `listen` function then with a `useEffect()` inside my page components.

The page event is correctly dispatched but the reducer didn't update the URL and stuff because it assumes dispatched data is under `action.data`.

```js
export default function page(state = initialState, action) {
  switch (action.type) {
    case EVENTS.page:
      return Object.assign({}, state, action.data)
    default:
      return state
  }
}
```

But dispatch look like that : 

```js
store.dispatch({
  type: EVENTS.pageStart,
  properties: getPageData(d),
  options: opts,
  userId: getUserProp(ID, instance, d),
  anonymousId: getUserProp(ANONID, instance, d),
  meta: {
    timestamp: timestamp(),
    callback: resolvePromise(resolve, getCallback(data, options, callback))
  },
})
```

I think I'm missing something about the current behavior and I would love a bit of help to figure out 😊

**Comment by Julienng** [comment]
Ok, so I changed the reducer action from `action.data` to `action.properties` locally and it seems to resolve the issue.

If the solution is ok for you, I can make a PR 😃.

**Comment by DavidWells** [comment]
Hey @Julienng thanks for the report!

I played around with the sandbox as well and saw what you mean. 

Inside the plugins `page` calls there is the correct page information https://codesandbox.io/s/react-router-with-analytics-7m8ot?file=/src/tracking.js:192-378 but that getState call is incorrect like you mention.

A PR would be awesome for this! Many thanks!

**Comment by Julienng** [comment]
I make the PR!

Analytics is really cool, thank you for your work 😊
