### ISSUE TITLE
Plugin state is unpredictable

### ISSUE THREAD

**Issue by ccook10-chwy** [DavidWells/analytics#356]
Once analytics in instantiated, plugin enabled state is fluid and unpredictable.

In my use case, I want my custom plugin to control its own enabled status based on custom logic. The application will always include it but it will only be enabled for specific conditions. I've experimented with various strategies (calling instance.plugins.disable('my-plugin') during different events) but have come to the conclusion that the plugin will need to manage its own state internally, which is unexpected. Please refer to my test script.

```JavaScript
      function callback() {
        const ts = new Date().toISOString();
        window.selfDisabler.loaded = true;
        console.log(`Disable resolved at ${ts}`);
      }

      function pluginShouldNotBeEnabled() {
        // This plugin wants to own responsibility
        // for its enabled status rather than make
        // the application responsible. This function
        // could be used to signal based on user-agent,
        // for example. Disabled for all here.
        return true;
      }

      const myConfig = { updating: false };
      function selfDisabler() {
        return {
          name: 'self-disabler',
          initialize: ({ config, instance }) => {
            // Placing this in bootstrap or initializeStart
            // results in unpredictable result at page/track
            window.selfDisabler.loaded = false;
            if (pluginShouldNotBeEnabled()) {
              const ts = new Date().toISOString();
              console.log(`Disabling plugin at ${ts}`);
              instance.plugins.disable('self-disabler', callback);
            } else {
              window.selfDisabler.loaded = true;
            }
          },
          page: ({ instance, payload }) => {
            // We don't expect this to get called when plugin
            // is disabled, but it is called

            const state = instance.getState('plugins.self-disabler.enabled');
            const ts = new Date().toISOString();
            console.log(`page: enabled=${state} at ${ts}`);
            // Above prints "page: enabled=false"

            if (instance.getState('plugins.self-disabler.enabled')) {
              console.log(`self-disabler: page ${JSON.stringify(payload)}`);
              // Above does not print, but we shouldn't have to
              // check if we are enabled?!?
            }
          },
          loaded: () => {
            return !!window.selfDisabler.loaded;
          },
        };
      }
      const Analytics = _analytics.init({
        app: 'plugin-tester',
        version: 100,
        plugins: [selfDisabler()],
      });

      Analytics.page();
```

I am guessing that queued page/track/etc calls are added based on the plugin state when they happen and that when they are processed, plugin state is not a factor so that's why the page event in my example above is getting called even though the enabled state is false when it is called.

**Comment by DavidWells** [comment]
Sounds like a race condition. The page call is already queued by the time your logic is run.

Put analytics.page inside a analytics.ready fn this might solve your issue.

**Comment by DavidWells** [comment]
You can also start plugins in a disabled state with disabled: true as a config value

**Comment by ccook10-chwy** [comment]
The [documentation](https://getanalytics.io/conditional-loading/#disabling-initial-loading) specifies to use `enabled: false` to disable initial loading. Either way, if the plugin is loaded disabled then it will never, as far as I can tell, be initialized so would never have an opportunity to "enable" itself as I intend. 

To re-iterate, I want the plugin to either disable or enable itself based on browser conditions.

**Comment by ccook10-chwy** [comment]
I have worked around my issue as follows.

```Javascript
function pluginShouldNotBeEnabled() {
  return true;
}

function selfDisabler() {
  if (pluginShouldNotBeEnabled()) {
    return { name: 'self-disabler' }
  }

  return {
    name: 'self-disabler',
    // ....
  }
}
```
