### ISSUE TITLE
This package is now creating issues with react 18 as it's unmaintained.

### ISSUE THREAD

**Issue by tebayoso** [DavidWells/analytics#360]
https://github.com/DavidWells/analytics/blob/8af9ec407e1f4bd989c7b48de6d8850a512e4fcd/packages/use-analytics/package.json#L27

**Comment by DavidWells** [comment]
What issues?

**Comment by tebayoso** [comment]
React 18 projects warns that the peer dependency is not present, and will never be as the package is unmaintained now.

**Comment by danestves** [comment]
Can you share the warn? I'm using react@18 and didn't get any warn

**Comment by niicojs** [comment]
The issue seems to be with `mini-create-react-context` which is deprecated.

**Comment by jasonraimondi** [comment]
Here is a screen shot of the warning I am getting when using react 18.

<img width="684" alt=" 2023-03-17 at 12 16 09 PM" src="https://user-images.githubusercontent.com/5787967/225960361-b7b7d047-507e-461e-ba4b-9a7cc9d31bca.png">

**Comment by CGeorges** [comment]
Maybe this issue can be closed since it was fixed here ?https://github.com/DavidWells/analytics/commit/83e21310c007b075dcfdbbb65bd65d5959246b0d
