### ISSUE TITLE
Google Analytics - Custom Dimensions

### ISSUE THREAD

**Issue by tammaroivan** [DavidWells/analytics#37]
Hello everyone 👋 

Is there any way to create a Custom dimension with `@analytics/google-analytics` plugin? I didn't find any information about that in the documentation.

Thank you

**Comment by DavidWells** [comment]
Hey @tammaroivan 

Custom dimensions were on my list of this to do... 😃

I went ahead and added them: https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-google-analytics/src/browser.js#L11

I need to clean up the docs & then I can release a new version for ya.

In the newer version, once released, you can define `customDimensions` option and map to your google analytics custom dimensions.

Here is an example:

```js
import Analytics from 'analytics'
import googleAnalytics from '@analytics/google-analytics'

/* initialize analytics and load plugins */
const analytics = Analytics({
  app: 'awesome-app',
  plugins: [
    googleAnalytics({
      trackingId: 'UA-1223141231',
      // Map your dimensions here
      customDimensions: {
        baz: 'dimension1',
        foo: 'dimension2',
        flam: 'dimension3',
      },
    }),
  ]
})

// Tracking example with mappings
analytics.track('buttonClicked', {
   baz: 'hello',
   foo: 'cool'
})
/* This tracking call payload maps to:
{
  dimension1: 'hello', ===> baz is mapped to dimension1
  dimension2: 'cool'   ===> foo is mapped to dimension1
}

Under the hood this sets the custom dimensions in GA:

ga('set', {  dimension1: 'hello', dimension2: 'cool' }).     */

// Mapping works with identify too
analytics.identify('user123', {
   flam: 'wow'
})
/* This identify call payload maps to:
{
  dimension3: 'wow', ===> flam is mapped to dimension3
}
a.k.a ga('set', {  dimension3: 'wow' }). 
*/
```

---

Out of curiosity, what are you tracking with custom dimensions? Also, are you using custom metrics at all? Thanks!

**Comment by tammaroivan** [comment]
Thank you so much for that! Waiting for that release.

I'm dealing with a specific problem. I need reports associated to the user id, I'm identifying the user with `analytics.identify` but Google Analytics really doesn't allow you to do so much else than "User Explorer" (or I couldn't find it). 

One basic example: I'm saving a specific event and I would like to know which user does this event more times. I couldn't find how to do this with the user id feature but yes with a custom dimension.

I'm not using custom metrics for now, but I'm just starting this project in my company and it will get bigger in the near future.

What do you think? Custom dimension is a good approach for this? Or can I do this with the user id feature?

Thanks!

**Comment by DavidWells** [comment]
Alrighty! `@analytics/google-analytics@0.3.0` is published with custom dimension support.

Thanks again for reaching out & using the package! 😃

As for which custom dimensions to track, I've always liked Simo's https://www.simoahava.com/analytics/13-useful-custom-dimensions-for-google-analytics/ list.

**Comment by tammaroivan** [comment]
Great! I'll try it today.

Thank you for the article 🙂

**Comment by omarciovsena** [comment]
am i doing something wrong?

I'm not able to load the values sent to customDimensions into Google Analytics

```
import googleAnalytics from '@analytics/google-analytics'
import Analytics from 'analytics'

const analytics = Analytics({
  app: 'app',
  version: 100,
  plugins: [
    googleAnalytics({
      trackingId: process.env.GA_TRACKING_ID,
      customDimensions: {
        feature: 'dimension1',
        subfeature: 'dimension2',
        version: 'dimension3',
        chapter: 'dimension4',
        verse: 'dimension5',
        ip: 'dimension6',
        isHowToUse: 'dimension7'
      }
    })
  ]
})
```

```
await analytics.track('request', {
   feature: 'verses',
   subfeature: 'search'
})
```

Using the default properties (action, category and label) it worked.

In Google Analytics:

![Captura de Tela 2020-06-12 às 17 49 49](https://user-images.githubusercontent.com/3450717/84545175-22cb9400-acd5-11ea-8a30-a8b91a67ce84.png)

![Captura de Tela 2020-06-12 às 17 45 46](https://user-images.githubusercontent.com/3450717/84544895-9d47e400-acd4-11ea-85cf-de2d9cf496c6.png)
![Captura de Tela 2020-06-12 às 17 45 52](https://user-images.githubusercontent.com/3450717/84544916-a46ef200-acd4-11ea-8dcf-946d7bdad583.png)

**Comment by DavidWells** [comment]
Hey @marciovsena 

That looks correct as per the docs https://getanalytics.io/plugins/google-analytics/#using-ga-custom-dimensions

Do you have a live project/link I can checkout? 

`setCustomDimensions` should be getting called here https://github.com/DavidWells/analytics/blob/8b44ac96fd1a3622fd08b58693c2008b8d9dc248/packages/analytics-plugin-google-analytics/src/browser.js#L255 which sets the dimensions before the tracking event is called https://github.com/DavidWells/analytics/blob/8b44ac96fd1a3622fd08b58693c2008b8d9dc248/packages/analytics-plugin-google-analytics/src/browser.js#L339

**Comment by omarciovsena** [comment]
@DavidWells Yes, I am apparently doing as described in the documentation.

Link of the PR with the implementation:

- https://github.com/marciovsena/bibleapi/pull/121
    - https://github.com/marciovsena/bibleapi/pull/121/files#diff-fc66d847b10744ac04e9854460da2f18

Application Staging Link:

- https://bibleapi-stg.herokuapp.com

I was unable to add your `hello@davi...` email to the google analytics staging account.

How to test:

- Visit https://bibleapi-stg.herokuapp.com/en
- Go to the `How To Use` section
- Search for:
    - `verses/nvi/sl/21`
    - `verses/nvi/sl/22`
    - `verses/nvi/sl/23`
    - `versions/nvi/sl/24`

Thank you

**Comment by brandonbronisz** [comment]
To anyone else that was having this issue, i had to manually pull the release. Perhaps a release for this wasn't published. 

Doing a fresh npm install was pulling 0.2.2
