### ISSUE TITLE
google-tag-manager is broken since 0.5.3

### ISSUE THREAD

**Issue by absorbb** [DavidWells/analytics#376]
Hi!
this commit https://github.com/DavidWells/analytics/commit/7eb96834b9d3fec8f06ebda72bd04e1986018e96
breaks google-tag-manager.
line 54: `scriptSrc` is not provided as a second argument

**Comment by DavidWells** [comment]
Fixed via `@analytics/google-tag-manager@0.5.4` 

Thank you for the report. Looks like regression slipped in from a PR
