### ISSUE TITLE
h is not defined

### ISSUE THREAD

**Issue by grumpyoldman-io** [DavidWells/analytics#381]
Hey there, in the latest version of use-analytics Im getting the following error:

> ReferenceError: h is not defined

looking at the source files in the release, you can clearly see it is adding a "h( )" wrapper, but h is not defined anywhere. Im guessing there is something going on in the build process.

<img width="844" alt="Screenshot 2023-06-07 at 15 34 32" src="https://github.com/DavidWells/analytics/assets/5748147/eb7e2307-d6d6-4148-b30b-a448874c4a56">

**Comment by ChristopherTrimboli** [comment]
also an issue for me on `1.0.0`

**Comment by erisnuts** [comment]
Same for me.
I was have to rollback to v0.0.5

**Comment by zamson** [comment]
Also having this issue

**Comment by vtrphan** [comment]
i'm having this issue too. Anyone has a workaround?

**Comment by grumpyoldman-io** [comment]
@vtrphan my current workaround is either falling back to an older version or simply rolling your own useAnalytics (it is a very think wrapper)

**Comment by grumpyoldman-io** [comment]
I've opened a PR that should fix the issue https://github.com/DavidWells/analytics/pull/383

**Comment by DavidWells** [comment]
released via use-analytics@1.1.0

Thanks for report and fix ❤️

**Comment by grumpyoldman-io** [comment]
Confirmed it works@1.1.0, I was actually also looking at bringing types to use-analytics but it was a bit un-intuitive where I could get typings from as the core package only exports types at build. Do you have any recommendation? Happy to open a PR.

**Comment by DavidWells** [comment]
@grumpyoldman-io all types should be in jsdoc format. I think microbundle spits them out if I remember correctly

**Comment by grumpyoldman-io** [comment]
@DavidWells just wondering if you made a conscious decision _not_ to write the package in Typescript, and if so why. I'd rather convert the package to Typescript than to extract types from JSDoc, but that only makes sense if you (as the maintainer) is in agreement. If the reasoning makes sense I'll go for JSDoc (if I open the PR)
