### ISSUE TITLE
https://unpkg.com/analytics@0.8.7/dist/analytics.min.js return 404 

### ISSUE THREAD

**Issue by grozwalker** [DavidWells/analytics#382]
Hello. 

I install package as script tag `<script src="https://unpkg.com/analytics/dist/analytics.min.js"></script>` but when browser try to load `https://unpkg.com/analytics/dist/analytics.min.j` server return 302 response code and redirect to `https://unpkg.com/analytics@0.8.7/dist/analytics.min.js` wich not found

<img width="630" alt="image" src="https://github.com/DavidWells/analytics/assets/16976296/1ded37dc-1829-4fc0-9ce8-e8658e7ec907">

Can you tell me, how can I fix this error? 

Thank you!

**Comment by DavidWells** [comment]
Hmmm minified version not published. Will need to fix build.

You can use https://unpkg.com/browse/analytics@0.8.7/dist/analytics.js for now but its recommended you `npm install` this package

**Comment by DavidWells** [comment]
Fixed https://unpkg.com/browse/analytics@0.8.9/dist/analytics.min.js
