### ISSUE TITLE
plugin request: PostHog

### ISSUE THREAD

**Issue by alessandro-hc** [DavidWells/analytics#394]
would be great to add support for this.

**Comment by WarreH** [comment]
Hi there, a community plugin is available for PostHog. Please check under  [Community Plugins](https://github.com/DavidWells/analytics#community-plugins) or you can find it on [npm](https://www.npmjs.com/package/@metro-fs/analytics-plugin-posthog).

**Comment by abhishekpatel946** [comment]
I will add the `PostHog` and `Facebook Pixel` plugin support. 
@alessandro-hc Working on it.

**Comment by abhishekpatel946** [comment]
Hey @WarreH I created a gist  on PostHog, but not sure how to integrate as a plugin. 
Can someone help me here.
https://gist.github.com/abhishekpatel946/f671edc2640be436a1ac1744806c4fab

**Comment by DavidWells** [comment]
See plugin here https://www.npmjs.com/package/@metro-fs/analytics-plugin-posthog
