### ISSUE TITLE
Plugin request: Server support for goSquared

### ISSUE THREAD

**Issue by chrisdrackett** [DavidWells/analytics#40]

**Comment by chrisdrackett** [comment]
@DavidWells I'm happy to take this on, but wanted to check if there is a reason that https://github.com/gosquared/node-gosquared isn't already used for a server side version of goSquared

**Comment by DavidWells** [comment]
I just never got around to implementing the node side of that piece. 

By all means, go for it! 😃

The [segment](https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-segment/src/node.js) or [google analytics](https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-google-analytics/src/node.js) serverside plugins are some examples. 

This `process.browser` pattern below allows for tree shaking out the node dep when building the browser version. 

```js
let universalAnalytics
if (!process.browser) {
  universalAnalytics = require('universal-analytics')
}
```

**Comment by DavidWells** [comment]
A consolidated issue has been created at https://github.com/DavidWells/analytics/issues/153 for plugin requests.

Feel free to comment/reopen this thread if you have begun active development on this plugin.
