### ISSUE TITLE
Angular Failed to Compile

### ISSUE THREAD

**Issue by theelement115** [DavidWells/analytics#402]
I am integrating google analytics with an angular project but i am unable to import the @analytics/google-analytics package.

But when I run ng serve i get this error.

Error: export 'googleAnalytics' (imported as 'googleAnalytics') was not found in '@analytics/google-analytics' (possible exports: default, init)

✖ Failed to compile.

this is my code:

    import {Analytics} from 'analytics'
    import {googleAnalytics} from '@analytics/google-analytics'
    
    
    export class ProductViewComponent {
    
      ...
      analytics = Analytics({
          app: 'Zaito web',
          plugins: [
            googleAnalytics({
              measurementIds: ['G-*********']
            })
          ]
        })

**Comment by DavidWells** [comment]
Change import to

```
import googleAnalytics from '@analytics/google-analytics'
```
