### ISSUE TITLE
Plugin Request: AWS Personalize

### ISSUE THREAD

**Issue by khalibloo** [DavidWells/analytics#404]
AWS Personalize is a product/content recommendation engine. It has a user interaction tracking component to it. Not sure why they didn't just integrate it with AWS Pinpoint analytics.

It uses the PutEvents operation in their SDK to report user interaction events as shown in this example https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/javascriptv3/example_code/personalize/src/personalize_putEvents.js. Here, some additional context https://docs.aws.amazon.com/personalize/latest/dg/putevents-example.html

They officially recommend to use the Amplify SDK to report the events, but in typical AWS fashion, Amplify forces you to use Cognito and a bunch of other AWS stuff. Amplify also adds a ton of bloat to the application code, and requires one to manually push changes over to it, like it's another Git. In summary, a plugin for Personalize would save a ton of pain.

**Comment by DavidWells** [comment]
Hey there @khalibloo  

Thanks for the plugin request.

I won't have the bandwidth to write/maintain a plugin for indicative.

That said, it's pretty easy to create a plugin for any provider. Here are the docs https://getanalytics.io/plugins/writing-plugins/#1-provider-plugins

It's really a matter of mapping their calls, to the analytics primitives `page`, `track`, `identity` etc

```js
export default function providerPluginExample(userConfig) {
  // return object for analytics to use
  return {
    /* All plugins require a name */
    name: 'my-example-plugin',
    /* Everything else below this is optional depending on your plugin requirements */
    config: {
      whatEver: userConfig.whatEver,
      elseYouNeed: userConfig.elseYouNeed
    },
    initialize: ({ config }) => {
      // load provider script to page
    },
    page: ({ payload }) => {
      // call provider specific page tracking
    },
    track: ({ payload }) => {
      // call provider specific event tracking
    },
    identify: ({ payload }) => {
      // call provider specific user identify method
    },
    loaded: () => {
      // return boolean so analytics knows when it can send data to third party
      return !!window.myPluginLoaded
    }
  }
}
```

Let me know if you have any questions on this.

Merging this into https://github.com/DavidWells/analytics/issues/153
