### ISSUE TITLE
Plugin Request - Server-side Implementation - Google Analytics

### ISSUE THREAD

**Issue by matt-greatminds** [DavidWells/analytics#417]
The current Google Analytics plugin does not support server-side eventing and I'd like to request that enhancement.

My company already uses GetAnalytics for the front-end and would like to use the same library to fire events from the server for important business metrics that cannot be reliably captured from the browser.

[Here is link from the Google Analytics Docs](https://developers.google.com/analytics/devguides/collection/protocol/ga4) outlining server-to-server events.

@DavidWells

**Comment by DavidWells** [comment]
I started to build this over at https://github.com/DavidWells/google-tag-manager-serverless but put on the shelf for now.

GA keeps throttling their product lines and making sweeping breaking changes. Kind of hard to keep up with their "product direction" 

It should be possible though as this lib runs in node.js

I moved this to https://github.com/DavidWells/analytics/issues/153

**Comment by matt-greatminds** [comment]
@DavidWells Thanks for the links.  After reviewing them I noticed that the solution you were exploring was related to GTM instead of GA4.

What we are hoping for is to send events directly from our backend for things like, "user assessment record was created in assessment table of blah blah blah database". This will allow us to not have client code sending events for certain actions because the more reliable server event has that covered.

I was hoping that by using the [Measurement Protocol](https://developers.google.com/analytics/devguides/collection/protocol/ga4#full_server-to-server) would be a way to add server-side support for GA4.

Does the additional detail provided above, change your approach to this ticket?

**Comment by ianlotinsky-gm** [comment]
@DavidWells Please see your email inbox for a message from Matt about our interest in paying for this GA4 native integration. Thanks!
