### ISSUE TITLE
OneTrust integration

### ISSUE THREAD

**Issue by alissonpadua** [DavidWells/analytics#422]
Hello everybody! Has anyone ever done the integration with oneTrust ? I struggling to find the best approach =)

**Comment by DavidWells** [comment]
Haven't heard of onetrust.

You want to find the corresponding SDK methods that map down to `page`, `track` and `identify` and create a plugin https://getanalytics.io/plugins/writing-plugins/#1-provider-plugins

**Comment by DavidWells** [comment]
Moving to https://github.com/DavidWells/analytics/issues/153

Let me know if you have questions about creating plugins
