### ISSUE TITLE
Unloading Plugins based on Path

### ISSUE THREAD

**Issue by markojak** [DavidWells/analytics#430]
Hi All,

Does anyone know if this wrapper allows for the ability to unload and then load a separate Segment.com writeKey based on the router path? I can't find any documentation on unloading plugins

What we're trying to do is exclude Segment.com from loading marketing (google ads, Bing etc.) on App paths. 
What makes this hard to do with NextJS is that it will persist the script across marketing/app pages and you cannot do a analytics.load("") update call in analytics.js because segment re-writes these functions (I think)

**Comment by DavidWells** [comment]
You can conditionally enable/disable stuff https://getanalytics.io/conditional-loading/#enabling--disabling-plugins

```js
routerListenerThingie((route) => {
  if (route === 'foo') {
    analytics.plugins.disable(['segment'])
  }
})
```

Or perhaps you can initialize another analytics instance without those plugins and call that instances .page, .track etc.

**Comment by DavidWells** [comment]
Alternatively, you can load 2x segment instances and have one or the other disabled and toggle them on/off

It's an odd use case and you might run into trouble with how the segment code initializes with the script.
