### ISSUE TITLE
Contradicting types for `config.version`

### ISSUE THREAD

**Issue by jamesbeith** [DavidWells/analytics#435]
In the API reference docs, `config.version` is typed as a `string`.

https://github.com/DavidWells/analytics/blob/82216bfad172fa834b1b7beb030be4e41ed73ed9/site/main/source/api.md?plain=1#L31

However, the _Using in your app_ example docs on the homepage is using a `integer`.

https://github.com/DavidWells/analytics/blob/209e6fd8e3e33b61297cf0d41f69a3c94b9d89c2/site/main/source/index.mdx?plain=1#L67

**Comment by DavidWells** [comment]
Ah word. Good catch.

Should be `string|number`. Really it can be whatever you wish. Some like semver, some like dates, some like numbers

**Comment by DavidWells** [comment]
Published updated lib
