### ISSUE TITLE
Is there a need to wait for `analytics.ready` before making API calls?

### ISSUE THREAD

**Issue by jamesbeith** [DavidWells/analytics#440]
Mentioned in [this comment](https://github.com/DavidWells/analytics/issues/398#issuecomment-1729983361)

> To debug you gotta look at the DOM to verify that GA and Amplitude are loaded.

Is that saying that a plugin may still be loading and could miss/drop an `analytics.page()` or `analytics.track()` (and other API) calls?

Here's an example from the docs

```javascript
const analytics = Analytics({
  app: 'awesome-app',
  plugins: [
    googleAnalytics({
      measurementIds: ['G-abc123']
    })
  ]
})

/* Track a page view */
analytics.page()

/* Track a custom event */
analytics.track('cartCheckout', {
  item: 'pink socks',
  price: 20
})
```

Will those `page()` and `track()` calls always (eventually) make their way to Google Analytics? 

Is there ever a need to make sure the `analytics` client is ready before making those calls? For example

```javascript
const analytics = Analytics({ ... })

analytics.ready(() => {
    /* Track a page view */
    analytics.page()

    /* Track a custom event */
    analytics.track('cartCheckout', {
      item: 'pink socks',
      price: 20
    })
})
```

**Comment by DavidWells** [comment]
You don't have to wrap things in .ready if you don't want to.

Anything called before is queued in memory and the queue processes once the provider is loaded. If the provider never loads, the event will get dropped on hard page reload.

Depends on the provider really. Some analytic sinks libraries might decorate events with their own data/datetimes etc if you want this to be "accurate", it might make sense to wait until all providers or loaded (.ready) or checking analytics.getState().plugins then fire your tracking calls

**Comment by jamesbeith** [comment]
Thank you 🙏
