### ISSUE TITLE
Datawarehouse / Database Support

### ISSUE THREAD

**Issue by adeolaemmanuelmorren** [DavidWells/analytics#441]
Hi @DavidWells love the library. Is there any way to configure the library to send all the events into a database or into a data warehouse? 

And also is it possible to run the library in cloudfare edge workers?

**Comment by DavidWells** [comment]
Thanks.

You can send the data to wherever you wish via a plugin https://getanalytics.io/plugins/writing-plugins/#1-provider-plugins

The library runs anywhere javascript runs.
