### ISSUE TITLE
invalid ts type

### ISSUE THREAD

**Issue by iscekic** [DavidWells/analytics#443]
```ts
function analytics(config: {
      app?: string;
      version?: string & number;
      debug?: boolean;
      plugins?: AnalyticsPlugin[];
  }): AnalyticsInstance;
```
`string & number` should be `string | number`

**Comment by bergwerf** [comment]
Same issue, `string & number` evalutes to `undefined`, causing a type checking error in my project.

**Comment by DavidWells** [comment]
Should be fixed with 

 - @analytics/core@0.12.15
 - analytics@0.8.14
