### ISSUE TITLE
type definitions have invalid type annotations

### ISSUE THREAD

**Issue by trusktr** [DavidWells/analytics#445]
For example, the `init` function is seen to have a `string & number` type which TypeScript does not support, leading to the type definition resulting in `undefined`:

<img width="328" alt="Screenshot 2024-06-25 at 10 51 02 AM" src="https://github.com/DavidWells/analytics/assets/297678/608d757a-ca2d-4cdd-9ca6-7295a8711e9c">

Trying to use it results in an error:

<img width="710" alt="Screenshot 2024-06-25 at 10 55 26 AM" src="https://github.com/DavidWells/analytics/assets/297678/7cb6d263-bc4a-449a-a7ad-c04df9979c0b">
<img width="706" alt="Screenshot 2024-06-25 at 10 55 40 AM" src="https://github.com/DavidWells/analytics/assets/297678/7bba5854-19e8-4cc3-90c6-4ecabb0e0242">

Changing it to `string | number` will fix the type def.

**Comment by DavidWells** [comment]
Should be fixed with 

 - @analytics/core@0.12.15
 - analytics@0.8.14
