### ISSUE TITLE
Allow to set identify to null

### ISSUE THREAD

**Issue by mptasinski** [DavidWells/analytics#446]
Current implementation of [`analytics.identify()`](https://getanalytics.io/api/#analyticsidentify) does't allow to set userId back to null

The only way i manage to reset userId is with [`analytics.reset()`](https://getanalytics.io/api/#analyticsreset) but it clears annonymouseId and thats what i dont want.

if i can simply run `analytics.identify(null);` and it will set userId back to null it will be great

thank you

**Comment by DavidWells** [comment]
Probably not gonna change this in core

You can use the `storage` events https://getanalytics.io/lifecycle/#storage-events to prevent values from being removed or keep the id's in memory with `analytics.getState()' and use `analytics.setAnonymousId`
