### ISSUE TITLE
Issue setting up the project locally to contribute a plugin

### ISSUE THREAD

**Issue by aonawale** [DavidWells/analytics#449]
I am trying to create a new plugin following the contributing guide here https://github.com/aonawale/analytics/blob/master/CONTRIBUTING.md. I started by installing pnpm globally using `npm install -g pnpm` because it is the package manager used by the analytics project.

First issue
The `npm run setup` command failed while installing with this error `nan_callbacks.h:55:23: error: ‘AccessorSignature’ is not a member of ‘v8’ #942`. I managed to get the installation to complete by following the recommendation here https://github.com/nodejs/nan/issues/942#issuecomment-1816080121.

Second issue
After the `npm run setup` command ran successfully, I ran the next command `npm run build` the I got another error ` ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  analytics@0.8.14 prebuild: "npm run clean && npm run types"`

Node version: v20.11.0
NPM version: 10.2.4
PNPM version: 9.9.0

<img width="824" alt="Screenshot 2024-08-28 at 17 24 07" src="https://github.com/user-attachments/assets/21bc61d3-852b-476d-a780-503e083a5e4a">

**Comment by aonawale** [comment]
Running the `npm run build` command in a new terminal window fixed the second issue.

**Comment by DavidWells** [comment]
Hey there. Yeah there might be some weird stuff with the build in newer versions of node or pnpm 😅

Try running with node v16 and/or pnpm 8.7.6

Just tested this out with `v16.20.2` and builds work. (pnpm v8.7.6)

Haven't had time to debug dev deps and update the pipeline for newer versions of node/pnpm.
