### ISSUE TITLE
Is this library maintained?

### ISSUE THREAD

**Issue by jukkahuuskonen** [DavidWells/analytics#454]
ISSUE: Is this still maintained? Last release was 2 years ago.

**Comment by msantic** [comment]
https://www.npmjs.com/package/analytics?activeTab=versions

**Comment by DavidWells** [comment]
Yeah. The core is stable at this point.

There are probably third-party analytics providers that could use some updates. But I'm currently working on other things. 

You can write your own custom plugins pretty easily, see https://getanalytics.io/plugins/writing-plugins/ or the src code of any of the provider plugins for examples.
