### ISSUE TITLE
Support for multiple Google Analytics tracking codes

### ISSUE THREAD

**Issue by mikeahirsch** [DavidWells/analytics#47]
This could be solved by adding support for either multiple instances of the analytics object or adding support for duplicate google analytics plugins that each have a different tracking code.

**Comment by DavidWells** [comment]
Hey @mikeahirsch thanks for the issue!

Google analytics initialization code is here: https://github.com/DavidWells/analytics/blob/master/packages/analytics-plugin-google-analytics/src/browser.js#L153-L184

I think we would need to edit the `ga('create', 'UA-XXXXX-Y', 'auto')` call [per these docs](https://developers.google.com/analytics/devguides/collection/analyticsjs/creating-trackers#working_with_multiple_trackers)

**What is your use case for have 2 instances of google analytics loaded?**

**Comment by mikeahirsch** [comment]
@DavidWells I have some software that allows clients to add their own tracking code so they can get the same data sent to their property. I went ahead and just used analytics.js to do this but would love to accomplish the same thing with this library so we could support more analytics options than just Google Analytics.

**Comment by DavidWells** [comment]
This is a great idea and is now implemented 🎉

```
npm install @analytics/google-analytics@0.4.0
```

Docs on how to use over here https://getanalytics.io/plugins/google-analytics/#using-multiple-instances

**Comment by DavidWells** [comment]
Closing this issue. Let me know if you have any questions.

Here is an example of using 2 Google Analytics instances in an app.

```js
import Analytics from 'analytics'
import googleAnalytics from '@analytics/google-analytics'

// Normal google analytics instance
const instanceOne = googleAnalytics({
  trackingId: '123-xyz',
})

// Second google analytics instance with override for 'name' field of the plugin
const instanceTwo = {
  // initialize the 2nd instance with 'instanceName' field set
  ...googleAnalytics({
    trackingId: '567-abc',
    instanceName: 'two'
  }),
  // change 'name' plugin to avoid namespace collisions
  ...{
    name: 'google-analytics-two'
  }
}

/* Object.assign example
const instanceTwo = Object.assign({}, googleAnalytics({
    trackingId: '567-abc',
    instanceName: 'two'
  }), {
    name: 'google-analytics-two'
  }
}) */

const analytics = Analytics({
  app: 'awesome-app',
  plugins: [
    // Instance 1 of Google Analytics
    instanceOne,
    // Instance 2 of Google Analytics
    instanceTwo
  ]
})
```
