### ISSUE TITLE
Self host analytics.js

### ISSUE THREAD

**Issue by thilak-rao** [DavidWells/analytics#48]
https://github.com/DavidWells/analytics/blob/87459c32ebb46f245634869ef90393b0bdc26bf9/packages/analytics-plugin-google-analytics/src/browser.js#L163

I'd like to self-host a copy of analytics.js and serve it from my hostname. Would you accept a pull request, if I make it configurable? 

The default behavior would remain unchanged and I would like to add an optional configuration to be able to change the URL of analytics.js

PS: Thank you for creating this amazing project.

**Comment by thilak-rao** [comment]
Although Google [does not recommend](https://support.google.com/analytics/answer/1032389?hl=en) doing this, my main motivation for this feature request is to set a long Cache TTL using Nginx directives like this:

```nginx
server {
    location = /analytics.js {
        proxy_pass https://www.google-analytics.com;
        expires 30d;
    }
}
```

By default, the cache TTL is just 2h :(

**Comment by DavidWells** [comment]
Hey @xthilakx 

Great idea!

I went ahead and added a `customScriptSrc` option that you can point to your custom GA script that will send proxied requests to your own service.

Install `@analytics/google-analytics@0.4.0` and the option is there. 

Docs on how to use over here:

https://getanalytics.io/plugins/google-analytics/#custom-proxy-endpoint

Follow a tutorial like [this](https://www.freecodecamp.org/news/save-your-analytics-from-content-blockers-7ee08c6ec7ee/) to set up your proxy.

**Comment by DavidWells** [comment]
Closing this out. Let me know if you have any further questions!

```js
import Analytics from 'analytics'
import googleAnalytics from '@analytics/google-analytics'

const analytics = Analytics({
  app: 'awesome-app',
  plugins: [
    googleAnalytics({
      trackingId: '123-xyz',
      customScriptSrc: 'https://my-url.com/to-custom-ga.js'
    })
  ]
})
```
