### ISSUE TITLE
Google Tag Manager - Custom Dimensions

### ISSUE THREAD

**Issue by kevin-chheang** [DavidWells/analytics#53]
Hello,

I'm trying to use custom dimensions variables with `@analytics/google-tag-manager` plugin.
And this is what I did: 
```
const analytics = Analytics({
  app: 'App-Client',
  plugins: [
    googleTagManager({
      containerId: envHandler.GTM_ACCOUNT_ID
    })
  ]
})

analytics.page({
  'pageTitleCustomDimension': 'Homepage'
})
```

I did the settings in Google Analytics (I created the custom dimension) and also in Google Tag Manager (I created the dataLayer Variable and linked to the GA custom dimension).

But in GA, the result that I got is the default value of the dataLayer Variable from GTM.

The preview of GTM:
<img width="772" alt="Capture d’écran 2020-05-20 à 11 56 59" src="https://user-images.githubusercontent.com/58222349/82433103-406c5b80-9a91-11ea-8878-24b8b0ef0da3.png">

Every time, I use the page method, it send a Message event with the pushed data layer. It does not fire my Page View Tag.

Is there a documentation on how to use custom dimensions with `@analytics/google-tag-manager` ?

Thank you.

**Comment by DavidWells** [comment]
Hey @KCH-KENG 

Did you figure this one out?
