### ISSUE TITLE
Update Full Story src

### ISSUE THREAD

**Issue by LawJolla** [DavidWells/analytics#57]
Thanks for this amazing package and your hard work!  

I'd send a PR, but I'm out of town. 

FullStory changed their JS package src to: `edge.fullstory.com/s/fs.js`

See
https://help.fullstory.com/hc/en-us/articles/360041242094-FullStory-on-a-CDN

I'm getting a lot of "Full Story failed to load" errors with the current src.

If L40 reference below can be changed to `edge.fullstory.com/s/fs.js` for the next release, that'd be awesome!  Thanks again.

https://github.com/DavidWells/analytics/blob/27a70dfa44fde72baaddb0fe85b850a5d7b6212b/packages/analytics-plugin-fullstory/src/browser.js#L40

**Comment by DavidWells** [comment]
Hey @LawJolla 

We can update that.

Is the `edge.fullstory.com/s/fs.js` the same library or has the underlying API changed?

**Comment by LawJolla** [comment]
@DavidWells thanks!

Same library.  https://www.fullstory.com/s/fs.js redirects to edge.fullstory.com/s/fs.js

**Comment by DavidWells** [comment]
@LawJolla now published with `@analytics/fullstory@0.2.3` 🎉

Thanks for opening the issue!
