### ISSUE TITLE
Bundle Size Doc Improvements

### ISSUE THREAD

**Issue by thilak-rao** [DavidWells/analytics#63]
https://getanalytics.io/resources/faq/#how-much-bundle-size-will-this-add

**This page should probably mention:** 
- If the package is tree-shakeable (looks like it is). 
- I could not find redux as a peer dependency in the source code. Unsure how adding redux will save ~2.6kb)
- Does the final bundle size of ~11.2kb includes just ESM or both ESM and CJS?

**Comment by DavidWells** [comment]
It looks like a majority of folks are moving away from redux as state management tool 😅

So `redux` was inlined and shrank via code golf for some savings. 

The numbers I look at are from https://bundlephobia.com/result?p=analytics

**Comment by thilak-rao** [comment]
@DavidWells The numbers from bundlephobia is not indicative of real-life bundle bloat as the package includes ESM and CJS build, but in real-life app, you'd use one of the two.

**Comment by thilak-rao** [comment]
Treeshaking should make bundle size even smaller.

**Comment by DavidWells** [comment]
Redux was shrunk and inlined to save a little size.

Closing this issue for now.
