### ISSUE TITLE
Enable extra config for items such as `cookieFlags`

### ISSUE THREAD

**Issue by JeffBaumgardt** [DavidWells/analytics#67]
https://github.com/DavidWells/analytics/blob/2600a2a1e0d0bb1225329d8498daac8bdf489bcb/packages/analytics-plugin-google-analytics/src/browser.js#L74-L86

I'm working to resolve a current issue where the ga default cookie is not sent with the correct `SameSite` and `Secure` flags. In a normal setup you would do something like

```js
ga('create', 'UA-XXXXX-Y', {
  'cookieName': 'gaCookie',
  'cookieDomain': 'blog.example.co.uk',
  'cookieExpires': 60 * 60 * 24 * 28  // Time in seconds.
  'cookieUpdate': 'false',
  'cookieFlags': 'SameSite=None; Secure',
});
```

With Chrome 84, cookies will now be flagged with an issue in the console if they are not correctly set with the proper attributes. In a future version these cookies will be discarded.

For the short term could we add a extra config object to the plugin method
Something like,
```
googleAnalytics({trackingId: 'UA-12345678-1'}, {cookieFlags: 'SameSite=None; Secure'})
```

Then it would be easy to assign that to the `gaConfig` on line 86.

I'm happy to help where I can.

**Comment by JeffBaumgardt** [comment]
Additional context: https://www.chromium.org/updates/same-site

**Comment by DavidWells** [comment]
Hey, @JeffBaumgardt thanks for bringing this up! 

This is news to me. We can add an additional option for this.

https://www.simoahava.com/analytics/cookieflags-field-google-analytics/

> NOTE 25 March 2020: The feature isn’t yet officially released, and there might be additional features added to the functionality before it is officially documented. I will update this article with any updates, if necessary.

Feel free to submit a PR!

If you need this ASAP, you can achieve this by overriding the default `initialize` behavior like so

```js
import Analytics from 'analytics'
import googleAnalytics from '@analytics/google-analytics'

// Original GA
const originalPlugin = googleAnalytics({
  trackingId: 'UA-1234567'
})
// Customized GA until option added
const enhancedPlugin = Object.assign({}, originalPlugin, {
  initialize: () => {
    console.log('custom implementation of GA initialize https://bit.ly/3fd7pqw')
  }
})

/* initialize analytics and load plugins */
const analytics = Analytics({
  app: 'cool-apps',
  plugins: [
    enhancedPlugin,
  ]
})

export default analytics
```

**Comment by JeffBaumgardt** [comment]
I'm sure I won't be the only one who would like to use the additional options that google provides.

Before I submit a PR I would like your input.

I can think of the extra config being one of two ways.
1) Extra argument on the plugin `function googleAnalytics(pluginConfig = {}, cookieConfig = {})`
2) Enhance the pluginConfig with an additional cookieConfig object

The first would somewhat break the existing model of the plugins by adding an additional argument to just this one plugin.

```
const gaConfig = {
    cookieDomain: config.domain || 'auto',
    siteSpeedSampleRate: config.siteSpeedSampleRate || 1,
    sampleRate: config.sampleRate || 100,
    allowLinker: true,
    // useAmpClientId: config.useAmpClientId
    ...{cookieConfig},
}
```

or
```
const gaConfig = {
    cookieDomain: config.domain || 'auto',
    siteSpeedSampleRate: config.siteSpeedSampleRate || 1,
    sampleRate: config.sampleRate || 100,
    allowLinker: true,
    // useAmpClientId: config.useAmpClientId
    ...{config.cookieConfig},
}
```

Really the implementation is simple it's just the approach we want to take.
I personally would prefer option 2 because it won't impact any users, and won't add any additional api.

**Comment by DavidWells** [comment]
Option 2 sounds good to me. 😃
