### ISSUE TITLE
Revamp gatsby-plugin-analytics

### ISSUE THREAD

**Issue by alexluong** [DavidWells/analytics#68]
Hey there,

It seems like `gatsby-plugin-analytics` hasn't received much attention in a while. I'd love it if we can make use of new features from both Gatsby and Analytics since the last time it was built.

I think `gatsby-plugin-analytics` should help users initialize the Analytics component as well as `window.Anlytics = Analytics` and setting up `AnalyticsProvider` so users can use hook right away.

The way we can go about it is using Gatsby component shadowing feature. Suggested end user experience:

- `yarn add gatsby-plugin-analytics analytics use-analytics @analytics/whatever-plugin`
- in `gatsby-config.js`:

```js
module.exports = {
  plugins: ["gatsby-plugin-analytics"]
}
```

- configure plugins in `src/gatsby-plugin-analytics/analytics.js`

```js
import Analytics from 'analytics'
import googleAnalytics from '@analytics/google-analytics'

const analytics = Analytics({
  app: 'awesome-app',
  plugins: [
    googleAnalytics({
      trackingId: 'UA-1234567',
    })
  ]
})

export default analytics
```

- in component:

```jsx
import { useAnalytics } from 'use-analytics'

...

const { track } = useAnalytics()
track()
```

These are just some initial thoughts on what the future Gatsby plugin can do. Would love your ideas and feedback! I'd be happy to help out with this as well! Thanks for building a great suite of analytic-related libraries so far!

**Comment by DavidWells** [comment]
Hey @alexluong 

I like this idea!

Originally I wanted to allow folks to configure all analytics plugins in the gatsby config but the way they serialize stuff it didn't work out.

Is there a way we can pass the `analytics` instance into the gatsby context without exposing it to the `window`?

**Comment by alexluong** [comment]
> Is there a way we can pass the analytics instance into the gatsby context without exposing it to the window?

We certainly can. We can also make it an opt-in/out feature

```js
// gatsby-config.js

plugins: [
  {
    resolve: "gatsby-plugin-analytics",
    options: {
      enableGlobalAnalytics: true // default to false, or vice versa
    }
  }
]
```

**Comment by DavidWells** [comment]
Sounds good to me. 😃

**Comment by DavidWells** [comment]
Any updates on this one? 😎

**Comment by DavidWells** [comment]
Closing this for now. If someone wants to update the options PRs welcome!
