### ISSUE TITLE
Allow for better page tracking in segment

### ISSUE THREAD

**Issue by Carl-Meyer** [DavidWells/analytics#75]
Hi there

I was using angulartics2 as an analytics library before switching to analytics. We are sending our analytics to segement. 
I hoping to ask if there is a way to send through page data in a better format similarly to how it was when using angulartics2? 

Here is what I mean:
**Angulartics2**
<img width="1342" alt="Screenshot 2020-08-11 at 10 02 46" src="https://user-images.githubusercontent.com/34540449/89872877-e1af0d80-dbb9-11ea-9089-3e3a6fc2d3f2.png">

**analytics**
<img width="1344" alt="Screenshot 2020-08-11 at 10 03 01" src="https://user-images.githubusercontent.com/34540449/89872922-f2f81a00-dbb9-11ea-9169-02700f715371.png">

I like the fact that analytics sends the height and width as well. I have added the name field to the page track call myself which is working fine but when viewing it in the segment debugger it shows as `/recruiting/` instead of `Job Postings`

Thanks for the hard work :)

**Comment by DavidWells** [comment]
You can customize the payload of page views, identity calls, and tracking events with [custom plugins](https://getanalytics.io/plugins/writing-plugins/#2-custom-plugins)

For example, if you want all pageView calls to have something specific or keys removed you can use a plugin. Hook into the `pageStart` [lifecycle event](https://getanalytics.io/lifecycle/).

```js
import Analytics from 'analytics'
import segmentPlugin from '@analytics/segment'

function myCustomPageDataPlugin(userConfig = {}) {
  return {
    name: 'my-custom-page-plugin',
    config: Object.assign({}, userConfig),
    pageStart: ({ payload }) => {
      // Alter payload before it reached .page calls
      return Object.assign({}, payload, {
        addThis: 'hello',
        addThat: 'goodbye'
      })
    }
  }
}

/* initialize analytics and load plugins */
const analytics = Analytics({
  debug: true,
  app: 'yolo',
  plugins: [
    myCustomPageDataPlugin(),
    segmentPlugin({
      writeKey: 'xyz'
    })
  ]
})

analytics.page()
```

**Comment by Carl-Meyer** [comment]
Hi @DavidWells thank you for taking the time to reply. I will investigate to see if this will achieve the desired effect. I think I had issues altering the page call to be able to have Page(name, pageData) go through since the Page interface only allows for calling Page (page Data) but let me have a look and see what I can accomplish. Thanks again 👍

**Comment by DavidWells** [comment]
Hwy @Carl-Meyer any updates here?

**Comment by Carl-Meyer** [comment]
Hi @DavidWells seems like not having the page name param in the sentry preview isn't an issue for us so I didn't end up implementing your solution. Sorry, but thank you for the support.
