### ISSUE TITLE
Is there a way to fetch the existing instance of Analytics?

### ISSUE THREAD

**Issue by Carl-Meyer** [DavidWells/analytics#76]
Hi there

I am trying to initialise analytics using the segment plugin, but I am struggling to grab a reference to the created analytics and use it to call page, track and identify calls. 

Here is how I got it to work for me so far:
```
 public page(config: AnalyticsConfig, pageData: PageData) {

    analytics = Analytics({
      app: 'recruiting',
      plugins: [
        segmentPlugin({
          writeKey: config.writeKey
        })
      ]
    });

    analytics.page(pageData);
  }

  public identify(config: AnalyticsConfig, id: string, traits: any) {

    analytics = Analytics({
      app: 'recruiting',
      plugins: [
        segmentPlugin({
          writeKey: config.writeKey
        })
      ]
    });
    analytics.identify(id, traits);
  }

  public track(config: AnalyticsConfig, eventName: string, payload?: any) {


    analytics = Analytics({
      app: 'recruiting',
      plugins: [
        segmentPlugin({
          writeKey: config.writeKey
        })
      ]
    });
    analytics.track(eventName, payload);
  }
```
I feel that this isn't the best way of doing it as I have to pass through my write key and initialise Analytics every time I make a page, track or identify call. 

I am working in Angular 9 + typescript and not sure how to initialise Analytics once and then fetch a reference to the already created Analytics and use it.

**Comment by DavidWells** [comment]
Hey @Carl-Meyer 

You want to initialize analytics once in your app and import that analytics instance into where you want to use it.

See the examples folder https://github.com/DavidWells/analytics/tree/master/examples for more details

Here is react example https://github.com/DavidWells/analytics/blob/master/examples/react/src/index.js#L7

**Comment by Carl-Meyer** [comment]
@DavidWells thank you. I think I figured out a nice way of doing it. I am setting analytics to a global variable in my app.component.ts and then I use that variable throughout my project whenever I want to call analytics for example

```
// in app.component.ts 
GlobalVariables.analytics = Analytics({
      app: 'recruiting',
      plugins: [
        segmentPlugin({
          writeKey: config.writeKey
        })
      ]
    });

// then anywhere else 
 GlobalVariables.analytics.track(eventName, payload);
```
