### ISSUE TITLE
Removing Injected Scripts from DOM?

### ISSUE THREAD

**Issue by jherdman** [DavidWells/analytics#78]
Upon reading the API it's not clear how to remove injected scripts from the DOM. How does one accomplish this?

**Comment by DavidWells** [comment]
Hey @jherdman 

To my knowledge, it's not possible to "unload" a script once it's loaded and executed.

What use case are you trying to achieve with removing a script?

**Comment by DavidWells** [comment]
Going to close this. Let me know if you have any additional information to add

**Comment by jherdman** [comment]
Hi David!

I'm a maintainer of [ember-metrics](https://github.com/adopted-ember-addons/ember-metrics). A community member had mentioned that this lib might be a great fit to be the unpinning of our package instead of our own homespun solution.

The use case we have for DOM removal is testing. Though a script may not unload when you remove it from the DOM, the DOM node itself does which is important for clean up and testing — even if this doesn't happen in the real world.
