### ISSUE TITLE
analytics.alias ?

### ISSUE THREAD

**Issue by tommedema** [DavidWells/analytics#8]
I'm using the Segment plugin, where my Segment account is configured to forward events to Mixpanel. Mixpanel defines its own unique distinct ID for each user and it is necessary for me to call Segment's alias method to then link my user's anonymous ID with Mixpanel's distinct ID. See also [1](https://help.mixpanel.com/hc/en-us/articles/115004496863?input_string=anonymous+id+not+used+as+distinct+ids) and [2](https://segment.com/docs/destinations/mixpanel/#alias) (note that I am not using user IDs as my app does not require registration; instead I use anonymous IDs).

However the analytics API seems to lack the `alias` function. How would I then call Segment's alias method?

**Comment by DavidWells** [comment]
Good question 😃

Right now alias isn’t part of the core API. Still trying to figure out how many providers actually use this functionality

For the time being you can just call your normal segment method ‘analytics.alias’ should be available in the global window.

If you are exposing the analytics (this lib) globally you will want to use window.Analytics (capital A) to avoid colliding with segment

—-

The alternative approach is setting up segment on the server side with the node implementation. This would probably be more work than it’s worth for you tho

**Comment by tommedema** [comment]
I see. So `window.Analytics` (capital A) refers to Segment's analytics library, not yours?

**Comment by DavidWells** [comment]
window.analytics is referring to raw segment code including alias

This lib isn’t exposed to the window by design. But you can expose it to whatever global namespace you want. I usually expose window.Analytics capital A if I need to (eg in Gatsby )

**Comment by tommedema** [comment]
Got it; thanks!
