### ISSUE TITLE
Cannot read property 'match' of undefined exception in @analytics/segment

### ISSUE THREAD

**Issue by daviddfm** [DavidWells/analytics#88]
In production I'm seeing an exception "Cannot read property 'match' of undefined" - If you look at the code below the fix should be easy... test src exists before trying to match it.  Not all <script> tags have a src property.....

```
function isScriptLoaded() {
      const scripts = document.getElementsByTagName('script')
      return !!Object.keys(scripts).filter((key) => {
        const { src } = scripts[key]
        return src.match(/cdn\.segment\.com\/analytics.js\/v1\//)
      }).length
    }
```

**Comment by DavidWells** [comment]
Thanks for report!

Fixed with `@analytics/segment@0.4.2`
