### ISSUE TITLE
analytics.ready suggested use?

### ISSUE THREAD

**Issue by tommedema** [DavidWells/analytics#9]
Let's say I want to track a certain view from being rendered:

```
export default function MyView(props) {
  useEffect(() => {
    analytics.page({ title: 'My View' })
  }, [])

  return (
    <div>
      <p>
        Yeehaw!
      </p>
    </div>
  )
}
```

Would the above be correct or would you always have to first wait for the analytics library to load? Or is this done internally anyway? E.g.:

```
  useEffect(() => {
    analytics.ready(() => {
      analytics.page({ title: 'My View' })
    })
  }, [])
```

**Comment by tommedema** [comment]
FYI in noticed that this is advertised as a feature in the README but when going through the codebase I've been unable to find logic where you're waiting for "ready" before queued actions are executed by plugins. I've found this but it's commented out: https://github.com/DavidWells/analytics/blob/3cc68daf89d140dbc72952b936fd5eca3b62ff6a/packages/analytics-core/src/middleware/plugins/engine.js#L302

**Comment by DavidWells** [comment]
`analytics.ready` will work the way you described above.

There ready code fires from here https://github.com/DavidWells/analytics/blob/master/packages/analytics-core/src/middleware/plugins/index.js#L39-L86

Checkout the demo site https://analytics-demo.netlify.com/ to see the lifecycle in action.

I'd recommend forking https://github.com/DavidWells/analytics/tree/master/examples/demo and using that as a playground of sorts with your integrations set in here https://github.com/DavidWells/analytics/blob/bfae6bfd610da3b56e2f050dd15172220d60be4c/examples/demo/src/utils/analytics/index.js#L24

`analytics.ready` waits for all plugins to load. If you have a load failure it will timeout at 10 seconds and fire regardless. This 10 second timeout will likely be a configurable option in the future.

--- 

The todo in the code is for figuring out offline & retry queuing logic. Thats a bigger fish to fry as every analytics provider out there acts in its own special way 🙈

**Comment by DavidWells** [comment]
Also if you see anything odd or have feature requests let me know 😃

What project are you using `analytics` on?

**Comment by tommedema** [comment]
Thanks! However, I was not referring to how/if `.ready` works. What I was wondering is if you're checking for analytics.ready prior to sending calls like `.track` or `.page` internally, or if I should do this check manually.

So, `analytics.ready` will work the way I described, but is it necessary? It seems a little excessive to wrap every event trigger in a `.ready` call. I also wonder if the `.ready` callback will fire if the plugins were already ready before attaching the listener -- from my code review I don't think so.

I'm using analytics for my startup's soft launch. We're using behavioral data to determine our ideal target audience and their use cases.

P.S. I also live in SF. Let's grab coffee some time ;)

**Comment by DavidWells** [comment]
Ready only fires once when the page loads

So it wouldn’t work for client side routing.

You can call track and page before ready and they will get queued for when the given provider is loaded into the page.

So in that hook you should just be able to call analytics.track/page without ready 

You can verify everything is working by looking at your network tab to see the calls or add ‘debug: true’ to the initial analytics setup where the plugins are registered. (See demo app)

The debug flag will expose redux dev tools for you to visualize everything that is happening 🤩

**Comment by DavidWells** [comment]
![analytics-debug-two](https://user-images.githubusercontent.com/532272/58361929-ea55df80-7e5f-11e9-9753-f3fd23265156.gif)

Here is the example https://github.com/DavidWells/analytics/blob/master/examples/demo/src/utils/analytics/index.js#L23

Also yeah lets grab some coffee!

**Comment by tommedema** [comment]
> they will get queued for when the given provider is loaded into the page

Ah, cool. That's the part that I couldn't find in the code review. ;)

Thanks for sharing the debug flag. Looks cool!

I'll send you an email re coffee
