### ISSUE TITLE
Plugin Request: Plausible Analytics

### ISSUE THREAD

**Issue by JotaPe** [DavidWells/analytics#96]
They're great for people that want self-hosted Analytics, I want to use the React Hooks with Plausible Analytics, if it's not so hard even try to implement myself and share here.

**Comment by DavidWells** [comment]
Sounds good to me.

The docs on writing a plugin are over here: https://getanalytics.io/plugins/writing-plugins/#1-provider-plugins

Holler if you have any questions!

**Comment by DavidWells** [comment]
A consolidated issue has been created at https://github.com/DavidWells/analytics/issues/153 for plugin requests.

Feel free to comment/reopen this thread if you have begun active development on this plugin.

**Comment by Florian-Guillot-Axa** [comment]
Hello,

I saw that this plugin https://www.npmjs.com/package/analytics-plugin-plausible/v/0.0.3 allow Plausible from this pr https://github.com/DavidWells/analytics/pull/168
But I don't see Plausible on the plugin list https://getanalytics.io/plugins/request/#currently-supported-plugins.
Is it just a mistake in the documentation, or is it something else ?

Thanks
